{
 "title": "Oracle DB Size",
 "description": "Oracle Tablespace Size",
 "tags": [
  "CI-TEC",
  "Oracle",
  "Others"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": { "query": "label_values(oracledb_up,job)" } },
   {
    "name": "alias",
    "label": "alias",
    "query": {
     "query": "label_values(oracledb_up{job=~\"$group\"},alias)"
    }
   },
   {
    "name": "tablespace",
    "label": "tablespace",
    "query": {
     "query": "query_result(avg_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=\"PERMANENT\"}[24h]))"
    }
   },
   { "name": "diff_intv2", "label": "Comparision Period", "query": "7d" },
   {
    "name": "top_pct",
    "label": "top_pct",
    "query": {
     "query": "query_result(topk(3, avg_over_time(oracledb_tablespace_usage_used_percent{alias=~\"$alias\" }[24h])))"
    }
   },
   {
    "name": "other_space",
    "label": "other_space",
    "query": {
     "query": "query_result(avg_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents!~\"PERMANENT\" }[24h]))"
    }
   }
  ]
 },
 "panels": [
  { "title": "DB Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Size",
   "type": "timeseries",
   "description": "only permenant tablespace usage",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\",}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\n    sum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=\"PERMANENT\"}[24h])) without(__name__)\r\n) by (job, alias)",
     "legendFormat": "total"
    },
    {
     "expr": "sum(sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\",}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\n    sum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=\"PERMANENT\"}[24h])) without(__name__)\r\n) by (job, alias)",
     "legendFormat": "used"
    },
    {
     "expr": "sum(sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\",}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\n    sum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=\"PERMANENT\"}[24h])) without(__name__)\r\n) by (job, alias)\r\n-\r\nsum(sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\",}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\n    sum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=\"PERMANENT\"}[24h])) without(__name__)\r\n) by (job, alias)",
     "legendFormat": "free"
    }
   ]
  },
  {
   "type": "table",
   "description": "DB Size",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\"}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\n    sum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=\"PERMANENT\"}[24h])) without(__name__)\r\n) by (job, alias)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\", }[24h])) without(__name__) * on (job, alias, tablespace_name )\r\n    sum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=\"PERMANENT\"}[24h])) without(__name__)\r\n) by (job, alias)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\", }[24h] offset 24h)) without(__name__) * on (job, alias, tablespace_name )\r\n    sum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=\"PERMANENT\"}[24h] offset 24h)) without(__name__)\r\n) by (job, alias)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\", }[24h] offset 30d)) without(__name__) * on (job, alias, tablespace_name )\r\n    sum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=\"PERMANENT\"}[24h] offset 30d)) without(__name__)\r\n) by (job, alias)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\", }[24h])) without(__name__) * on (job, alias, tablespace_name )\r\n    sum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=\"TEMPORARY\"}[24h])) without(__name__)\r\n) by (job, alias)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\", }[24h])) without(__name__) * on (job, alias, tablespace_name )\r\n    sum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=\"UNDO\"}[24h])) without(__name__)\r\n) by (job, alias)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "description": "DB Size",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\"}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\n    sum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=\"PERMANENT\"}[24h])) without(__name__)\r\n) by (job, alias)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\", }[24h])) without(__name__) * on (job, alias, tablespace_name )\r\n    sum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=\"PERMANENT\"}[24h])) without(__name__)\r\n) by (job, alias)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\", }[24h] offset $diff_intv2)) without(__name__) * on (job, alias, tablespace_name )\r\n    sum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=\"PERMANENT\"}[24h] offset $diff_intv2)) without(__name__)\r\n) by (job, alias)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\", }[24h])) without(__name__) * on (job, alias, tablespace_name )\r\n    sum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=\"TEMPORARY\"}[24h])) without(__name__)\r\n) by (job, alias)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\", }[24h])) without(__name__) * on (job, alias, tablespace_name )\r\n    sum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=\"UNDO\"}[24h])) without(__name__)\r\n) by (job, alias)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Data Tablespaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Tablespace Size - Data Growth (-$diff_intv2)",
   "type": "table",
   "description": "Tablespace Size",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\"}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=~\"PERMANENT\"}[24h])) without(__name__)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\"}[24h])) without(__name__) - on (job, alias, tablespace_name )\r\n sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\"}[24h])) without(__name__)\r\n) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=~\"PERMANENT\"}[24h])) without(__name__)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\"}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=~\"PERMANENT\"}[24h])) without(__name__)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(last_over_time(oracledb_tablespace_usage_used_percent{alias=~\"$alias\"}[24h])) without(__name__)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=~\"PERMANENT\"}[24h])) without(__name__)",
     "legendFormat": "__auto"
    },
    {
     "expr": "( sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\"}[24h])) without(__name__) - on (job, alias, tablespace_name )\r\n  sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\"}[24h] offset $diff_intv2)) without(__name__))\r\n* on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=~\"PERMANENT\"}[24h])) without(__name__)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Used (%) - Top 3 Tablespaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "$top_pct",
   "type": "timeseries",
   "description": "tablespace usage",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "repeat": "top_pct",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\", tablespace_name=~\"$top_pct\"}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", tablespace_name=~\"$top_pct\"}[24h])) without(__name__)",
     "legendFormat": "total"
    },
    {
     "expr": "sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\", tablespace_name=~\"$top_pct\"}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", tablespace_name=~\"$top_pct\"}[24h])) without(__name__)",
     "legendFormat": "used"
    },
    {
     "expr": "(sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\", tablespace_name=~\"$top_pct\"}[24h])) without(__name__) - on (job, alias, tablespace_name )\r\n sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\", tablespace_name=~\"$top_pct\"}[24h])) without(__name__)\r\n) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", tablespace_name=~\"$top_pct\"}[24h])) without(__name__)",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Selected Tablespaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "$tablespace",
     "type": "timeseries",
     "description": "tablespace usage",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
     "repeat": "tablespace",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\", tablespace_name=~\"$tablespace\"}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", tablespace_name=~\"$tablespace\"}[24h])) without(__name__)",
       "legendFormat": "total"
      },
      {
       "expr": "sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\", tablespace_name=~\"$tablespace\"}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", tablespace_name=~\"$tablespace\"}[24h])) without(__name__)",
       "legendFormat": "used"
      },
      {
       "expr": "(sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\", tablespace_name=~\"$tablespace\"}[24h])) without(__name__) - on (job, alias, tablespace_name )\r\n sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\", tablespace_name=~\"$tablespace\"}[24h])) without(__name__)\r\n) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", tablespace_name=~\"$tablespace\"}[24h])) without(__name__)",
       "legendFormat": "free"
      }
     ]
    }
   ]
  },
  {
   "title": "Temporary, Undo Tablespaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Tablespace Size",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\"}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents!~\"PERMANENT\"}[24h])) without(__name__)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\"}[24h])) without(__name__) - on (job, alias, tablespace_name )\r\n sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\"}[24h])) without(__name__)\r\n) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents!~\"PERMANENT\"}[24h])) without(__name__)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\"}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents!~\"PERMANENT\"}[24h])) without(__name__)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_tablespace_usage_used_percent{alias=~\"$alias\"}[24h])) without(__name__)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents!~\"PERMANENT\"}[24h])) without(__name__)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$other_space",
     "type": "timeseries",
     "description": "tablespace usage",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
     "repeat": "other_space",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\", tablespace_name=~\"$other_space\"}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", tablespace_name=~\"$other_space\"}[24h])) without(__name__)",
       "legendFormat": "total"
      },
      {
       "expr": "sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\", tablespace_name=~\"$other_space\"}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", tablespace_name=~\"$other_space\"}[24h])) without(__name__)",
       "legendFormat": "used"
      },
      {
       "expr": "(sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\", tablespace_name=~\"$other_space\"}[24h])) without(__name__) - on (job, alias, tablespace_name )\r\n sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\", tablespace_name=~\"$other_space\"}[24h])) without(__name__)\r\n) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", tablespace_name=~\"$other_space\"}[24h])) without(__name__)",
       "legendFormat": "free"
      }
     ]
    }
   ]
  }
 ]
}