{
 "title": "Oracle SQL Details",
 "description": "Oracle SQL Details (2024-09-11)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "alias", "label": "alias" },
   {
    "name": "plan_hash_value",
    "label": "plan_hash_value",
    "query": {
     "query": "query_result(avg_over_time(oracledb_ora_top_cpu_sqls_elapsed_time_total{alias=\"$alias\", sql_id=\"$sql_id\"}[$diff_intv]))"
    }
   },
   { "name": "intv", "label": "interval", "query": "30s, 1m, 5m, 30m, 1h, 6h, 12h" },
   { "name": "use_diff", "label": "Comparison", "query": "On : 1, Off : 0" },
   { "name": "diff_intv", "label": "Comp. Period", "query": "1d" },
   { "name": "sql_id", "label": "sql_id", "query": "dc6pajnpnpggb" },
   {
    "name": "sql_text",
    "label": "sql_text",
    "query": "select COMPCD ,IDNO ,ATTNCCD ,BEGINDT ,ENDDT ,BEGINTIME ,END"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "sql_id : $sql_id<br>\r\n${sql_text}<br>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 5 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n<br>\r\n<br>\r\n  Retrieval time\r\n</div>"
   }
  },
  {
   "type": "table",
   "description": "Top SQLs ordered by Elapsed Time",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(oracledb_ora_top_cpu_sqls_elapsed_time_total{alias=\"$alias\", sql_id=\"$sql_id\"}[$__range])/1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(oracledb_ora_top_cpu_sqls_cpu_time_total{alias=\"$alias\", sql_id=\"$sql_id\"}[$__range])/1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(oracledb_ora_top_cpu_sqls_executions_total{alias=\"$alias\", sql_id=\"$sql_id\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(oracledb_ora_top_cpu_sqls_buffer_gets_total{alias=\"$alias\", sql_id=\"$sql_id\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(oracledb_ora_top_cpu_sqls_disk_reads_total{alias=\"$alias\", sql_id=\"$sql_id\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 10 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\nDiff : -${diff_intv}\r\n</div>\r\n"
   }
  },
  {
   "type": "table",
   "description": "Top SQLs ordered by Elapsed Time",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(oracledb_ora_top_cpu_sqls_elapsed_time_total{alias=\"$alias\", sql_id=\"$sql_id\"}[$__range] offset $diff_intv)/1000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(oracledb_ora_top_cpu_sqls_cpu_time_total{alias=\"$alias\", sql_id=\"$sql_id\"}[$__range] offset $diff_intv)/1000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(oracledb_ora_top_cpu_sqls_executions_total{alias=\"$alias\", sql_id=\"$sql_id\"}[$__range] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(oracledb_ora_top_cpu_sqls_buffer_gets_total{alias=\"$alias\", sql_id=\"$sql_id\"}[$__range] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(oracledb_ora_top_cpu_sqls_disk_reads_total{alias=\"$alias\", sql_id=\"$sql_id\"}[$__range] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Graph - Sum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Elapsed Time(s) - Sum",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_elapsed_time_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\"}[$intv])/1000) by (sql_id)",
     "legendFormat": "Basetime"
    },
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_elapsed_time_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\"}[$intv] offset $diff_intv)/1000) by (sql_id)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "Comp: -$diff_intv"
    }
   ]
  },
  {
   "title": "CPU Time(s) - Sum",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_cpu_time_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\"}[$intv])/1000) by (sql_id)",
     "legendFormat": "Basetime"
    },
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_cpu_time_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\"}[$intv] offset $diff_intv)/1000) by (sql_id)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "Comp: -$diff_intv"
    }
   ]
  },
  {
   "title": "Executions - Sum",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_executions_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\"}[$intv])) by (sql_id)",
     "legendFormat": "Basetime"
    },
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_executions_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\"}[$intv] offset $diff_intv)) by (sql_id)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "Comp: -$diff_intv"
    }
   ]
  },
  {
   "title": "Buffer Gets - Sum",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_buffer_gets_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\"}[$intv])) by (sql_id)\r\n\r\n",
     "legendFormat": "Basetime"
    },
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_buffer_gets_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\"}[$intv] offset $diff_intv)) by (sql_id)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "Comp: -$diff_intv"
    }
   ]
  },
  {
   "title": "Disk Reads - Sum",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_disk_reads_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\"}[$intv])) by (sql_id)",
     "legendFormat": "Basetime"
    },
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_disk_reads_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\"}[$intv] offset $diff_intv)) by (sql_id)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "Comp: -$diff_intv"
    }
   ]
  },
  {
   "title": "Disk Writes - Sum",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_direct_writes_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\"}[$intv])) by (sql_id)",
     "legendFormat": "Basetime"
    },
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_direct_writes_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\"}[$intv] offset $diff_intv)) by (sql_id)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "Comp: -$diff_intv"
    }
   ]
  },
  {
   "title": "Graph - each plan_hash_value",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elapsed Time(s)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(oracledb_ora_top_cpu_sqls_elapsed_time_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\", plan_hash_value=~\"$plan_hash_value\"}[$intv])/1000) by (sql_id, plan_hash_value)",
       "legendFormat": "{{plan_hash_value}}"
      },
      {
       "expr": "sum(rate(oracledb_ora_top_cpu_sqls_elapsed_time_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\", plan_hash_value=~\"$plan_hash_value\"}[$intv] offset $diff_intv)/1000) by (sql_id, plan_hash_value)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{plan_hash_value}}: -$diff_intv"
      }
     ]
    },
    {
     "title": "CPU Time(s)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(oracledb_ora_top_cpu_sqls_cpu_time_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\", plan_hash_value=~\"$plan_hash_value\"}[$intv])/1000) by (sql_id, plan_hash_value)",
       "legendFormat": "{{plan_hash_value}}"
      },
      {
       "expr": "sum(rate(oracledb_ora_top_cpu_sqls_cpu_time_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\", plan_hash_value=~\"$plan_hash_value\"}[$intv] offset $diff_intv)/1000) by (sql_id, plan_hash_value)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{plan_hash_value}}: -$diff_intv"
      }
     ]
    },
    {
     "title": "Executions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(oracledb_ora_top_cpu_sqls_executions_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\", plan_hash_value=~\"$plan_hash_value\"}[$intv])) by (sql_id, plan_hash_value)",
       "legendFormat": "{{plan_hash_value}}"
      },
      {
       "expr": "sum(rate(oracledb_ora_top_cpu_sqls_executions_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\", plan_hash_value=~\"$plan_hash_value\"}[$intv] offset $diff_intv)) by (sql_id, plan_hash_value)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{plan_hash_value}}: -$diff_intv"
      }
     ]
    },
    {
     "title": "Buffer Gets",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(oracledb_ora_top_cpu_sqls_buffer_gets_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\", plan_hash_value=~\"$plan_hash_value\"}[$intv])) by (sql_id, plan_hash_value)\r\n\r\n",
       "legendFormat": "{{plan_hash_value}}"
      },
      {
       "expr": "sum(rate(oracledb_ora_top_cpu_sqls_buffer_gets_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\", plan_hash_value=~\"$plan_hash_value\"}[$intv] offset $diff_intv)) by (sql_id, plan_hash_value)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{plan_hash_value}}: -$diff_intv"
      }
     ]
    },
    {
     "title": "Disk Reads",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(oracledb_ora_top_cpu_sqls_disk_reads_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\", plan_hash_value=~\"$plan_hash_value\"}[$intv])) by (sql_id, plan_hash_value)",
       "legendFormat": "{{plan_hash_value}}"
      },
      {
       "expr": "sum(rate(oracledb_ora_top_cpu_sqls_disk_reads_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\", plan_hash_value=~\"$plan_hash_value\"}[$intv] offset $diff_intv)) by (sql_id, plan_hash_value)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{plan_hash_value}}: -$diff_intv"
      }
     ]
    },
    {
     "title": "Disk Writes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(oracledb_ora_top_cpu_sqls_direct_writes_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\", plan_hash_value=~\"$plan_hash_value\"}[$intv])) by (sql_id, plan_hash_value)",
       "legendFormat": "{{plan_hash_value}}"
      },
      {
       "expr": "sum(rate(oracledb_ora_top_cpu_sqls_direct_writes_total{sql_id=~\"$sql_id.*\", alias=~\"$alias\", plan_hash_value=~\"$plan_hash_value\"}[$intv] offset $diff_intv)) by (sql_id, plan_hash_value)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{plan_hash_value}}: -$diff_intv"
      }
     ]
    }
   ]
  },
  { "title": "Wait Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Wait Table / Index (cnt)",
   "type": "table",
   "description": "This information is sampled data from v$session.\nThe numbers represent the number of sampling occurrences",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(oracledb_ora_wait_sess_value{alias=~\"$alias\", wait_info=~\".*\\\\[.*\\\\].*\", sqlid=\"$sql_id\"}) by (wait_info)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "count(oracledb_ora_wait_sess_value{alias=~\"$alias\", wait_info=~\".*\\\\[.*\\\\].*\", sqlid=\"$sql_id\"} offset $diff_intv) by (wait_info)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Wait Events (cnt)",
   "type": "table",
   "description": "This information is sampled data from v$session.\nThe numbers represent the number of sampling occurrences",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(oracledb_ora_wait_sess_value{alias=~\"$alias\", sqlid=\"$sql_id\"}) by (wait_event)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "count(oracledb_ora_wait_sess_value{alias=~\"$alias\", sqlid=\"$sql_id\"} offset $diff_intv) by (wait_event)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Wait Info (cnt)",
   "type": "table",
   "description": "This information is sampled data from v$session.\nThe numbers represent the number of sampling occurrences",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(oracledb_ora_wait_sess_value{alias=~\"$alias\", wait_info!~\".*\\\\[.*\\\\].*|.*novalue.*\", sqlid=\"$sql_id\"}) by (wait_info)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "count(oracledb_ora_wait_sess_value{alias=~\"$alias\", wait_info!~\".*\\\\[.*\\\\].*|.*novalue.*\", sqlid=\"$sql_id\"} offset $diff_intv) by (wait_info)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Wait Table / Index (cnt)",
   "type": "piechart",
   "description": "This information is sampled data from v$session.\nThe numbers represent the number of sampling occurrences",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(oracledb_ora_wait_sess_value{alias=~\"$alias\", wait_info=~\".*\\\\[.*\\\\].*\", sqlid=\"$sql_id\"}) by (wait_info)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Wait Events (cnt)",
   "type": "piechart",
   "description": "This information is sampled data from v$session.\nThe numbers represent the number of sampling occurrences",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(oracledb_ora_wait_sess_value{alias=~\"$alias\", sqlid=\"$sql_id\"}) by (wait_event)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Wait Info (cnt)",
   "type": "piechart",
   "description": "This information is sampled data from v$session.\nThe numbers represent the number of sampling occurrences",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(oracledb_ora_wait_sess_value{alias=~\"$alias\", wait_info!~\".*\\\\[.*\\\\].*|.*novalue.*\", sqlid=\"$sql_id\"}) by (wait_info)",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}