{
 "title": "Oracle Sessions",
 "description": "Oracle Sessions (2024-10-30)",
 "tags": [
  "CI-TEC",
  "Oracle",
  "Others"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": { "query": "label_values(oracledb_up,job)" } },
   {
    "name": "alias",
    "label": "alias",
    "query": {
     "query": "label_values(oracledb_up{job=~\"$group\"},alias)"
    }
   },
   { "name": "sid", "label": "SID" },
   { "name": "event", "label": "Wait Event" },
   { "name": "winfo", "label": "Wait Info" },
   { "name": "sql_id", "label": "sql_id (Min 5 chars.)" }
  ]
 },
 "panels": [
  { "title": "Active Session Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Session Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(oracledb_ora_wait_sess_value{alias=~\"$alias\"})",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Wait Events",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(oracledb_ora_wait_sess_value{alias=~\"$alias\"}) by (wait_event)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Wait Info",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(oracledb_ora_wait_sess_value{alias=~\"$alias\", wait_info!~\".*,.*|novalue\"}) by (wait_info)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Command",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(oracledb_ora_wait_sess_value{alias=~\"$alias\"}) by (cmd)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Mudule",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(oracledb_ora_wait_sess_value{alias=~\"$alias\"}) by (module)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "SQL_ID",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(oracledb_ora_wait_sess_value{alias=~\"$alias\"}) by (sqlid)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Active Session List", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "type": "table",
   "description": "Top 20 Wait Sessions sory by CPU",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "oracledb_ora_wait_sess_value{alias=~\"$alias\", sid=~\".*$sid,.*\", wait_event=~\"(?s)(?i).*$event.*\", wait_info=~\"(?s)(?i).*$winfo.*\", sqlid=~\"(?s)(?i).*$sql_id.*\" }",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}