{
 "title": "Oracle One Instance",
 "description": "Oracle One Instance",
 "tags": [
  "CI-TEC",
  "Oracle",
  "One"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": { "query": "label_values(oracledb_up,job)" } },
   {
    "name": "alias",
    "label": "alias",
    "query": {
     "query": "label_values(oracledb_up{job=~\"$group\"},alias)"
    }
   },
   { "name": "intv", "label": "interval", "query": "30s, 1m, 5m, 30m, 1h, 6h, 12h" },
   { "name": "use_diff", "label": "Comparison", "query": "On : 1, Off : 0" },
   { "name": "diff_intv", "label": "Comp. Period", "query": "1d" }
  ]
 },
 "panels": [
  {
   "title": "DB Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(last_over_time(oracledb_instance{alias=~\"$alias\"}[24h])) by (alias, instance, job, version, instance_name, host_name, archiver, startup_time)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_database{alias=~\"$alias\"}[24h])) by (alias, instance, job, name, log_mode, database_role, platform_name, flashback_on)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(last_over_time(oracledb_param{name=\"sga_target\", alias=~\"$alias\"}[24h])) by (alias, instance, job)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_param{name=\"sga_max_size\", alias=~\"$alias\"}[24h])) by (alias, instance, job)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_param{name=\"memory_target\", alias=~\"$alias\"}[24h])) by (alias, instance, job)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_param{name=\"memory_max_target\", alias=~\"$alias\"}[24h])) by (alias, instance, job)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_param{name=\"db_cache_size\", alias=~\"$alias\"}[24h])) by (alias, instance, job)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_param{name=\"shared_pool_size\", alias=~\"$alias\"}[24h])) by (alias, instance, job)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_param{name=\"java_pool_size\", alias=~\"$alias\"}[24h])) by (alias, instance, job)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_param{name=\"large_pool_size\", alias=~\"$alias\"}[24h])) by (alias, instance, job)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_param{name=\"pga_aggregate_limit\", alias=~\"$alias\"}[24h])) by (alias, instance, job)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_param{name=\"pga_aggregate_target\", alias=~\"$alias\"}[24h])) by (alias, instance, job)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_ora_memstat_value{stat_name=\"PHYSICAL_MEMORY_BYTES\", alias=~\"$alias\"}[24h])) by (alias, instance, job)",
       "legendFormat": "__auto"
      },
      {
       "expr": "ceil(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Usage Per Sec\"} / ignoring(metric_name) \r\n oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Utilization (%)\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Host CPU Utilization (%)",
   "type": "timeseries",
   "description": "Host user% + sys%",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Utilization (%)\"}[$intv])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Utilization (%)\"}[$intv] offset $diff_intv) \r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Oracle CPU (%)",
   "type": "timeseries",
   "description": "Oracle user% + sys%",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"CPU Usage Per Sec\"}[$intv]) / ignoring(metric_name) \r\n(avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Usage Per Sec\"}[$intv]) / ignoring(metric_name) \r\n avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Utilization (%)\"}[$intv])\r\n)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"CPU Usage Per Sec\"}[$intv] offset $diff_intv)/ ignoring(metric_name) \r\n(avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Usage Per Sec\"}[$intv] offset $diff_intv) / ignoring(metric_name) \r\n avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Utilization (%)\"}[$intv] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "DB Time (s)",
   "type": "timeseries",
   "description": "DB Time = CPU Time + Wait Time ",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Database Time Per Sec\"}[$intv]) /100",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Database Time Per Sec\"}[$intv] offset $diff_intv) /100\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "SQL Time (s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_elapsed_time_total{alias=~\"$alias\"}[$intv])/1000) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_elapsed_time_total{alias=~\"$alias\"}[$intv] offset $diff_intv)/1000) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "SQL Executions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_executions_total{alias=~\"$alias\"}[$intv])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_executions_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Logical Reads (blocks)",
   "type": "timeseries",
   "description": "Logical Reads  = DB Block Gets + Consistent Read Gets\nThis metric represents the number of logical reads per second.\nA logical read is a read request for a data block from the SGA. \nLogical reads may result in a physical read if the requested block does not reside with the buffer cache.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Logical Reads Per Sec\"}[$intv])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Logical Reads Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Wait Events Time(s) - Basetime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\"}[$intv])) by (alias,name) / 1000000",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\"}[$intv])) by (alias) / 1000000",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Physical Reads (bytes) ",
   "type": "timeseries",
   "description": "This metric represents bytes of data read from disk per second.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Read Bytes Per Sec\"}[$intv])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Read Bytes Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Physical Writes (bytes)",
   "type": "timeseries",
   "description": "This statistic represents database bytes written to SGA buffers cached to disk by the DBWR background process and PGA by processes performing direct writes.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Write Bytes Per Sec\"}[$intv])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Write Bytes Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Current Logons Count",
   "type": "timeseries",
   "description": "This metric represents the current number of logons.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Current Logons Count\"}[$intv])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Current Logons Count\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Long Table Scans",
   "type": "timeseries",
   "description": "This metric represents the number of long table scans per second during sample period. \nA table is considered 'long' if the table is not cached and if its high-water mark is greater than 5 blocks.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Long Table Scans Per Sec\"}[$intv])\r\n",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Long Table Scans Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  { "title": "Top SQLs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "type": "table",
   "description": "Top SQLs ordered by Elapsed Time",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_elapsed_time_total{alias=~\"$alias\"}[$__range])/1000\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_cpu_time_total{alias=~\"$alias\"}[$__range])/1000\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_executions_total{alias=~\"$alias\"}[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_buffer_gets_total{alias=~\"$alias\"}[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_disk_reads_total{alias=~\"$alias\"}[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_elapsed_time_total{alias=~\"$alias\"}[$__range] offset $diff_intv)/1000\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_cpu_time_total{alias=~\"$alias\"}[$__range] offset $diff_intv)/1000\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_executions_total{alias=~\"$alias\"}[$__range] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_buffer_gets_total{alias=~\"$alias\"}[$__range] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_disk_reads_total{alias=~\"$alias\"}[$__range] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "description": "CPU & Memory Size",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ceil(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Usage Per Sec\"} / ignoring(metric_name) \r\n oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Utilization (%)\"})",
       "legendFormat": "CPUs"
      },
      {
       "expr": "oracledb_ora_memstat_value{alias=~\"$alias\", stat_name=\"PHYSICAL_MEMORY_BYTES\"}/1024",
       "legendFormat": "MEM(GB)"
      },
      {
       "expr": "oracledb_ora_startup_time_minutes{alias=~\"$alias\"}",
       "legendFormat": "Uptime"
      }
     ]
    },
    {
     "title": "Host CPU Utilization (%)",
     "type": "timeseries",
     "description": "Host user% + sys%",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Utilization (%)\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Utilization (%)\"}[$intv] offset $diff_intv) \r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Oracle CPU (%)",
     "type": "timeseries",
     "description": "Oracle user% + sys%",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"CPU Usage Per Sec\"}[$intv]) / ignoring(metric_name) \r\n(\r\navg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Usage Per Sec\"}[$intv]) / ignoring(metric_name) \r\navg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Utilization (%)\"}[$intv])\r\n)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"CPU Usage Per Sec\"}[$intv] offset $diff_intv) / ignoring(metric_name) \r\n(\r\navg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Usage Per Sec\"}[$intv] offset $diff_intv) / ignoring(metric_name) \r\navg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Utilization (%)\"}[$intv] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Oracle Background CPU (%)",
     "type": "timeseries",
     "description": "Oracle user% + sys%",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Background CPU Usage Per Sec\"} / ignoring(metric_name) \r\n(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Usage Per Sec\"} / ignoring(metric_name) \r\n oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Utilization (%)\"})",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Background CPU Usage Per Sec\"} offset $diff_intv/ ignoring(metric_name) \r\n(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Usage Per Sec\"} offset $diff_intv / ignoring(metric_name) \r\n oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Utilization (%)\"} offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "OS Active Memory (%)",
     "type": "timeseries",
     "description": "= (Physical Memory - Inactive Memory) / Physical Memory",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "(oracledb_ora_memstat_value{alias=~\"$alias\",stat_name=\"PHYSICAL_MEMORY_BYTES\"} - ignoring(stat_name)\r\n oracledb_ora_memstat_value{alias=~\"$alias\",stat_name=\"INACTIVE_MEMORY_BYTES\"}) / ignoring(stat_name)\r\noracledb_ora_memstat_value{alias=~\"$alias\",stat_name=\"PHYSICAL_MEMORY_BYTES\"} * 100",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(oracledb_ora_memstat_value{alias=~\"$alias\",stat_name=\"PHYSICAL_MEMORY_BYTES\"} offset $diff_intv - ignoring(stat_name)\r\n oracledb_ora_memstat_value{alias=~\"$alias\",stat_name=\"INACTIVE_MEMORY_BYTES\"} offset $diff_intv) / ignoring(stat_name)\r\noracledb_ora_memstat_value{alias=~\"$alias\",stat_name=\"PHYSICAL_MEMORY_BYTES\"}  offset $diff_intv * 100\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "OS Used Memory (%)",
     "type": "timeseries",
     "description": "= (Physical Memory - Free Memory) / Physical Memory",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "(oracledb_ora_memstat_value{alias=~\"$alias\",stat_name=\"PHYSICAL_MEMORY_BYTES\"} - ignoring(stat_name)\r\n oracledb_ora_memstat_value{alias=~\"$alias\",stat_name=\"FREE_MEMORY_BYTES\"}) / ignoring(stat_name)\r\noracledb_ora_memstat_value{alias=~\"$alias\",stat_name=\"PHYSICAL_MEMORY_BYTES\"} * 100",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(oracledb_ora_memstat_value{alias=~\"$alias\",stat_name=\"PHYSICAL_MEMORY_BYTES\"} offset $diff_intv - ignoring(stat_name)\r\n oracledb_ora_memstat_value{alias=~\"$alias\",stat_name=\"FREE_MEMORY_BYTES\"} offset $diff_intv) / ignoring(stat_name)\r\noracledb_ora_memstat_value{alias=~\"$alias\",stat_name=\"PHYSICAL_MEMORY_BYTES\"}  offset $diff_intv * 100\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  },
  {
   "title": "Time Model & Wait Event Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB Time (s)",
     "type": "timeseries",
     "description": "DB Time = CPU Time + Wait Time ",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Database Time Per Sec\"}[$intv]) /100",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Database Time Per Sec\"}[$intv] offset $diff_intv) /100\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "CPU Time (s)",
     "type": "timeseries",
     "description": "DB Time = CPU Time + Wait Time ",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"CPU Usage Per Sec\"}[$intv]) / 100",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"CPU Usage Per Sec\"}[$intv] offset $diff_intv) / 100\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Total Wait Time (s)",
     "type": "timeseries",
     "description": "DB Time = CPU Time + Wait Time ",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\"}[$intv])) by (alias) / 1000000",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias) / 1000000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "CPU & Wait Time Ratio",
     "type": "timeseries",
     "description": "DB Time = CPU + Wait",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "oracledb_ora_metric_value {alias=~\"$alias\",metric_name=\"Database CPU Time Ratio\"}",
       "legendFormat": "CPU Ratio"
      },
      {
       "expr": "oracledb_ora_metric_value {alias=~\"$alias\",metric_name=\"Database Wait Time Ratio\"}",
       "legendFormat": "Wait Ratio"
      }
     ]
    },
    {
     "title": "Active Sessions",
     "type": "timeseries",
     "description": "Host user% + sys%",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_sessions_value{alias=~\"$alias\",status=\"ACTIVE\",type='USER'}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_sessions_value{alias=~\"$alias\",status=\"ACTIVE\",type='USER'}[$intv] offset $diff_intv) \r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Wait Events Time",
     "type": "table",
     "description": "DB Time = CPU Time + Wait Time ",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(100, last_over_time(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\"}[$__range])/1000000\r\n        - min_over_time(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\"}[$__range])/1000000) / $__range_s",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(100, last_over_time(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\"}[$__range] offset $diff_intv)/1000000\r\n        - min_over_time(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\"}[$__range] offset $diff_intv)/1000000) / $__range_s\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wait Events Time(s) - Basetime",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\"}[$intv])) by (alias,name) / 1000000",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\"}[$intv])) by (alias) / 1000000",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Wait Events Time(s) - Comparison (-$diff_intv)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias,name) / 1000000",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias) / 1000000",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "log file sync - Wait time(s)",
     "type": "timeseries",
     "description": "When a user session COMMITs (or rolls back), the sessions redo information needs to be flushed to the redo log file. \nThe user session will post the LGWR to write all redo required from the log buffer to the redo log file. \nWhen the LGWR has finished it will post the user session. \nThe user session waits on this wait event while waiting for LGWR to post it back to confirm all redo changes are safely on disk.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=\"log file sync\"}[$intv]) / 1000000",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=\"log file sync\"}[$intv] offset $diff_intv) / 1000000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "log file parallel write - W_tm(s)",
     "type": "timeseries",
     "description": "As the db file parallel write wait event belongs to the Oracle DBWR process, the log file parallel write wait event belongs to the Log Writer (LGWR) process. When it is time to write, the LGWR process writes the redo buffer to the online redo files in parallel and waits on the log file parallel write event until the last I/O is on disk.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=\"log file parallel write\"}[$intv]) / 1000000",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=\"log file parallel write\"}[$intv] offset $diff_intv) / 1000000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "db file sequential read - W_tm(s)",
     "type": "timeseries",
     "description": "This event shows a wait for a foreground process while doing a sequential read from the database. The I/O is generally issued as a single I/O request to the OS; the wait blocks until the I/O request completes.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=\"db file sequential read\"}[$intv]) / 1000000",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=\"db file sequential read\"}[$intv] offset $diff_intv) / 1000000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "db file scattered read - W_tm(s)",
     "type": "timeseries",
     "description": "This is the same type of event as \"db file sequential read\", except that Oracle will read multiple data blocks. Multi-block reads are typically used on full table scans. The name \"scattered read\" refers to the fact that multiple blocks are read into database block buffers that are 'scattered' throughout memory.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=\"db file scattered read\"}[$intv]) / 1000000",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=\"db file scattered read\"}[$intv] offset $diff_intv) / 1000000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "gc% event sum  - W_tm(s)",
     "type": "timeseries",
     "description": "- gc cr request\n- gc current block busy\n- gc ...",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=~\"gc.*\"}[$intv])) by (alias) / 1000000",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=~\"gc.*\"}[$intv] offset $diff_intv)) by (alias) / 1000000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "enq% event sum  - W_tm(s)",
     "type": "timeseries",
     "description": "- enq: TX - row lock contention\n- enq: TX - index contention\n- enq: CF - contention\n- enq: HW - contention\n- enq: KO - fast object checkpoint\n- enq: SQ - contention\n- ...",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=~\"enq.*\"}[$intv])) by (alias) / 1000000",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=~\"enq.*\"}[$intv] offset $diff_intv)) by (alias) / 1000000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "log file sync - Avg Wait time(ms)",
     "type": "timeseries",
     "description": "When a user session COMMITs (or rolls back), the sessions redo information needs to be flushed to the redo log file. \nThe user session will post the LGWR to write all redo required from the log buffer to the redo log file. \nWhen the LGWR has finished it will post the user session. \nThe user session waits on this wait event while waiting for LGWR to post it back to confirm all redo changes are safely on disk.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=\"log file sync\"}[$intv]) /\r\nrate(oracledb_ora_system_event_total_waits{alias=~\"$alias\", name=\"log file sync\"}[$intv]) / 1000",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=\"log file sync\"}[$intv] offset $diff_intv) /\r\nrate(oracledb_ora_system_event_total_waits{alias=~\"$alias\", name=\"log file sync\"}[$intv]  offset $diff_intv) / 1000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "log file parallel write - Avg W_tm(ms)",
     "type": "timeseries",
     "description": "As the db file parallel write wait event belongs to the Oracle DBWR process, the log file parallel write wait event belongs to the Log Writer (LGWR) process. When it is time to write, the LGWR process writes the redo buffer to the online redo files in parallel and waits on the log file parallel write event until the last I/O is on disk.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=\"log file parallel write\"}[$intv]) /\r\nrate(oracledb_ora_system_event_total_waits{alias=~\"$alias\", name=\"log file parallel write\"}[$intv]) / 1000",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=\"log file parallel write\"}[$intv] offset $diff_intv) /\r\nrate(oracledb_ora_system_event_total_waits{alias=~\"$alias\", name=\"log file parallel write\"}[$intv]  offset $diff_intv) / 1000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "db file sequential read - Avg W_tm(ms)",
     "type": "timeseries",
     "description": "This event shows a wait for a foreground process while doing a sequential read from the database. The I/O is generally issued as a single I/O request to the OS; the wait blocks until the I/O request completes.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=\"db file sequential read\"}[$intv]) /\r\nrate(oracledb_ora_system_event_total_waits{alias=~\"$alias\", name=\"db file sequential read\"}[$intv]) / 1000",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=\"db file sequential read\"}[$intv] offset $diff_intv) /\r\nrate(oracledb_ora_system_event_total_waits{alias=~\"$alias\", name=\"db file sequential read\"}[$intv]  offset $diff_intv) / 1000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "db file scattered read - Avg W_tm(ms)",
     "type": "timeseries",
     "description": "This is the same type of event as \"db file sequential read\", except that Oracle will read multiple data blocks. Multi-block reads are typically used on full table scans. The name \"scattered read\" refers to the fact that multiple blocks are read into database block buffers that are 'scattered' throughout memory.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=\"db file scattered read\"}[$intv]) /\r\nrate(oracledb_ora_system_event_total_waits{alias=~\"$alias\", name=\"db file scattered read\"}[$intv]) / 1000",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=\"db file scattered read\"}[$intv] offset $diff_intv) /\r\nrate(oracledb_ora_system_event_total_waits{alias=~\"$alias\", name=\"db file scattered read\"}[$intv]  offset $diff_intv) / 1000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "gc% event sum  - Avg W_tm(ms)",
     "type": "timeseries",
     "description": "- gc cr request\n- gc current block busy\n- gc ...",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=~\"gc.*\"}[$intv])) by (alias) /\r\nsum(rate(oracledb_ora_system_event_total_waits{alias=~\"$alias\", name=~\"gc.*\"}[$intv])) by (alias) / 1000",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=~\"gc.*\"}[$intv] offset $diff_intv)) by (alias) /\r\nsum(rate(oracledb_ora_system_event_total_waits{alias=~\"$alias\", name=~\"gc.*\"}[$intv] offset $diff_intv)) by (alias) / 1000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "enq% event sum  - Avg W_tm(ms)",
     "type": "timeseries",
     "description": "- enq: TX - row lock contention\n- enq: TX - index contention\n- enq: CF - contention\n- enq: HW - contention\n- enq: KO - fast object checkpoint\n- enq: SQ - contention\n- ...",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=~\"enq.*\"}[$intv])) by (alias) /\r\nsum(rate(oracledb_ora_system_event_total_waits{alias=~\"$alias\", name=~\"enq.*\"}[$intv])) by (alias) / 1000",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=~\"enq.*\"}[$intv] offset $diff_intv)) by (alias) /\r\nsum(rate(oracledb_ora_system_event_total_waits{alias=~\"$alias\", name=~\"enq.*\"}[$intv] offset $diff_intv)) by (alias) / 1000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  },
  {
   "title": "Logical I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logical Reads (blocks)",
     "type": "timeseries",
     "description": "Logical Reads  = DB Block Gets + Consistent Read Gets\nThis metric represents the number of logical reads per second.\nA logical read is a read request for a data block from the SGA. \nLogical reads may result in a physical read if the requested block does not reside with the buffer cache.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Logical Reads Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Logical Reads Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "DB Block Gets (blocks)",
     "type": "timeseries",
     "description": "Logical Reads  = DB Block Gets + Consistent Read Gets\nThis metric represents the number of times per second a current block was requested.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"DB Block Gets Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"DB Block Gets Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Consistent Read Gets (blocks)",
     "type": "timeseries",
     "description": "Logical Reads  = DB Block Gets + Consistent Read Gets\nThis metric represents the number of times per second a consistent read was requested for a block.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Consistent Read Gets Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Consistent Read Gets Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "DB Block Changes (blocks)",
     "type": "timeseries",
     "description": "This metric represents the total number of changes per second that were part of an update or delete operation that were made to all blocks in the SGA.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"DB Block Changes Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"DB Block Changes Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "CR Blocks Created (blocks)",
     "type": "timeseries",
     "description": "This metric represents the number of current blocks per second cloned to create consistent read (CR) blocks.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"CR Blocks Created Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"CR Blocks Created Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "CR Undo Records Applied (records)",
     "type": "timeseries",
     "description": "This metric represents the number of undo records applied for consistent read per second.",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"CR Undo Records Applied Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"CR Undo Records Applied Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  },
  {
   "title": "Phyical I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Physical Reads (bytes) ",
     "type": "timeseries",
     "description": "This metric represents bytes of data read from disk per second.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Read Bytes Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Read Bytes Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Physical Read IO Requests",
     "type": "timeseries",
     "description": "This metric represents the total rate of I/O read requests for the database.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Read IO Requests Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Read IO Requests Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Physical Reads (blocks)",
     "type": "timeseries",
     "description": "This metric represents the number of data blocks read from disk per second.\nWhen a user performs a SQL query, Oracle tries to retrieve the data from the database buffer cache (memory) first, then searches the disk if it is not already in memory.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Reads Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Reads Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Physical Reads Direct (blocks)",
     "type": "timeseries",
     "description": "This metric represents the number of direct physical reads per second",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Reads Direct Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Reads Direct Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Physical Reads Direct Lobs (blocks)",
     "type": "timeseries",
     "description": "This metric represents the number of direct large object (LOB) physical reads per second.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Reads Direct Lobs Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Reads Direct Lobs Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Physical Writes (bytes)",
     "type": "timeseries",
     "description": "This statistic represents database bytes written to SGA buffers cached to disk by the DBWR background process and PGA by processes performing direct writes.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Write Bytes Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Write Bytes Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Physical Write IO Requests",
     "type": "timeseries",
     "description": "This metric represents the total rate of I/O write requests for the database.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Write IO Requests Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Write IO Requests Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Physical Writes (blocks)",
     "type": "timeseries",
     "description": "This metric represents the number of disk writes per second. \nThis statistic represents the rate of database blocks written from the SGA buffer cached to disk by the DBWR background process, and from the PGA by processes performing direct writes.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Writes Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Writes Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Physical Writes Direct (blocks)",
     "type": "timeseries",
     "description": "This metric represents the number of direct physical writes per second.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Writes Direct Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Writes Direct Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Physical Writes Direct Lobs (blocks)",
     "type": "timeseries",
     "description": "This metric represents the number of direct large object (LOB) physical writes per second.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Writes Direct Lobs Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Writes Direct Lobs Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  },
  {
   "title": "Tablespace Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tablespace Size - Data Growth ( ~ 7 days )",
     "type": "table",
     "description": "Tablespace Size",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\"}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=~\"PERMANENT\"}[24h])) without(__name__)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\"}[24h])) without(__name__) - on (job, alias, tablespace_name )\r\n sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\"}[24h])) without(__name__)\r\n) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=~\"PERMANENT\"}[24h])) without(__name__)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\"}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=~\"PERMANENT\"}[24h])) without(__name__)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_tablespace_usage_used_percent{alias=~\"$alias\"}[24h])) without(__name__)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=~\"PERMANENT\"}[24h])) without(__name__)",
       "legendFormat": "__auto"
      },
      {
       "expr": "( sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\"}[24h])) without(__name__) - on (job, alias, tablespace_name )\r\n  sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\"}[24h] offset 7d)) without(__name__))\r\n* on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents=~\"PERMANENT\"}[24h])) without(__name__)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Temporary, Undo Tablespace Size",
     "type": "table",
     "description": "Tablespace Size",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\"}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents!~\"PERMANENT\"}[24h])) without(__name__)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum(last_over_time(oracledb_tablespace_usage_tablespace_size{alias=~\"$alias\"}[24h])) without(__name__) - on (job, alias, tablespace_name )\r\n sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\"}[24h])) without(__name__)\r\n) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents!~\"PERMANENT\"}[24h])) without(__name__)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_tablespace_usage_used_space{alias=~\"$alias\"}[24h])) without(__name__) * on (job, alias, tablespace_name )\r\nsum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents!~\"PERMANENT\"}[24h])) without(__name__)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_tablespace_usage_used_percent{alias=~\"$alias\"}[24h])) without(__name__)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(oracledb_tablespace_block_size{alias=~\"$alias\", contents!~\"PERMANENT\"}[24h])) without(__name__)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Top Tables / Indexes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Waited Tables",
     "type": "table",
     "description": "This panel displays the most frequently waited tables and indexes based on data from Oracle Session samples.\nIt helps identify which database objects contribute the most to wait events, providing insights for performance tuning and optimization. Use this panel to monitor and analyze potential bottlenecks related to specific tables and indexes",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(oracledb_ora_wait_sess_value{alias=~\"$alias\", wait_info=~\".*\\\\[T\\\\].*|.*\\\\[P\\\\].*\"}) by (wait_info)",
       "legendFormat": "__auto"
      },
      {
       "expr": "count(oracledb_ora_wait_sess_value{alias=~\"$alias\", wait_info=~\".*\\\\[T\\\\].*|.*\\\\[P\\\\].*\"} offset $diff_intv) by (wait_info)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top Waited Indexes",
     "type": "table",
     "description": "This panel displays the most frequently waited tables and indexes based on data from Oracle Session samples.\nIt helps identify which database objects contribute the most to wait events, providing insights for performance tuning and optimization. Use this panel to monitor and analyze potential bottlenecks related to specific tables and indexes",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(oracledb_ora_wait_sess_value{alias=~\"$alias\", wait_info=~\".*\\\\[I\\\\].*\"}) by (wait_info)",
       "legendFormat": "__auto"
      },
      {
       "expr": "count(oracledb_ora_wait_sess_value{alias=~\"$alias\", wait_info=~\".*\\\\[I\\\\].*\"} offset $diff_intv) by (wait_info)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Long Table Scans",
     "type": "timeseries",
     "description": "This metric represents the number of long table scans per second during sample period. \nA table is considered 'long' if the table is not cached and if its high-water mark is greater than 5 blocks.",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Long Table Scans Per Sec\"}[$intv])\r\n",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Long Table Scans Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Total Table Scans",
     "type": "timeseries",
     "description": "This metric represents the number of long and short table scans per second during the sample period. \nA table is considered 'long' if the table is not cached and if its high-water mark is greater than 5 blocks.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Total Table Scans Per Sec\"}[$intv])\r\n",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Total Table Scans Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Full Index Scans",
     "type": "timeseries",
     "description": "This metric represents the number of fast full index scans per second.",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Full Index Scans Per Sec\"}[$intv])\r\n",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Full Index Scans Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Total Index Scans",
     "type": "timeseries",
     "description": "This metric represents the total number of index scans per second.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Total Index Scans Per Sec\"}[$intv])\r\n",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Total Index Scans Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  },
  {
   "title": "Hit Ratio",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffer Cache Hit (%)",
     "type": "timeseries",
     "description": "- This metric represents the data block buffer cache efficiency, as measured by the percentage of times the data block requested by the query is in memory.\n- Effective use of the buffer cache can greatly reduce the I/O load on the database. If the buffer cache is too small, frequently accessed data will be flushed from the buffer cache too quickly which forces the information to be re-fetched from disk. Since disk access is much slower than memory access, application performance will suffer. In addition, the extra burden imposed on the I/O subsystem could introduce a bottleneck at one or more devices that would further degrade performance.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Buffer Cache Hit Ratio\"}[$intv])\r\n",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Buffer Cache Hit Ratio\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Library Cache Hit (%)",
     "type": "timeseries",
     "description": "This metric represents the library cache efficiency, as measured by the percentage of times the fully parsed or compiled representation of PL/SQL blocks and SQL statements are already in memory.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Library Cache Hit Ratio\"}[$intv])\r\n",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Library Cache Hit Ratio\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Row Cache Hit (%)",
     "type": "timeseries",
     "description": "This metric represents row  cache efficiency as measured by the percentage of requests against the data that were already in memory",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Row Cache Hit Ratio\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Row Cache Hit Ratio\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "PGA Cache Hit (%)",
     "type": "timeseries",
     "description": "This metric represents the total number of bytes processed in the PGA versus the total number of bytes processed plus extra bytes read/written in extra passes.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"PGA Cache Hit %\"}[$intv])\r\n",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"PGA Cache Hit %\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Memory Sorts (%)",
     "type": "timeseries",
     "description": "This metric represents the sort efficiency as measured by the percentage of times sorts were performed in memory as opposed to going to disk.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Memory Sorts Ratio\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Memory Sorts Ratio\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Soft Parse (%)",
     "type": "timeseries",
     "description": "This metric represents the percentage of parse requests where the cursor was already in the cursor cache compared to the number of total parses.",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Soft Parse Ratio\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Soft Parse Ratio\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  },
  {
   "title": "User Call, Executions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Logons Count",
     "type": "timeseries",
     "description": "This metric represents the current number of logons.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Current Logons Count\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Current Logons Count\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Logons Per Sec",
     "type": "timeseries",
     "description": "This metric represents the current number of logons.\nIt indicates how often new sessions are being created in the database.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Logons Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Logons Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Active Sessions",
     "type": "timeseries",
     "description": "Host user% + sys%",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_sessions_value{alias=~\"$alias\",status=\"ACTIVE\",type='USER'}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_sessions_value{alias=~\"$alias\",status=\"ACTIVE\",type='USER'}[$intv] offset $diff_intv) \r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "User Calls",
     "type": "timeseries",
     "description": "This metric represents the number of logins, parses, or execute calls per second during the sample period.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"User Calls Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"User Calls Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Executions",
     "type": "timeseries",
     "description": "This metric represents the rate of SQL command executions per second.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Executions Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Executions Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Recursive Calls",
     "type": "timeseries",
     "description": "Sometimes, to execute a SQL statement issued by a user, the Oracle Server must issue additional statements. Such statements are called recursive calls or recursive SQL statements.\nFor example,\n- When data dictionary information is not available in the data dictionary cache and must be retrieved from disk\n- In the firing of database triggers\n- In the execution of DDL statements\n- In the execution of SQL statements within stored procedures, functions, packages and anonymous PL/SQL blocks\n- In the enforcement of referential integrity constraints",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Recursive Calls Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"User Calls Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Total Parse Count",
     "type": "timeseries",
     "description": "The total number of parses per second, both hard and soft. \nA hard parse occurs when a SQL statement has to be loaded into the shared pool. \nIn this case, the Oracle Server has to allocate memory in the shared pool and parse the statement. \nA soft parse is recorded when the Oracle Server checks the shared pool for a SQL statement and finds a version of the statement that it can reuse.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Total Parse Count Per Sec\"}[$intv])\r\n",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Total Parse Count Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Hard Parse Count",
     "type": "timeseries",
     "description": "A hard parse occurs when a SQL statement has to be loaded into the shared pool. \nIn this case, the Oracle Server has to allocate memory in the shared pool and parse the statement. \nA soft parse is recorded when the Oracle Server checks the shared pool for a SQL statement and finds a version of the statement that it can reuse.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Hard Parse Count Per Sec\"}[$intv])\r\n",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Hard Parse Count Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Parse Failure Count",
     "type": "timeseries",
     "description": "This metric represents the total number of parse failures per second.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Parse Failure Count Per Sec\"}[$intv])\r\n",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Parse Failure Count Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Soft Parse (%)",
     "type": "timeseries",
     "description": "This metric represents the percentage of parse requests where the cursor was already in the cursor cache compared to the number of total parses.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Soft Parse Ratio\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Soft Parse Ratio\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "User Commits",
     "type": "timeseries",
     "description": "This metric represents the number of user commits performed, per second during the sample period. \nWhen a user commits a transaction, the redo generated that reflects the changes made to database blocks must be written to disk. \nCommits often represent the closest thing to a user transaction rate.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"User Commits Per Sec\"}[$intv])\r\n",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"User Commits Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "User Rollbacks",
     "type": "timeseries",
     "description": "This metric represents the number of times, per second during the sample period, that users manually issue the ROLLBACK statement or an error occurred during a user's transactions.",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"User Rollbacks Per Sec\"}[$intv])\r\n",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"User Rollbacks Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  },
  {
   "title": "RAC Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Wait Events Time(s)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=~\"gc.*\"}[$intv])) by (alias,name) / 1000000) > 0.0001",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "GC Wait Events ( Diff : $diff_intv )",
     "type": "timeseries",
     "description": "DB Time = CPU Time + Wait Time ",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(topk(10, sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=~\"gc.*\"}[$intv] offset $diff_intv)) by (alias,name) / 1000000) > 0.0001)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "gc% event sum  - Avg W_tm(ms)",
     "type": "timeseries",
     "description": "- gc cr request\n- gc current block busy\n- gc ...",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=~\"gc.*\"}[$intv])) by (alias) /\r\nsum(rate(oracledb_ora_system_event_total_waits{alias=~\"$alias\", name=~\"gc.*\"}[$intv])) by (alias) / 1000",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\", name=~\"gc.*\"}[$intv] offset $diff_intv)) by (alias) /\r\nsum(rate(oracledb_ora_system_event_total_waits{alias=~\"$alias\", name=~\"gc.*\"}[$intv] offset $diff_intv)) by (alias) / 1000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "GC Blocks Lost",
     "type": "timeseries",
     "description": "This metric represents the number of global cache blocks lost over the user-defined observation period.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Global Cache Blocks Lost\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Global Cache Blocks Lost\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "GC Blocks Corrupted\"",
     "type": "timeseries",
     "description": "This metric represents the number of blocks that encountered a corruption or checksum failure during interconnect over the user-defined observation period.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Global Cache Blocks Corrupted\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Global Cache Blocks Corrupted\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "GC CR Received (blocks)",
     "type": "timeseries",
     "description": "the global cache consistent read blocks received.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"GC CR Block Received Per Second\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"GC CR Block Received Per Second\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "GC CR Get Time (ms)",
     "type": "timeseries",
     "description": "This metric represents the average get time.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Global Cache Average CR Get Time\"}[$intv]) * 10",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Global Cache Average CR Get Time\"}[$intv] offset $diff_intv) * 10\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "GC Current Received (blocks)",
     "type": "timeseries",
     "description": "the global cache current read blocks received.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"GC Current Block Received Per Second\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"GC Current Block Received Per Second\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "GC Current Get Time (ms)",
     "type": "timeseries",
     "description": "This metric represents the average get time.",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Global Cache Average Current Get Time\"}[$intv]) * 10",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Global Cache Average Current Get Time\"}[$intv] offset $diff_intv) * 10\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  }
 ]
}