{
 "title": "Oracle SQLs",
 "description": "Oracle SQLs (2024-08-26)",
 "tags": [
  "CI-TEC",
  "Oracle",
  "SQL"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": { "query": "label_values(oracledb_up,job)" } },
   {
    "name": "alias",
    "label": "alias",
    "query": {
     "query": "label_values(oracledb_up{job=~\"$group\"},alias)"
    }
   },
   {
    "name": "intv",
    "label": "interval",
    "query": "10s, 30s, 1m, 5m, 30m, 1h, 6h, 12h"
   },
   { "name": "filter", "label": "SQL Text Filter" },
   { "name": "sql_id", "label": "sql_id Filter (Min 5 chars.)" },
   { "name": "use_diff", "label": "Comparison", "query": "On : 1, Off : 0" },
   { "name": "diff_intv", "label": "Comp. Period", "query": "1d" }
  ]
 },
 "panels": [
  {
   "title": "Total - SQL Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_elapsed_time_total{alias=~\"$alias\"}[$intv])/1000) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_elapsed_time_total{alias=~\"$alias\"}[$intv] offset $diff_intv)/1000) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Total - CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_cpu_time_total{alias=~\"$alias\"}[$intv])/1000) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_cpu_time_total{alias=~\"$alias\"}[$intv] offset $diff_intv)/1000) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Total - Executions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_executions_total{alias=~\"$alias\"}[$intv])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_executions_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Total - Buffer Gets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_buffer_gets_total{alias=~\"$alias\"}[$intv])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_buffer_gets_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Total - Direct Reads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_disk_reads_total{alias=~\"$alias\"}[$intv])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_disk_reads_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Total - Direct Writes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_direct_writes_total{alias=~\"$alias\"}[$intv])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(oracledb_ora_top_cpu_sqls_direct_writes_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  { "title": "Top SQLs Comparison", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "table",
   "description": "Top SQLs ordered by Elapsed Time",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_elapsed_time_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range])/1000\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_cpu_time_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range])/1000\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_executions_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_buffer_gets_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_disk_reads_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_elapsed_time_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range] offset $diff_intv)/1000\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_cpu_time_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range] offset $diff_intv)/1000\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_executions_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_buffer_gets_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,   \r\n   increase(oracledb_ora_top_cpu_sqls_disk_reads_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top SQLs per executions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Top SQLs ordered by Elapsed Time",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_elapsed_time_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range])/1000\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_cpu_time_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range])/1000\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_executions_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range])\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_buffer_gets_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range])\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_disk_reads_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range])\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_elapsed_time_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range] offset $diff_intv)/1000\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_cpu_time_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range] offset $diff_intv)/1000\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_executions_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(1000,\r\n   increase(oracledb_ora_top_cpu_sqls_buffer_gets_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(1000,   \r\n   increase(oracledb_ora_top_cpu_sqls_disk_reads_total{alias=~\"$alias\", sql_text=~\"(?s)(?i).*$filter.*\", sql_id=~\"$sql_id.*\"}[$__range] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}