{
 "title": "Oracle Overview",
 "description": "Oracle SQLs (2024-08-26)",
 "tags": [
  "CI-TEC",
  "Oracle",
  "Main"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": { "query": "label_values(oracledb_up,job)" } },
   {
    "name": "alias",
    "label": "alias",
    "query": {
     "query": "label_values(oracledb_up{job=~\"$group\"},alias)"
    }
   },
   { "name": "intv", "label": "interval", "query": "30s, 1m, 5m, 30m, 1h, 6h, 12h" },
   { "name": "use_diff", "label": "Comparison", "query": "On : 1, Off : 0" },
   { "name": "diff_intv", "label": "Comp. Period", "query": "1d" }
  ]
 },
 "panels": [
  { "title": "DB & Exporter State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(oracledb_up{}) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(up + (oracledb_up - oracledb_up)) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_duration_seconds + (oracledb_up - oracledb_up)) by (alias, instance, job) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(oracledb_ora_startup_time_minutes + (oracledb_up - oracledb_up)) by (alias, instance, job) * 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_samples_scraped + (oracledb_up - oracledb_up)) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(oracledb_ora_metric_value{metric_name=\"Database Time Per Sec\"}[$__range]) / 100) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(oracledb_ora_metric_value{metric_name=\"Database Time Per Sec\"}[$__range] offset $diff_intv) / 100) by (alias, instance, job)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(oracledb_ora_metric_value{metric_name=\"Host CPU Utilization (%)\"}[$__range]) / 100) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(oracledb_ora_metric_value{metric_name=\"Host CPU Utilization (%)\"}[$__range] offset $diff_intv) / 100) by (alias, instance, job)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "ceil(avg_over_time(oracledb_ora_metric_value{metric_name=\"Host CPU Usage Per Sec\"}[$__range]) / ignoring(metric_name) \r\n     avg_over_time(oracledb_ora_metric_value{metric_name=\"Host CPU Utilization (%)\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(oracledb_ora_memstat_value{stat_name=\"PHYSICAL_MEMORY_BYTES\"}[$__range])) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(last_over_time(oracledb_instance{}[24h])) by (alias, instance, job, version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$alias",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "alias",
   "collapsed": true,
   "panels": [
    {
     "title": "State",
     "type": "stat",
     "description": "- The total wait time of the summarized events that are timed.\n- = Active session",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count({__name__=~\".+\",alias=~\"$alias\"}) by (alias, instance, job)",
       "legendFormat": "DB State"
      },
      {
       "expr": "oracledb_ora_startup_time_minutes{alias=~\"$alias\"}*60",
       "legendFormat": "Uptime"
      }
     ]
    },
    {
     "title": "OS CPU (%)",
     "type": "timeseries",
     "description": "Host user% + sys%",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Utilization (%)\"}[$intv]) ",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Utilization (%)\"}[$intv] offset $diff_intv) \r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "OS Active Mem(%)",
     "type": "timeseries",
     "description": "= (Physical Memory - Inactive Memory) / Physical Memory",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "(oracledb_ora_memstat_value{alias=~\"$alias\",stat_name=\"PHYSICAL_MEMORY_BYTES\"} - ignoring(stat_name)\r\n oracledb_ora_memstat_value{alias=~\"$alias\",stat_name=\"INACTIVE_MEMORY_BYTES\"}) / ignoring(stat_name)\r\noracledb_ora_memstat_value{alias=~\"$alias\",stat_name=\"PHYSICAL_MEMORY_BYTES\"} * 100",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(oracledb_ora_memstat_value{alias=~\"$alias\",stat_name=\"PHYSICAL_MEMORY_BYTES\"} offset $diff_intv - ignoring(stat_name)\r\n oracledb_ora_memstat_value{alias=~\"$alias\",stat_name=\"INACTIVE_MEMORY_BYTES\"} offset $diff_intv) / ignoring(stat_name)\r\noracledb_ora_memstat_value{alias=~\"$alias\",stat_name=\"PHYSICAL_MEMORY_BYTES\"}  offset $diff_intv * 100\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "DB CPU (%)",
     "type": "timeseries",
     "description": "Oracle user% + sys%",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"CPU Usage Per Sec\"}[$intv]) / ignoring(metric_name) \r\n(\r\navg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Usage Per Sec\"}[$intv]) / ignoring(metric_name) \r\navg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Utilization (%)\"}[$intv])\r\n)",
       "legendFormat": "{{alias}}:"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"CPU Usage Per Sec\"}[$intv] offset $diff_intv) / ignoring(metric_name) \r\n(\r\navg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Usage Per Sec\"}[$intv] offset $diff_intv) / ignoring(metric_name) \r\navg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Host CPU Utilization (%)\"}[$intv] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "DB Time (s)",
     "type": "timeseries",
     "description": "DB Time = CPU Time + Wait Time ",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Database Time Per Sec\"}[$intv]) /100",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\",metric_name=\"Database Time Per Sec\"}[$intv] offset $diff_intv) /100\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Wait Time (s)",
     "type": "timeseries",
     "description": "DB Time = CPU Time + Wait Time ",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\"}[$intv])) by (alias) / 1000000",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(rate(oracledb_ora_system_event_time_waited_micro{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias) / 1000000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "SQL Time (s)",
     "type": "timeseries",
     "description": "Sum of all SQL execution times per second ",
     "gridPos": { "h": 4, "w": 2, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(oracledb_ora_top_cpu_sqls_elapsed_time_total{alias=~\"$alias\"}[$intv])/1000) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(rate(oracledb_ora_top_cpu_sqls_elapsed_time_total{alias=~\"$alias\"}[$intv] offset $diff_intv)/1000) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "SQL Exec.",
     "type": "timeseries",
     "description": "Sum of all SQL execution times per second ",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(oracledb_ora_top_cpu_sqls_executions_total{alias=~\"$alias\"}[$intv])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(rate(oracledb_ora_top_cpu_sqls_executions_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "L Reads (blks)",
     "type": "timeseries",
     "description": "Logical Reads  = DB Block Gets + Consistent Read Gets\nThis metric represents the number of logical reads per second.\nA logical read is a read request for a data block from the SGA. \nLogical reads may result in a physical read if the requested block does not reside with the buffer cache.",
     "gridPos": { "h": 4, "w": 2, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Logical Reads Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Logical Reads Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "P Reads (blks)",
     "type": "timeseries",
     "description": "This metric represents the number of data blocks read from disk per second.\nWhen a user performs a SQL query, Oracle tries to retrieve the data from the database buffer cache (memory) first, then searches the disk if it is not already in memory.",
     "gridPos": { "h": 4, "w": 2, "x": 18, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Reads Per Sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(oracledb_ora_metric_value{alias=~\"$alias\", metric_name=\"Physical Reads Per Sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "IO avg read (ms)",
     "type": "timeseries",
     "description": "Tablespace average read time\n= readtim_ms / phyrds",
     "gridPos": { "h": 4, "w": 2, "x": 20, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(oracledb_ora_tablespace_stat_readtim_ms{alias=~\"$alias\" }[$intv])) by (alias) /\r\nsum(rate(oracledb_ora_tablespace_stat_phyrds{alias=~\"$alias\" }[$intv])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(rate(oracledb_ora_tablespace_stat_readtim_ms{alias=~\"$alias\" }[$intv] offset $diff_intv)) by (alias) /\r\nsum(rate(oracledb_ora_tablespace_stat_phyrds{alias=~\"$alias\" }[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "IO avg write (ms)",
     "type": "timeseries",
     "description": "Tablespace average write time\n= writetim_ms / phywrts",
     "gridPos": { "h": 4, "w": 2, "x": 22, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(oracledb_ora_tablespace_stat_writetim_ms{alias=~\"$alias\" }[$intv])) by (alias) /\r\nsum(rate(oracledb_ora_tablespace_stat_phywrts{alias=~\"$alias\" }[$intv])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(rate(oracledb_ora_tablespace_stat_writetim_ms{alias=~\"$alias\" }[$intv] offset $diff_intv)) by (alias) /\r\nsum(rate(oracledb_ora_tablespace_stat_phywrts{alias=~\"$alias\" }[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  }
 ]
}