{
 "title": "PostgreSQL SQLs",
 "description": "PostgreSQL SQL (2024-08-26)",
 "tags": [
  "CI-TEC",
  "PostgreSQL",
  "SQL"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": { "query": "label_values(pg_up,job)" } },
   {
    "name": "alias",
    "label": "Instance",
    "query": {
     "query": "label_values(pg_up{job=~\"$group\"},alias)"
    }
   },
   {
    "name": "intv",
    "label": "Interval",
    "query": "10s, 30s, 1m, 5m, 30m, 1h, 6h, 12h"
   },
   { "name": "filter", "label": "Top SQLs Filter" },
   {
    "name": "query_id",
    "label": "SQL Detail query_id (Min 5 chars.)",
    "query": "input query_id"
   },
   { "name": "use_diff", "label": "Comparison", "query": "On : 1, Off : 0" },
   { "name": "diff_intv", "label": "Comp. Period", "query": "1d" }
  ]
 },
 "panels": [
  {
   "title": "Total - SQL Time",
   "type": "timeseries",
   "description": "Total time spent in the statement.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_topsql_seconds_total{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_seconds_total{alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_topsql_seconds_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_seconds_total{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Total - Executions",
   "type": "timeseries",
   "description": "Number of times executed, in seconds",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_topsql_calls_total{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_calls_total{alias=~\"$alias\"}[5m])) by (alias)\r\n\r\n",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_topsql_calls_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_calls_total{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Rows  retrieved or affected",
   "type": "timeseries",
   "description": "Total number of rows retrieved or affected by the statement",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_topsql_rows_total{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_rows_total{alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_topsql_rows_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_rows_total{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Total - SQL block_read Time",
   "type": "timeseries",
   "description": "Total time spent reading blocks.",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_topsql_block_read_seconds_total{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_block_read_seconds_total{alias=~\"$alias\"}[5m])) by (alias)\r\n\r\n",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_topsql_block_read_seconds_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_block_read_seconds_total{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Total - SQL block_write Time",
   "type": "timeseries",
   "description": "Total time spent writing blocks.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_topsql_block_write_seconds_total{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_block_write_seconds_total{alias=~\"$alias\"}[5m])) by (alias)\r\n\r\n",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_topsql_block_write_seconds_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_block_write_seconds_total{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  { "title": "Top SQLs Comparison", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "table",
   "description": "Top SQL ordered by Elapsed Time",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(200, \r\n     sum ((pg_stat_topsql_seconds_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} -\r\n           pg_stat_topsql_seconds_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} offset $__range)\r\n          or pg_stat_topsql_seconds_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"})\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n    ) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200, \r\n     sum ((pg_stat_topsql_calls_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} -\r\n           pg_stat_topsql_calls_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} offset $__range)\r\n          or pg_stat_topsql_calls_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"})\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n    ) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200, \r\n     sum ((pg_stat_topsql_rows_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} -\r\n           pg_stat_topsql_rows_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} offset $__range)\r\n          or pg_stat_topsql_rows_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"})\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n    ) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200,(\r\n   sum(max_over_time(pg_stat_topsql_seconds_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"}[$__range] offset $diff_intv) -\r\n       min_over_time(pg_stat_topsql_seconds_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"}[$__range] offset $diff_intv))\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200,(\r\n   sum(max_over_time(pg_stat_topsql_calls_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"}[$__range] offset $diff_intv) -\r\n       min_over_time(pg_stat_topsql_calls_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"}[$__range] offset $diff_intv))\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200,(\r\n   sum(max_over_time(pg_stat_topsql_rows_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"}[$__range] offset $diff_intv) -\r\n       min_over_time(pg_stat_topsql_rows_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"}[$__range] offset $diff_intv))\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Top SQLs per executions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "table",
   "description": "Top SQL ordered by Elapsed Time",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(200, \r\n     sum ((pg_stat_topsql_seconds_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} -\r\n           pg_stat_topsql_seconds_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} offset $__range)\r\n          or pg_stat_topsql_seconds_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"})\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n    ) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200, \r\n     sum ((pg_stat_topsql_calls_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} -\r\n           pg_stat_topsql_calls_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} offset $__range)\r\n          or pg_stat_topsql_calls_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"})\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n    ) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200, \r\n     sum ((pg_stat_topsql_rows_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} -\r\n           pg_stat_topsql_rows_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} offset $__range)\r\n          or pg_stat_topsql_rows_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"})\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n    ) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200,(\r\n   sum(max_over_time(pg_stat_topsql_seconds_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"}[$__range] offset $diff_intv) -\r\n       min_over_time(pg_stat_topsql_seconds_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"}[$__range] offset $diff_intv))\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200,(\r\n   sum(max_over_time(pg_stat_topsql_calls_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"}[$__range] offset $diff_intv) -\r\n       min_over_time(pg_stat_topsql_calls_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"}[$__range] offset $diff_intv))\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200,(\r\n   sum(max_over_time(pg_stat_topsql_rows_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"}[$__range] offset $diff_intv) -\r\n       min_over_time(pg_stat_topsql_rows_total{sql_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"}[$__range] offset $diff_intv))\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Selected SQLs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pg_stat_topsql_seconds_total{alias=\"$alias\", queryid=~\"$query_id.*\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SQL Time",
     "type": "timeseries",
     "description": "Total time spent in the statement.",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_topsql_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv])) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m])) by (queryid)",
       "legendFormat": "{{queryid}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_topsql_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv] offset $diff_intv)) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m] offset $diff_intv)) by (queryid)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{queryid}}:diff"
      }
     ]
    },
    {
     "title": "Executions",
     "type": "timeseries",
     "description": "Number of times executed, in seconds",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_topsql_calls_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv])) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_calls_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m])) by (queryid)",
       "legendFormat": "{{queryid}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_topsql_calls_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv] offset $diff_intv)) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_calls_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m] offset $diff_intv)) by (queryid)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{queryid}}:diff"
      }
     ]
    },
    {
     "title": "Rows  retrieved or affected",
     "type": "timeseries",
     "description": "Total number of rows retrieved or affected by the statement",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_topsql_rows_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv])) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_rows_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m])) by (queryid)",
       "legendFormat": "{{queryid}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_topsql_rows_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv] offset $diff_intv)) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_rows_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m] offset $diff_intv)) by (queryid)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{queryid}}:diff"
      }
     ]
    },
    {
     "title": "SQL block_read Time",
     "type": "timeseries",
     "description": "Total time spent reading blocks.",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_topsql_block_read_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv])) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_block_read_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m])) by (queryid)",
       "legendFormat": "{{queryid}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_topsql_block_read_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv] offset $diff_intv)) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_block_read_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m] offset $diff_intv)) by (queryid)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{queryid}}:diff"
      }
     ]
    },
    {
     "title": "SQL block_write Time",
     "type": "timeseries",
     "description": "Total time spent writing blocks.",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_topsql_block_write_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv])) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_block_write_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m])) by (queryid)",
       "legendFormat": "{{queryid}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_topsql_block_write_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv] offset $diff_intv)) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_block_write_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m] offset $diff_intv)) by (queryid)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{queryid}}:diff"
      }
     ]
    }
   ]
  }
 ]
}