{
 "title": "PostgreSQL SQL Details",
 "description": "PostgreSQL SQL Details (2024-09-11)",
 "time": { "from": "2024-09-09T10:09:18.656Z", "to": "2024-09-09T16:40:03.882Z" },
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": { "query": "label_values(pg_up,job)" } },
   {
    "name": "alias",
    "label": "Instance",
    "query": {
     "query": "label_values(pg_up{job=~\"$group\"},alias)"
    }
   },
   {
    "name": "intv",
    "label": "Interval",
    "query": "10s, 30s, 1m, 5m, 30m, 1h, 6h, 12h"
   },
   { "name": "use_diff", "label": "Comparison", "query": "On : 1, Off : 0" },
   { "name": "diff_intv", "label": "Comp. Period", "query": "1d" },
   { "name": "query_id", "label": "query_id" },
   { "name": "sql_text", "label": "sql_text" },
   { "name": "dbname", "label": "dbname" },
   { "name": "user", "label": "user" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "query_id : $query_id<br>\r\nuser : $user<br>\r\ndbname : $dbname<br>\r\n${sql_text}<br>\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n<br>\r\n<br>\r\n  Retrieval time\r\n</div>"
   }
  },
  {
   "type": "table",
   "description": "Top SQL ordered by Elapsed Time",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(3, \r\n     sum ((pg_stat_topsql_seconds_total{queryid=\"$query_id\", alias=\"$alias\"} -\r\n           pg_stat_topsql_seconds_total{queryid=\"$query_id\", alias=\"$alias\"} offset $__range)\r\n          or pg_stat_topsql_seconds_total{queryid=\"$query_id\", alias=\"$alias\"})\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n    ) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(3, \r\n     sum ((pg_stat_topsql_calls_total{queryid=\"$query_id\", alias=\"$alias\"} -\r\n           pg_stat_topsql_calls_total{queryid=\"$query_id\", alias=\"$alias\"} offset $__range)\r\n          or pg_stat_topsql_calls_total{queryid=\"$query_id\", alias=\"$alias\"})\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n    ) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(3, \r\n     sum ((pg_stat_topsql_rows_total{queryid=\"$query_id\", alias=\"$alias\"} -\r\n           pg_stat_topsql_rows_total{queryid=\"$query_id\", alias=\"$alias\"} offset $__range)\r\n          or pg_stat_topsql_rows_total{queryid=\"$query_id\", alias=\"$alias\"})\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n    ) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\nDiff : -${diff_intv}\r\n</div>\r\n"
   }
  },
  {
   "type": "table",
   "description": "Top SQL ordered by Elapsed Time",
   "gridPos": { "h": 2, "w": 20, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(3,(\r\n   sum(max_over_time(pg_stat_topsql_seconds_total{queryid=\"$query_id\", alias=\"$alias\"}[$__range] offset $diff_intv) -\r\n       min_over_time(pg_stat_topsql_seconds_total{queryid=\"$query_id\", alias=\"$alias\"}[$__range] offset $diff_intv))\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(3,(\r\n   sum(max_over_time(pg_stat_topsql_calls_total{queryid=\"$query_id\", alias=\"$alias\"}[$__range] offset $diff_intv) -\r\n       min_over_time(pg_stat_topsql_calls_total{queryid=\"$query_id\", alias=\"$alias\"}[$__range] offset $diff_intv))\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(3,(\r\n   sum(max_over_time(pg_stat_topsql_rows_total{queryid=\"$query_id\", alias=\"$alias\"}[$__range] offset $diff_intv) -\r\n       min_over_time(pg_stat_topsql_rows_total{queryid=\"$query_id\", alias=\"$alias\"}[$__range] offset $diff_intv))\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQL Time",
   "type": "timeseries",
   "description": "Total time spent in the statement.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_topsql_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv])) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m])) by (queryid)",
     "legendFormat": "{{queryid}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_topsql_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv] offset $diff_intv)) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m] offset $diff_intv)) by (queryid)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{queryid}}:diff"
    }
   ]
  },
  {
   "title": "Executions",
   "type": "timeseries",
   "description": "Number of times executed, in seconds",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_topsql_calls_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv])) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_calls_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m])) by (queryid)",
     "legendFormat": "{{queryid}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_topsql_calls_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv] offset $diff_intv)) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_calls_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m] offset $diff_intv)) by (queryid)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{queryid}}:diff"
    }
   ]
  },
  {
   "title": "Rows  retrieved or affected",
   "type": "timeseries",
   "description": "Total number of rows retrieved or affected by the statement",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_topsql_rows_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv])) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_rows_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m])) by (queryid)",
     "legendFormat": "{{queryid}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_topsql_rows_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv] offset $diff_intv)) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_rows_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m] offset $diff_intv)) by (queryid)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{queryid}}:diff"
    }
   ]
  },
  {
   "title": "SQL block_read Time",
   "type": "timeseries",
   "description": "Total time spent reading blocks.",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_topsql_block_read_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv])) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_block_read_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m])) by (queryid)",
     "legendFormat": "{{queryid}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_topsql_block_read_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv] offset $diff_intv)) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_block_read_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m] offset $diff_intv)) by (queryid)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{queryid}}:diff"
    }
   ]
  },
  {
   "title": "SQL block_write Time",
   "type": "timeseries",
   "description": "Total time spent writing blocks.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_topsql_block_write_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv])) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_block_write_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m])) by (queryid)",
     "legendFormat": "{{queryid}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_topsql_block_write_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[$intv] offset $diff_intv)) by (queryid)\r\nor\r\nsum(irate(pg_stat_topsql_block_write_seconds_total{alias=~\"$alias\", queryid=~\"$query_id.*\"}[5m] offset $diff_intv)) by (queryid)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{queryid}}:diff"
    }
   ]
  }
 ]
}