{
 "title": "PostgreSQL Monitor",
 "description": "PostgreSQL Performance (2024-08-11)",
 "tags": [
  "CI-TEC",
  "PostgreSQL",
  "Monitor"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": { "query": "label_values(pg_up,job)" } },
   {
    "name": "alias",
    "label": "Instance",
    "query": {
     "query": "label_values(pg_up{job=~\"$group\"},alias)"
    }
   },
   {
    "name": "intv",
    "label": "Interval",
    "query": "10s, 30s, 1m, 5m, 10m 30m 1h, 6h, 12h"
   },
   { "name": "use_diff", "label": "Comparison", "query": "On : 1, Off : 0" },
   { "name": "diff_intv", "label": "Comp. Period", "query": "1d" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SQL Time",
   "type": "timeseries",
   "description": "Total time spent in the statement, in seconds",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_topsql_seconds_total{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_seconds_total{alias=~\"$alias\"}[5m])) by (alias)\r\n\r\n",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_topsql_seconds_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_seconds_total{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "SQL Executions",
   "type": "timeseries",
   "description": "Number of times executed, in seconds",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_topsql_calls_total{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_calls_total{alias=~\"$alias\"}[5m])) by (alias)\r\n\r\n",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_topsql_calls_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_calls_total{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Active conn.",
   "type": "timeseries",
   "description": "Active connections in this state",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{alias=~\"$alias\",state=\"active\"}) by(alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\n    sum(pg_stat_activity_count{alias=~\"$alias\",state=\"active\"} offset $diff_intv) by(alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Connection count",
   "type": "timeseries",
   "description": "Number of connections",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{alias=~\"$alias\"}) by(alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\n(sum(pg_stat_activity_count{alias=~\"$alias\"} offset $diff_intv) by(alias) )\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "rows fetched ",
   "type": "timeseries",
   "description": "Number of rows fetched by queries in this database",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_tup_fetched{alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_database_tup_fetched{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_tup_fetched{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "blks_hit_ratio",
   "type": "timeseries",
   "description": "- It indicates the buffer cache hit rate.\n- = sum(blks_hit) / sum(blks_hit + blks_read)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(pg_stat_database_blks_hit{alias=~\"$alias\"}[$intv])) by (alias)) / \r\n( sum(rate(pg_stat_database_blks_hit{alias=~\"$alias\"}[$intv])) by (alias) + sum(rate(pg_stat_database_blks_read{alias=~\"$alias\"}[$intv])) by (alias) )",
     "legendFormat": "{{alias}}:{{datname}}"
    },
    {
     "expr": "(\r\n(sum(rate(pg_stat_database_blks_hit{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)) / \r\n( sum(rate(pg_stat_database_blks_hit{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias) + sum(rate(pg_stat_database_blks_read{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias) )\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:{{datname}}:diff"
    }
   ]
  },
  {
   "title": "blk_read_time",
   "type": "timeseries",
   "description": "Total time the statement spent reading data file blocks, in milliseconds (if track_io_timing is enabled, otherwise zero)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_blk_read_time{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_blk_read_time{alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_database_blk_read_time{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_blk_read_time{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
     "legendFormat": "{{alias}}:{{datname}}:diff"
    }
   ]
  },
  {
   "title": "commit_count",
   "type": "timeseries",
   "description": "Number of transactions in this database that have been committed",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_xact_commit{alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_database_xact_commit{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_xact_commit{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "deadlock_count",
   "type": "timeseries",
   "description": "Total number of deadlocks detected",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_deadlocks{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_deadlocks{alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_database_deadlocks{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_deadlocks{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "maxwritten_clean_total",
   "type": "timeseries",
   "description": "Number of times the background writer stopped a cleaning scan because it had written too many buffers",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_maxwritten_clean_total{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(pg_stat_bgwriter_maxwritten_clean_total{alias=~\"$alias\"}[5m])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nrate(pg_stat_bgwriter_maxwritten_clean_total{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(pg_stat_bgwriter_maxwritten_clean_total{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "conflicts",
   "type": "timeseries",
   "description": "Number of queries canceled due to conflicts with recovery in this database. (Conflicts occur only on standby servers; see pg_stat_database_conflicts for details.)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_conflicts{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_conflicts{alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_database_conflicts{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_conflicts{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "temp files created",
   "type": "timeseries",
   "description": "Number of temporary files created by queries in this database. All temporary files are counted, regardless of why the temporary file was created (e.g., sorting or hashing), and regardless of the log_temp_files setting.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_temp_files{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_temp_files{alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_database_temp_files{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_temp_files{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  { "title": "SQL Statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Top SQL ordered by Elapsed Time",
   "type": "table",
   "description": "Top SQL ordered by Elapsed Time",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(200, \r\n     sum ((pg_stat_topsql_seconds_total{alias=~\"$alias\"} -\r\n           pg_stat_topsql_seconds_total{alias=~\"$alias\"} offset $__range)\r\n          or pg_stat_topsql_seconds_total{alias=~\"$alias\"})\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n    ) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200, \r\n     sum ((pg_stat_topsql_calls_total{alias=~\"$alias\"} -\r\n           pg_stat_topsql_calls_total{alias=~\"$alias\"} offset $__range)\r\n          or pg_stat_topsql_calls_total{alias=~\"$alias\"})\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n    ) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200, \r\n     sum ((pg_stat_topsql_rows_total{alias=~\"$alias\"} -\r\n           pg_stat_topsql_rows_total{alias=~\"$alias\"} offset $__range)\r\n          or pg_stat_topsql_rows_total{alias=~\"$alias\"})\r\n    by (job, alias, instance, queryid, sql_text, datname, user) \r\n    ) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQL Time",
   "type": "timeseries",
   "description": "Total time spent in the statement.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_topsql_seconds_total{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_seconds_total{alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_topsql_seconds_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_seconds_total{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Executions",
   "type": "timeseries",
   "description": "Number of times executed, in seconds",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_topsql_calls_total{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_calls_total{alias=~\"$alias\"}[5m])) by (alias)\r\n\r\n",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_topsql_calls_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_calls_total{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Rows  retrieved or affected",
   "type": "timeseries",
   "description": "Total number of rows retrieved or affected by the statement",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_topsql_rows_total{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_rows_total{alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_topsql_rows_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_rows_total{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "SQL block_read Time",
   "type": "timeseries",
   "description": "Total time spent reading blocks.",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_topsql_block_read_seconds_total{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_block_read_seconds_total{alias=~\"$alias\"}[5m])) by (alias)\r\n\r\n",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_topsql_block_read_seconds_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_block_read_seconds_total{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "SQL block_write Time",
   "type": "timeseries",
   "description": "Total time spent writing blocks.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_topsql_block_write_seconds_total{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_block_write_seconds_total{alias=~\"$alias\"}[5m])) by (alias)\r\n\r\n",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_topsql_block_write_seconds_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_block_write_seconds_total{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection count",
     "type": "timeseries",
     "description": "Number of connections",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{alias=~\"$alias\"}) by(alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\n(sum(pg_stat_activity_count{alias=~\"$alias\"} offset $diff_intv) by(alias) )\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Active conn.",
     "type": "timeseries",
     "description": "Active connections in this state",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{alias=~\"$alias\",state=\"active\"}) by(alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\n    sum(pg_stat_activity_count{alias=~\"$alias\",state=\"active\"} offset $diff_intv) by(alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "idle conn.",
     "type": "timeseries",
     "description": "idle connections in this state",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{alias=~\"$alias\",state=\"idle\"}) by(alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\n    sum(pg_stat_activity_count{alias=~\"$alias\",state=\"idle\"} offset $diff_intv) by(alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "\"idle in transaction\" conn.",
     "type": "timeseries",
     "description": "state=\"idle in transaction\" connections in this state",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{alias=~\"$alias\",state=\"idle in transaction\"}) by(alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\n    sum(pg_stat_activity_count{alias=~\"$alias\",state=\"idle in transaction\"} offset $diff_intv) by(alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "\"idle in transaction (aborted)\" conn.",
     "type": "timeseries",
     "description": "state=\"idle in transaction (aborted)\" connections in this state",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{alias=~\"$alias\",state=\"idle in transaction (aborted)\"}) by(alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\n    sum(pg_stat_activity_count{alias=~\"$alias\",state=\"idle in transaction (aborted)\"} offset $diff_intv) by(alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "max_connections",
     "type": "timeseries",
     "description": "Server Parameter: max_connections",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_settings_max_connections{alias=~\"$alias\"}",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\n    pg_settings_max_connections{alias=~\"$alias\"} offset $diff_intv\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "numbackends",
     "type": "timeseries",
     "description": "Number of backends currently connected to this database. This is the only column in this view that returns a value reflecting current state; all other columns return the accumulated values since the last reset.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(pg_stat_database_numbackends{alias=~\"$alias\"}) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(pg_stat_database_numbackends{alias=~\"$alias\"}) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "disabled conn.",
     "type": "timeseries",
     "description": "state=\"disabled\" connections in this state",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{alias=~\"$alias\",state=\"disabled\"}) by(alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\n    sum(pg_stat_activity_count{alias=~\"$alias\",state=\"disabled\"} offset $diff_intv) by(alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "\"fastpath function call\" conn.",
     "type": "timeseries",
     "description": "state=\"fastpath function call\" connections in this state",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{alias=~\"$alias\",state=\"fastpath function call\"}) by(alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\n    sum(pg_stat_activity_count{alias=~\"$alias\",state=\"fastpath function call\"} offset $diff_intv) by(alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  },
  { "title": "Rows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "rows fetched ",
   "type": "timeseries",
   "description": "Number of rows fetched by queries in this database",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_tup_fetched{alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_database_tup_fetched{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_tup_fetched{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "rows inserted",
   "type": "timeseries",
   "description": "Number of rows inserted by queries in this database",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_tup_inserted{alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_database_tup_inserted{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_tup_inserted{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "rows updated ",
   "type": "timeseries",
   "description": "Number of rows updated by queries in this database",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_tup_updated{alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_database_tup_updated{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_tup_updated{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "rows deleted",
   "type": "timeseries",
   "description": "Number of rows deleted by queries in this database",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_tup_deleted{alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_database_tup_deleted{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_tup_deleted{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "rows returned",
   "type": "timeseries",
   "description": "Number of rows returned by queries in this database",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_tup_returned{alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_database_tup_returned{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_tup_returned{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Data blocks Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "blk_read_time",
     "type": "timeseries",
     "description": "Total time the statement spent reading data file blocks, in milliseconds (if track_io_timing is enabled, otherwise zero)",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_database_blk_read_time{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_blk_read_time{alias=~\"$alias\"}[5m])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_database_blk_read_time{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_blk_read_time{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
       "legendFormat": "{{alias}}:{{datname}}:diff"
      }
     ]
    },
    {
     "title": "blk_write_time",
     "type": "timeseries",
     "description": "Total time the statement spent writing data file blocks, in milliseconds (if track_io_timing is enabled, otherwise zero)",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_database_blk_write_time{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_blk_write_time{alias=~\"$alias\"}[5m])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_database_blk_write_time{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_blk_write_time{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
       "legendFormat": "{{alias}}:{{datname}}:diff"
      }
     ]
    },
    {
     "title": "blks_read",
     "type": "timeseries",
     "description": "Number of disk blocks read in this database",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_database_blks_read{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_blks_read{alias=~\"$alias\"}[5m])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_database_blks_read{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_blks_read{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "blks_hit",
     "type": "timeseries",
     "description": "Number of times disk blocks were found already in the buffer cache, so that a read was not necessary (this only includes hits in the PostgreSQL buffer cache, not the operating system's file system cache)",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_database_blks_hit{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_blks_hit{alias=~\"$alias\"}[5m])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_database_blks_hit{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_blks_hit{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "blks_hit_ratio",
     "type": "timeseries",
     "description": "- It indicates the buffer cache hit rate.\n- = sum(blks_hit) / sum(blks_hit + blks_read)",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_database_blks_hit{alias=~\"$alias\"}[$intv])) by (alias)) / \r\n( sum(rate(pg_stat_database_blks_hit{alias=~\"$alias\"}[$intv])) by (alias) + sum(rate(pg_stat_database_blks_read{alias=~\"$alias\"}[$intv])) by (alias) )",
       "legendFormat": "{{alias}}:{{datname}}"
      },
      {
       "expr": "(\r\n(sum(rate(pg_stat_database_blks_hit{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)) / \r\n( sum(rate(pg_stat_database_blks_hit{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias) + sum(rate(pg_stat_database_blks_read{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias) )\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:{{datname}}:diff"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "commit_count",
     "type": "timeseries",
     "description": "Number of transactions in this database that have been committed",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_database_xact_commit{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_xact_commit{alias=~\"$alias\"}[5m])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_database_xact_commit{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_xact_commit{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "rollback_count",
     "type": "timeseries",
     "description": "Number of transactions in this database that have been rolled back",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_database_xact_rollback{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_xact_rollback{alias=~\"$alias\"}[5m])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_database_xact_rollback{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_xact_rollback{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "deadlock_count",
     "type": "timeseries",
     "description": "Total number of deadlocks detected",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_database_deadlocks{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_deadlocks{alias=~\"$alias\"}[5m])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_database_deadlocks{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_deadlocks{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "lock count",
     "type": "timeseries",
     "description": "Number of locks",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(pg_locks_count{alias=~\"$alias\"}) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(pg_locks_count{alias=~\"$alias\"}) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "long_running_transactions",
     "type": "timeseries",
     "description": "Current number of long running transactions",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(pg_long_running_transactions{alias=~\"$alias\"}) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(pg_long_running_transactions{alias=~\"$alias\"}) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  },
  {
   "title": "bgwriter_buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "maxwritten_clean_total",
     "type": "timeseries",
     "description": "Number of times the background writer stopped a cleaning scan because it had written too many buffers",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(pg_stat_bgwriter_maxwritten_clean_total{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(pg_stat_bgwriter_maxwritten_clean_total{alias=~\"$alias\"}[5m])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nrate(pg_stat_bgwriter_maxwritten_clean_total{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(pg_stat_bgwriter_maxwritten_clean_total{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "buffers_alloc_total",
     "type": "timeseries",
     "description": "Number of buffers allocated",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(pg_stat_bgwriter_buffers_alloc_total{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(pg_stat_bgwriter_buffers_alloc_total{alias=~\"$alias\"}[5m])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nrate(pg_stat_bgwriter_buffers_alloc_total{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(pg_stat_bgwriter_buffers_alloc_total{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "buffers_backend_fsync_total",
     "type": "timeseries",
     "description": "Number of times a backend had to execute its own fsync call (normally the background writer handles those even when the backend does its own write)",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(pg_stat_bgwriter_buffers_backend_fsync_total{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(pg_stat_bgwriter_buffers_backend_fsync_total{alias=~\"$alias\"}[5m])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nrate(pg_stat_bgwriter_buffers_backend_fsync_total{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(pg_stat_bgwriter_buffers_backend_fsync_total{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "buffers_backend_total",
     "type": "timeseries",
     "description": "Number of buffers written directly by a backend",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(pg_stat_bgwriter_buffers_backend_total{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(pg_stat_bgwriter_buffers_backend_total{alias=~\"$alias\"}[5m])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nrate(pg_stat_bgwriter_buffers_backend_total{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(pg_stat_bgwriter_buffers_backend_total{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "buffers_checkpoint_total",
     "type": "timeseries",
     "description": "Number of buffers written during checkpoints",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(pg_stat_bgwriter_buffers_checkpoint_total{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(pg_stat_bgwriter_buffers_checkpoint_total{alias=~\"$alias\"}[5m])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nrate(pg_stat_bgwriter_buffers_checkpoint_total{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(pg_stat_bgwriter_buffers_checkpoint_total{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "buffers_clean_total",
     "type": "timeseries",
     "description": "Number of buffers written by the background writer",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(pg_stat_bgwriter_buffers_clean_total{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(pg_stat_bgwriter_buffers_clean_total{alias=~\"$alias\"}[5m])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nrate(pg_stat_bgwriter_buffers_clean_total{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(pg_stat_bgwriter_buffers_clean_total{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  },
  {
   "title": "Check Point",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Checkpoint",
     "type": "timeseries",
     "description": "- checkpoint execution count\n- checkpoints_timed + checkpoints_req\n- checkpoints_timed: Number of scheduled checkpoints that have been performed\n- checkpoints_req: Number of scheduled checkpoints that have been performed",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "( rate(pg_stat_bgwriter_checkpoints_req_total{alias=~\"$alias\"}[$intv]) + rate(pg_stat_bgwriter_checkpoints_timed_total{alias=~\"$alias\"}[$intv]) )\r\nor\r\n( irate(pg_stat_bgwriter_checkpoints_timed_total{alias=~\"$alias\"}[5m]) + irate(pg_stat_bgwriter_checkpoints_timed_total{alias=~\"$alias\"}[5m]) )",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\n    (rate(pg_stat_bgwriter_checkpoints_timed_total{alias=~\"$alias\"}[$intv] offset $diff_intv) +\r\n     rate(pg_stat_bgwriter_checkpoints_timed_total{alias=~\"$alias\"}[$intv] offset $diff_intv) )\r\nor\r\n    (irate(pg_stat_bgwriter_checkpoints_timed_total{alias=~\"$alias\"}[5m] offset $diff_intv) +\r\n     irate(pg_stat_bgwriter_checkpoints_timed_total{alias=~\"$alias\"}[5m] offset $diff_intv) )\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "checkpoint_write_time",
     "type": "timeseries",
     "description": "Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(pg_stat_bgwriter_checkpoint_write_time_total{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(pg_stat_bgwriter_checkpoint_write_time_total{alias=~\"$alias\"}[5m])",
       "legendFormat": "{{alias}}:{{datname}}"
      },
      {
       "expr": "(\r\nrate(pg_stat_bgwriter_checkpoint_write_time_total{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(pg_stat_bgwriter_checkpoint_write_time_total{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
       "legendFormat": "{{alias}}:{{datname}}:diff"
      }
     ]
    },
    {
     "title": "checkpoint_sync_time",
     "type": "timeseries",
     "description": "Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(pg_stat_bgwriter_checkpoint_sync_time_total{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(pg_stat_bgwriter_checkpoint_sync_time_total{alias=~\"$alias\"}[5m])",
       "legendFormat": "{{alias}}:{{datname}}"
      },
      {
       "expr": "(\r\nrate(pg_stat_bgwriter_checkpoint_sync_time_total{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(pg_stat_bgwriter_checkpoint_sync_time_total{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
       "legendFormat": "{{alias}}:{{datname}}:diff"
      }
     ]
    },
    {
     "title": "checkpoint_buffers",
     "type": "timeseries",
     "description": "Number of buffers written during checkpoints",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(pg_stat_bgwriter_buffers_checkpoint_total{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(pg_stat_bgwriter_buffers_checkpoint_total{alias=~\"$alias\"}[5m])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nrate(pg_stat_bgwriter_buffers_checkpoint_total{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(pg_stat_bgwriter_buffers_checkpoint_total{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  },
  {
   "title": "Conflicts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "conflicts",
     "type": "timeseries",
     "description": "Number of queries canceled due to conflicts with recovery in this database. (Conflicts occur only on standby servers; see pg_stat_database_conflicts for details.)",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_database_conflicts{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_conflicts{alias=~\"$alias\"}[5m])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_database_conflicts{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_conflicts{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "conflicts_bufferpin",
     "type": "timeseries",
     "description": "Number of queries in this database that have been canceled due to pinned buffers",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_database_conflicts_confl_bufferpin{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_conflicts_confl_bufferpin{alias=~\"$alias\"}[5m])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_database_conflicts_confl_bufferpin{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_conflicts_confl_bufferpin{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "conflicts_lock",
     "type": "timeseries",
     "description": "Number of queries in this database that have been canceled due to lock timeouts",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_database_conflicts_confl_lock{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_conflicts_confl_lock{alias=~\"$alias\"}[5m])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_database_conflicts_confl_lock{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_conflicts_confl_lock{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "conflicts_snapshot",
     "type": "timeseries",
     "description": "Number of queries in this database that have been canceled due to old snapshots",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_database_conflicts_confl_snapshot{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_conflicts_confl_snapshot{alias=~\"$alias\"}[5m])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_database_conflicts_confl_snapshot{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_conflicts_confl_snapshot{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "conflicts_tablespace",
     "type": "timeseries",
     "description": "Number of queries in this database that have been canceled due to dropped tablespaces",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_database_conflicts_confl_tablespace{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_conflicts_confl_tablespace{alias=~\"$alias\"}[5m])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_database_conflicts_confl_tablespace{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_conflicts_confl_tablespace{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "WAL Size",
     "type": "timeseries",
     "description": "Total size of WAL segments",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(pg_wal_size_bytes{alias=~\"$alias\"}) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(pg_wal_size_bytes{alias=~\"$alias\"}) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "WAL segments",
     "type": "timeseries",
     "description": "Number of WAL segments",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(pg_wal_segments{alias=~\"$alias\"}) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(pg_wal_segments{alias=~\"$alias\"}) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Archived WAL files",
     "type": "timeseries",
     "description": "Number of WAL files that have been successfully archived",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_archiver_archived_count{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_archiver_archived_count{alias=~\"$alias\"}[5m])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_archiver_archived_count{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_archiver_archived_count{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Failed WAL files",
     "type": "timeseries",
     "description": "Number of failed attempts for archiving WAL files",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_archiver_failed_count{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_archiver_failed_count{alias=~\"$alias\"}[5m])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_archiver_failed_count{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_archiver_failed_count{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "current_wal_lsn_bytes",
     "type": "timeseries",
     "description": "WAL position in bytes",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_stat_replication_pg_current_wal_lsn_bytes{alias=~\"$alias\"}",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\npg_stat_replication_pg_current_wal_lsn_bytes{alias=~\"$alias\"} offset $diff_intv\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "WAL last_archive_age",
     "type": "timeseries",
     "description": "Time in seconds since last WAL segment was successfully archived",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "pg_stat_archiver_last_archive_age{alias=~\"$alias\"}",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\npg_stat_archiver_last_archive_age{alias=~\"$alias\"} offset $diff_intv\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "WAL lsn_diff",
     "type": "timeseries",
     "description": "Lag in bytes between master and slave",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_stat_replication_pg_wal_lsn_diff{alias=~\"$alias\"}",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\npg_stat_replication_pg_wal_lsn_diff{alias=~\"$alias\"} offset $diff_intv\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  },
  {
   "title": "Etc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Size",
     "type": "timeseries",
     "description": "Disk space used by the database",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(pg_database_size_bytes{alias=~\"$alias\"}) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(pg_database_size_bytes{alias=~\"$alias\"}) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "temp files created",
     "type": "timeseries",
     "description": "Number of temporary files created by queries in this database. All temporary files are counted, regardless of why the temporary file was created (e.g., sorting or hashing), and regardless of the log_temp_files setting.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_database_temp_files{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_temp_files{alias=~\"$alias\"}[5m])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_database_temp_files{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_temp_files{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "temp write (bytes)",
     "type": "timeseries",
     "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_database_temp_bytes{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_temp_bytes{alias=~\"$alias\"}[5m])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nsum(rate(pg_stat_database_temp_bytes{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_temp_bytes{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Max Age (Frozen XID)",
     "type": "timeseries",
     "description": "Age of the oldest transaction ID that has not been frozen.",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(pg_database_wraparound_age_datfrozenxid_seconds{alias=~\"$alias\"}) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "(\r\nmax(pg_database_wraparound_age_datfrozenxid_seconds{alias=~\"$alias\"} offset $diff_intv) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  },
  {
   "title": "Version Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "pg_static{alias=~\"$alias\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}