{
 "title": "PostgreSQL Overview",
 "description": "PostgreSQL Overview",
 "tags": [
  "CI-TEC",
  "PostgreSQL",
  "Main"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": { "query": "label_values(pg_up,job)" } },
   {
    "name": "alias",
    "label": "Instance",
    "query": {
     "query": "label_values(pg_up{job=~\"$group\"},alias)"
    }
   },
   { "name": "intv", "label": "Interval", "query": "30s, 1m, 5m, 30m, 1h, 6h, 12h" },
   { "name": "use_diff", "label": "Comparison", "query": "On : 1, Off : 0" },
   { "name": "diff_intv", "label": "Comp. Period", "query": "1d" }
  ]
 },
 "panels": [
  { "title": "DB & Exporter State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "scrape_samples_scraped{job!=\"prometheus\"} * 1\r\n   unless (mysql_up{alias!~\"$alias\"} == 1)\r\n   unless (my_up{alias!~\"$alias\"} == 1)\r\n   unless (oracledb_up{alias!~\"$alias\"} == 1)\r\n   unless (pg_up{alias!~\"$alias\"} == 1)\r\n   unless (mssql_batch_requests{alias!~\"$alias\"} >= 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "up{job!=\"prometheus\"}\r\n   unless (mysql_up{alias!~\"$alias\"} == 1)\r\n   unless (my_up{alias!~\"$alias\"} == 1)\r\n   unless (oracledb_up{alias!~\"$alias\"} == 1)\r\n   unless (pg_up{alias!~\"$alias\"} == 1)\r\n   unless (mssql_batch_requests{alias!~\"$alias\"} >= 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "scrape_duration_seconds{job!=\"prometheus\"} * 1000\r\n   unless (mysql_up{alias!~\"$alias\"} == 1)\r\n   unless (my_up{alias!~\"$alias\"} == 1)\r\n   unless (oracledb_up{alias!~\"$alias\"} == 1)\r\n   unless (pg_up{alias!~\"$alias\"} == 1)\r\n   unless (mssql_batch_requests{alias!~\"$alias\"} >= 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape_time",
   "type": "timeseries",
   "description": "- The time taken for Prometheus to scrape metrics from a target. It helps identify performance issues or delays in data collection.",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(scrape_duration_seconds{alias=~\"$alias\", job!=\"prometheus\"}[$intv])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Scrape_count",
   "type": "timeseries",
   "description": "- The total number of samples successfully scraped from a target. It helps monitor the volume of data collected during each scrape.",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(scrape_samples_scraped{alias=~\"$alias\", job!=\"prometheus\"}[$intv])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "$alias", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "alias" },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_up{alias=\"$alias\"}",
     "legendFormat": "DB"
    },
    {
     "expr": "up{alias=\"$alias\"}",
     "legendFormat": "exporter"
    }
   ]
  },
  {
   "title": "SQL Time",
   "type": "timeseries",
   "description": "Total time spent in the statement, in seconds",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_topsql_seconds_total{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_seconds_total{alias=~\"$alias\"}[5m])) by (alias)\r\n\r\n",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_topsql_seconds_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_seconds_total{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "SQL Executions",
   "type": "timeseries",
   "description": "Number of times executed, in seconds",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_topsql_calls_total{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_calls_total{alias=~\"$alias\"}[5m])) by (alias)\r\n\r\n",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_topsql_calls_total{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_topsql_calls_total{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "rows fetched ",
   "type": "timeseries",
   "description": "Number of rows fetched by queries in this database",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_tup_fetched{alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_database_tup_fetched{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_tup_fetched{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "deadlock_count",
   "type": "timeseries",
   "description": "Total number of deadlocks detected",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_deadlocks{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_deadlocks{alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_database_deadlocks{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_deadlocks{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Active conn.",
   "type": "timeseries",
   "description": "Active connections in this state",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{alias=~\"$alias\",state=\"active\"}) by(alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\n    sum(pg_stat_activity_count{alias=~\"$alias\",state=\"active\"} offset $diff_intv) by(alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Connection count",
   "type": "timeseries",
   "description": "Number of connections",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{alias=\"$alias\"}) by(alias) / sum(pg_settings_max_connections{alias=\"$alias\"}) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(pg_stat_activity_count{alias=\"$alias\"} offset $diff_intv) by(alias) / sum(pg_settings_max_connections{alias=\"$alias\"} offset $diff_intv) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "blk_read_time",
   "type": "timeseries",
   "description": "Total time the statement spent reading data file blocks, in milliseconds (if track_io_timing is enabled, otherwise zero)",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_blk_read_time{alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(pg_stat_database_blk_read_time{alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(pg_stat_database_blk_read_time{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(pg_stat_database_blk_read_time{alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
     "legendFormat": "{{alias}}:{{datname}}:diff"
    }
   ]
  }
 ]
}