{
 "title": "1. MySQL Overview (mysqld_exporter)",
 "description": "MySQL Overview (mysqld_exporter)",
 "tags": [
  "CI-TEC",
  "MySQL",
  "Main",
  "mysqld_exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": { "query": "label_values(mysql_up,job)" } },
   {
    "name": "alias",
    "label": "alias",
    "query": {
     "query": "label_values(mysql_up{job=~\"$group\"},alias)"
    }
   },
   {
    "name": "intv",
    "label": "interval",
    "query": "10s, 30s, 1m, 5m, 30m, 1h, 6h, 12h"
   },
   { "name": "use_diff", "label": "Comparison", "query": "On : 1, Off : 0" },
   { "name": "diff_intv", "label": "Comp. Period", "query": "1d" }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "scrape_samples_scraped{job!=\"prometheus\"} * 1\r\n   unless (mysql_up{alias!~\"$alias\"} == 1)\r\n   unless (my_up{alias!~\"$alias\"} == 1)\r\n   unless (oracledb_up{alias!~\"$alias\"} == 1)\r\n   unless (pg_up{alias!~\"$alias\"} == 1)\r\n   unless (mssql_batch_requests{alias!~\"$alias\"} >= 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "up{job!=\"prometheus\"}\r\n   unless (mysql_up{alias!~\"$alias\"} == 1)\r\n   unless (my_up{alias!~\"$alias\"} == 1)\r\n   unless (oracledb_up{alias!~\"$alias\"} == 1)\r\n   unless (pg_up{alias!~\"$alias\"} == 1)\r\n   unless (mssql_batch_requests{alias!~\"$alias\"} >= 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "scrape_duration_seconds{job!=\"prometheus\"} * 1000\r\n   unless (mysql_up{alias!~\"$alias\"} == 1)\r\n   unless (my_up{alias!~\"$alias\"} == 1)\r\n   unless (oracledb_up{alias!~\"$alias\"} == 1)\r\n   unless (pg_up{alias!~\"$alias\"} == 1)\r\n   unless (mssql_batch_requests{alias!~\"$alias\"} >= 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape_time",
   "type": "timeseries",
   "description": "- The time taken for Prometheus to scrape metrics from a target. It helps identify performance issues or delays in data collection.",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(scrape_duration_seconds{alias=~\"$alias\", job!=\"prometheus\"}[$intv])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Scrape_count",
   "type": "timeseries",
   "description": "- The total number of samples successfully scraped from a target. It helps monitor the volume of data collected during each scrape.",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(scrape_samples_scraped{alias=~\"$alias\", job!=\"prometheus\"}[$intv])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "DB & Exporter State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "$alias", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "alias" },
  {
   "title": "$alias",
   "type": "stat",
   "description": "- The total wait time of the summarized events that are timed.\n- = Active session",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{alias=~\"$alias\"}",
     "legendFormat": "DB State"
    },
    {
     "expr": "mysql_global_status_uptime{alias=~\"$alias\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "SQL Time",
   "type": "timeseries",
   "description": "- The total wait time of the summarized events that are timed.\n- = Active session",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(mysql_perf_schema_events_statements_sum_timer_wait{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(mysql_perf_schema_events_statements_sum_timer_wait{alias=~\"$alias\"}[5m])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nrate(mysql_perf_schema_events_statements_sum_timer_wait{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(mysql_perf_schema_events_statements_sum_timer_wait{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "SQL Exec.",
   "type": "timeseries",
   "description": "The Number of executions per second of statements.",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_perf_schema_events_statements_sum_total{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(mysql_perf_schema_events_statements_sum_total{alias=~\"$alias\"}[5m])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nrate(mysql_perf_schema_events_statements_sum_total{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(mysql_perf_schema_events_statements_sum_total{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "SQL rows read",
   "type": "timeseries",
   "description": "The number of rows read during statements' execution.\n= rows_examined",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_perf_schema_events_statements_sum_rows_examined{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(mysql_perf_schema_events_statements_sum_rows_examined{alias=~\"$alias\"}[5m])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nrate(mysql_perf_schema_events_statements_sum_rows_examined{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(mysql_perf_schema_events_statements_sum_rows_examined{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Slow queries",
   "type": "timeseries",
   "description": "- The number of queries that have taken more than long_query_time.",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(mysql_global_status_slow_queries{alias=~\"$alias\"}[5m])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nrate(mysql_global_status_slow_queries{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(mysql_global_status_slow_queries{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Lock Wait Time",
   "type": "timeseries",
   "description": "The time spent waiting for locks.",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(mysql_perf_schema_events_statements_sum_lock_time{alias=~\"$alias\"}[$intv])/1000000000000\r\nor\r\nirate(mysql_perf_schema_events_statements_sum_lock_time{alias=~\"$alias\"}[5m])/1000000000000",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nrate(mysql_perf_schema_events_statements_sum_lock_time{alias=~\"$alias\"}[$intv] offset $diff_intv)/1000000000000\r\nor\r\nirate(mysql_perf_schema_events_statements_sum_lock_time{alias=~\"$alias\"}[5m] offset $diff_intv)/1000000000000\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Logical reads",
   "type": "timeseries",
   "description": "- The number of logical read requests",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_buffer_pool_read_requests{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(mysql_global_status_innodb_buffer_pool_read_requests{alias=~\"$alias\"}[5m])",
     "legendFormat": "diff_time"
    },
    {
     "expr": "(\r\nrate(mysql_global_status_innodb_buffer_pool_read_requests{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(mysql_global_status_innodb_buffer_pool_read_requests{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Disk reads",
   "type": "timeseries",
   "description": "- The number of requests to read directly from disk. innodb_buffer_pool_reads",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_buffer_pool_reads{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(mysql_global_status_innodb_buffer_pool_reads{alias=~\"$alias\"}[5m])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nrate(mysql_global_status_innodb_buffer_pool_reads{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(mysql_global_status_innodb_buffer_pool_reads{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Handler - read rows",
   "type": "timeseries",
   "description": "- read rows = read_rnd_next + read_next + read_prev\n- read_rnd_next: The number of requests to read the next row in the data file. This value is high if you are doing a lot of table scans.\n- read_next : The number of requests to read the next row in key order. This value is incremented if you are querying an index column with a range constraint or if you are doing an index scan.\n- read_prev: The number of requests to read the previous row in key order. This read method is mainly used to optimize ORDER BY ... DESC.",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_handlers_total{handler=~\"read_rnd_next|read_next|read_prev\",alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(mysql_global_status_handlers_total{handler=~\"read_rnd_next|read_next|read_prev\",alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "diff_time"
    },
    {
     "expr": "(\r\nsum(rate(mysql_global_status_handlers_total{handler=~\"read_rnd_next|read_next|read_prev\",alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(mysql_global_status_handlers_total{handler=~\"read_rnd_next|read_next|read_prev\",alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Threads running",
   "type": "timeseries",
   "description": "- The number of threads that are not sleeping",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(mysql_global_status_threads_running{alias=~\"$alias\"}[$intv])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "avg_over_time(mysql_global_status_threads_running{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Current Conn.",
   "type": "timeseries",
   "description": "- The number of currently open connections",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(mysql_global_status_threads_connected{alias=~\"$alias\"}[$intv])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "avg_over_time(mysql_global_status_threads_connected{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "N/W - In",
   "type": "timeseries",
   "description": "- The number of bytes received from all clients.",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_bytes_received{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(mysql_global_status_bytes_received{alias=~\"$alias\"}[5m])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nrate(mysql_global_status_bytes_received{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(mysql_global_status_bytes_received{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  }
 ]
}