{
 "title": "3. MySQL SQLs (mysqld_exporter)",
 "description": "MySQL SQLs (mysqld_exporter)",
 "tags": [
  "CI-TEC",
  "MySQL",
  "SQL",
  "mysqld_exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": { "query": "label_values(mysql_up,job)" } },
   {
    "name": "alias",
    "label": "alias",
    "query": {
     "query": "label_values(mysql_up{job=~\"$group\"},alias)"
    }
   },
   {
    "name": "intv",
    "label": "interval",
    "query": "10s, 30s, 1m, 5m, 30m, 1h, 6h, 12h"
   },
   { "name": "filter", "label": "Top SQLs Filter" },
   {
    "name": "digest",
    "label": "SQL Detail digest (Min 5 chars.)",
    "query": "input digest"
   },
   { "name": "use_diff", "label": "Comparison", "query": "On : 1, Off : 0" },
   { "name": "diff_intv", "label": "Comp. Period", "query": "1d" }
  ]
 },
 "panels": [
  {
   "title": "Total - SQL Time",
   "type": "timeseries",
   "description": "- The total wait time of the summarized events that are timed.\n- = Active session",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(mysql_perf_schema_events_statements_sum_timer_wait{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(mysql_perf_schema_events_statements_sum_timer_wait{alias=~\"$alias\"}[5m])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nrate(mysql_perf_schema_events_statements_sum_timer_wait{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(mysql_perf_schema_events_statements_sum_timer_wait{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Total - Executions",
   "type": "timeseries",
   "description": "The Number of executions per second of statements.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mysql_perf_schema_events_statements_sum_total{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(mysql_perf_schema_events_statements_sum_total{alias=~\"$alias\"}[5m])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nrate(mysql_perf_schema_events_statements_sum_total{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(mysql_perf_schema_events_statements_sum_total{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Total - Rows examined",
   "type": "timeseries",
   "description": "The number of rows read during statements' execution.",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(mysql_perf_schema_events_statements_sum_rows_examined{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(mysql_perf_schema_events_statements_sum_rows_examined{alias=~\"$alias\"}[5m])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nrate(mysql_perf_schema_events_statements_sum_rows_examined{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(mysql_perf_schema_events_statements_sum_rows_examined{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Total - Rows sent",
   "type": "timeseries",
   "description": "The number of rows returned during statements' execution.",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(mysql_perf_schema_events_statements_sum_rows_sent{alias=~\"$alias\"}[$intv])\r\nor\r\nirate(mysql_perf_schema_events_statements_sum_rows_sent{alias=~\"$alias\"}[5m])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nrate(mysql_perf_schema_events_statements_sum_rows_sent{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\nor\r\nirate(mysql_perf_schema_events_statements_sum_rows_sent{alias=~\"$alias\"}[5m] offset $diff_intv)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)\r\n",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Handler - read rows",
   "type": "timeseries",
   "description": "- read rows = read_rnd_next + read_next + read_prev\n- read_rnd_next: The number of requests to read the next row in the data file. This value is high if you are doing a lot of table scans.\n- read_next : The number of requests to read the next row in key order. This value is incremented if you are querying an index column with a range constraint or if you are doing an index scan.\n- read_prev: The number of requests to read the previous row in key order. This read method is mainly used to optimize ORDER BY ... DESC.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_handlers_total{handler=~\"read_rnd_next|read_next|read_prev\",alias=~\"$alias\"}[$intv])) by (alias)\r\nor\r\nsum(irate(mysql_global_status_handlers_total{handler=~\"read_rnd_next|read_next|read_prev\",alias=~\"$alias\"}[5m])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(\r\nsum(rate(mysql_global_status_handlers_total{handler=~\"read_rnd_next|read_next|read_prev\",alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\nor\r\nsum(irate(mysql_global_status_handlers_total{handler=~\"read_rnd_next|read_next|read_prev\",alias=~\"$alias\"}[5m] offset $diff_intv)) by (alias)\r\n)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  { "title": "Top SQLs Comparison", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "table",
   "description": "Top SQL ordered by Elapsed Time",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(200, \r\n     sum ((mysql_perf_schema_events_statements_seconds_total{digest_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} -\r\n           mysql_perf_schema_events_statements_seconds_total{digest_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} offset $__range)\r\n          or mysql_perf_schema_events_statements_seconds_total{digest_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"})\r\n     by (job, alias, instance, digest, digest_text, schema)\r\n    ) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200, \r\n     sum ((mysql_perf_schema_events_statements_total{digest_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} -\r\n           mysql_perf_schema_events_statements_total{digest_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} offset $__range)\r\n          or mysql_perf_schema_events_statements_total{digest_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"})\r\n     by (job, alias, instance, digest, digest_text, schema)\r\n    ) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200, \r\n     sum ((mysql_perf_schema_events_statements_rows_examined_total{digest_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} -\r\n           mysql_perf_schema_events_statements_rows_examined_total{digest_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} offset $__range)\r\n          or mysql_perf_schema_events_statements_rows_examined_total{digest_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"})\r\n     by (job, alias, instance, digest, digest_text, schema)\r\n    ) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200,(\r\n   sum(max_over_time(mysql_perf_schema_events_statements_seconds_total{alias=~\"$alias\", digest_text=~\"(?s)(?i).*$filter.*\"}[$__range] offset $diff_intv) -\r\n       min_over_time(mysql_perf_schema_events_statements_seconds_total{alias=~\"$alias\", digest_text=~\"(?s)(?i).*$filter.*\"}[$__range] offset $diff_intv))\r\n    by (job, alias, instance, digest, digest_text, schema)\r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200,(\r\n   sum(max_over_time(mysql_perf_schema_events_statements_total{alias=~\"$alias\", digest_text=~\"(?s)(?i).*$filter.*\"}[$__range] offset $diff_intv) -\r\n       min_over_time(mysql_perf_schema_events_statements_total{alias=~\"$alias\", digest_text=~\"(?s)(?i).*$filter.*\"}[$__range] offset $diff_intv))\r\n    by (job, alias, instance, digest, digest_text, schema)\r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200,(\r\n   sum(max_over_time(mysql_perf_schema_events_statements_rows_examined_total{alias=~\"$alias\", digest_text=~\"(?s)(?i).*$filter.*\"}[$__range] offset $diff_intv) -\r\n       min_over_time(mysql_perf_schema_events_statements_rows_examined_total{alias=~\"$alias\", digest_text=~\"(?s)(?i).*$filter.*\"}[$__range] offset $diff_intv))\r\n    by (job, alias, instance, digest, digest_text, schema)\r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top SQLs per executions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Top SQL ordered by Elapsed Time",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(200, \r\n     sum ((mysql_perf_schema_events_statements_seconds_total{digest_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} -\r\n           mysql_perf_schema_events_statements_seconds_total{digest_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} offset $__range)\r\n          or mysql_perf_schema_events_statements_seconds_total{digest_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"})\r\n     by (job, alias, instance, digest, digest_text, schema)\r\n    ) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(200, \r\n     sum ((mysql_perf_schema_events_statements_total{digest_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} -\r\n           mysql_perf_schema_events_statements_total{digest_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} offset $__range)\r\n          or mysql_perf_schema_events_statements_total{digest_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"})\r\n     by (job, alias, instance, digest, digest_text, schema)\r\n    ) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(200, \r\n     sum ((mysql_perf_schema_events_statements_rows_examined_total{digest_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} -\r\n           mysql_perf_schema_events_statements_rows_examined_total{digest_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"} offset $__range)\r\n          or mysql_perf_schema_events_statements_rows_examined_total{digest_text=~\"(?s)(?i).*$filter.*\", alias=~\"$alias\"})\r\n     by (job, alias, instance, digest, digest_text, schema)\r\n    ) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(200,(\r\n   sum(max_over_time(mysql_perf_schema_events_statements_seconds_total{alias=~\"$alias\", digest_text=~\"(?s)(?i).*$filter.*\"}[$__range] offset $diff_intv) -\r\n       min_over_time(mysql_perf_schema_events_statements_seconds_total{alias=~\"$alias\", digest_text=~\"(?s)(?i).*$filter.*\"}[$__range] offset $diff_intv))\r\n    by (job, alias, instance, digest, digest_text, schema)\r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(200,(\r\n   sum(max_over_time(mysql_perf_schema_events_statements_total{alias=~\"$alias\", digest_text=~\"(?s)(?i).*$filter.*\"}[$__range] offset $diff_intv) -\r\n       min_over_time(mysql_perf_schema_events_statements_total{alias=~\"$alias\", digest_text=~\"(?s)(?i).*$filter.*\"}[$__range] offset $diff_intv))\r\n    by (job, alias, instance, digest, digest_text, schema)\r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(200,(\r\n   sum(max_over_time(mysql_perf_schema_events_statements_rows_examined_total{alias=~\"$alias\", digest_text=~\"(?s)(?i).*$filter.*\"}[$__range] offset $diff_intv) -\r\n       min_over_time(mysql_perf_schema_events_statements_rows_examined_total{alias=~\"$alias\", digest_text=~\"(?s)(?i).*$filter.*\"}[$__range] offset $diff_intv))\r\n    by (job, alias, instance, digest, digest_text, schema)\r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Top SQL ordered by Elapsed Time",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk(5, \r\n     sum ((mysql_perf_schema_events_statements_seconds_total{digest=~\"$digest.*\", alias=~\"$alias\"} -\r\n           mysql_perf_schema_events_statements_seconds_total{digest=~\"$digest.*\", alias=~\"$alias\"} offset $__range)\r\n          or mysql_perf_schema_events_statements_seconds_total{digest=~\"$digest.*\", alias=~\"$alias\"})\r\n     by (job, alias, instance, digest, digest_text, schema)\r\n    ) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SQL Time(/s)",
     "type": "timeseries",
     "description": "perf_schema_events_statements_seconds_total (per sec).",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_seconds_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_seconds_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
       "legendFormat": "{{schema}}: {{digest}}"
      },
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_seconds_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_seconds_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{schema}}: diff"
      }
     ]
    },
    {
     "title": "Executions",
     "type": "timeseries",
     "description": "The number of executions per second of statements.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
       "legendFormat": "{{schema}}: {{digest}}"
      },
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{schema}}: diff"
      }
     ]
    },
    {
     "title": "rows_examined",
     "type": "timeseries",
     "description": "The number of rows read during statements' execution.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_rows_examined_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_rows_examined_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
       "legendFormat": "{{schema}}: {{digest}}"
      },
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_rows_examined_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_rows_examined_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{schema}}: diff"
      }
     ]
    },
    {
     "title": "sort_rows",
     "type": "timeseries",
     "description": "The number of rows sorted.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_sort_rows_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_sort_rows_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
       "legendFormat": "{{schema}}: {{digest}}"
      },
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_sort_rows_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_sort_rows_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{schema}}: diff"
      }
     ]
    },
    {
     "title": "rows_sent",
     "type": "timeseries",
     "description": "The number of rows returned.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_rows_sent_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_rows_sent_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
       "legendFormat": "{{schema}}: {{digest}}"
      },
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_rows_sent_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_rows_sent_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{schema}}: diff"
      }
     ]
    },
    {
     "title": "no_index_used",
     "type": "timeseries",
     "description": "The number of times no index was found.",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_no_index_used_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_no_index_used_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
       "legendFormat": "{{schema}}: {{digest}}"
      },
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_no_index_used_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_no_index_used_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{schema}}: diff"
      }
     ]
    },
    {
     "title": "created_tmp_disk_tables",
     "type": "timeseries",
     "description": "The number of on-disk temporary tables created.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_tmp_tables_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_tmp_tables_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
       "legendFormat": "{{schema}}: {{digest}}"
      },
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_tmp_tables_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_tmp_tables_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{schema}}: diff"
      }
     ]
    },
    {
     "title": "created_tmp_tables",
     "type": "timeseries",
     "description": "The number of temporary tables created.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_tmp_disk_tables_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_tmp_disk_tables_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
       "legendFormat": "{{schema}}: {{digest}}"
      },
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_tmp_disk_tables_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_tmp_disk_tables_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{schema}}: diff"
      }
     ]
    },
    {
     "title": "sort_merge_passes",
     "type": "timeseries",
     "description": "The number of merge passes by the sort algorithm performed by statements.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_sort_merge_passes_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_sort_merge_passes_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
       "legendFormat": "{{schema}}: {{digest}}"
      },
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_sort_merge_passes_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_sort_merge_passes_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{schema}}: diff"
      }
     ]
    },
    {
     "title": "rows_affected",
     "type": "timeseries",
     "description": "The number of rows affected by statements.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_rows_affected_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_rows_affected_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
       "legendFormat": "{{schema}}: {{digest}}"
      },
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_rows_affected_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_rows_affected_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{schema}}: diff"
      }
     ]
    },
    {
     "title": "errors",
     "type": "timeseries",
     "description": "The number of errors. 0 if SQLSTATE signifies completion (starting with 00) or warning (01), otherwise 1.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_errors_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_errors_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
       "legendFormat": "{{schema}}: {{digest}}"
      },
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_errors_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_errors_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{schema}}: diff"
      }
     ]
    },
    {
     "title": "warnings",
     "type": "timeseries",
     "description": "The number of warnings from the diagnostics area.",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_warnings_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_warnings_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
       "legendFormat": "{{schema}}: {{digest}}"
      },
      {
       "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_warnings_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_warnings_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{schema}}: diff"
      }
     ]
    }
   ]
  }
 ]
}