{
 "title": "MySQL SQL Details",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": { "query": "label_values(mysql_up,job)" } },
   {
    "name": "alias",
    "label": "alias",
    "query": {
     "query": "label_values(mysql_up{job=~\"$group\"},alias)"
    }
   },
   {
    "name": "intv",
    "label": "interval",
    "query": "10s, 30s, 1m, 5m, 30m, 1h, 6h, 12h"
   },
   { "name": "use_diff", "label": "Comparison", "query": "Comparison" },
   { "name": "diff_intv", "label": "Comp. Period", "query": "1d" },
   {
    "name": "digest",
    "label": "SQL Detail digest (Min 5 chars.)"
   },
   { "name": "schema", "label": "schema" },
   { "name": "sql_text", "label": "sql_text" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "digest : $digest<br>\r\n${sql_text}<br>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n<br>\r\n<br>\r\n  Retrieval time\r\n</div>"
   }
  },
  {
   "type": "table",
   "description": "Top SQL ordered by Elapsed Time",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(200, \r\n     sum ((mysql_perf_schema_events_statements_seconds_total{digest=~\"$digest\", alias=~\"$alias\"} -\r\n           mysql_perf_schema_events_statements_seconds_total{digest=~\"$digest\", alias=~\"$alias\"} offset $__range)\r\n          or mysql_perf_schema_events_statements_seconds_total{digest=~\"$digest\", alias=~\"$alias\"})\r\n     by (job, alias, instance, digest, digest_text, schema)\r\n    ) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200, \r\n     sum ((mysql_perf_schema_events_statements_total{digest=~\"$digest\", alias=~\"$alias\"} -\r\n           mysql_perf_schema_events_statements_total{digest=~\"$digest\", alias=~\"$alias\"} offset $__range)\r\n          or mysql_perf_schema_events_statements_total{digest=~\"$digest\", alias=~\"$alias\"})\r\n     by (job, alias, instance, digest, digest_text, schema)\r\n    ) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200, \r\n     sum ((mysql_perf_schema_events_statements_rows_examined_total{digest=~\"$digest\", alias=~\"$alias\"} -\r\n           mysql_perf_schema_events_statements_rows_examined_total{digest=~\"$digest\", alias=~\"$alias\"} offset $__range)\r\n          or mysql_perf_schema_events_statements_rows_examined_total{digest=~\"$digest\", alias=~\"$alias\"})\r\n     by (job, alias, instance, digest, digest_text, schema)\r\n    ) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\nDiff : -${diff_intv}\r\n</div>\r\n"
   }
  },
  {
   "type": "table",
   "description": "Top SQL ordered by Elapsed Time",
   "gridPos": { "h": 2, "w": 20, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(3,(\r\n   sum(max_over_time(mysql_perf_schema_events_statements_seconds_total{alias=\"$alias\", digest=\"$digest\"}[$__range] offset $diff_intv) -\r\n       min_over_time(mysql_perf_schema_events_statements_seconds_total{alias=\"$alias\", digest=\"$digest\"}[$__range] offset $diff_intv))\r\n    by (job, alias, instance, digest, digest_text, schema)\r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(3,(\r\n   sum(max_over_time(mysql_perf_schema_events_statements_total{alias=\"$alias\", digest=\"$digest\"}[$__range] offset $diff_intv) -\r\n       min_over_time(mysql_perf_schema_events_statements_total{alias=\"$alias\", digest=\"$digest\"}[$__range] offset $diff_intv))\r\n    by (job, alias, instance, digest, digest_text, schema)\r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(3,(\r\n   sum(max_over_time(mysql_perf_schema_events_statements_rows_examined_total{alias=\"$alias\", digest=\"$digest\"}[$__range] offset $diff_intv) -\r\n       min_over_time(mysql_perf_schema_events_statements_rows_examined_total{alias=\"$alias\", digest=\"$digest\"}[$__range] offset $diff_intv))\r\n    by (job, alias, instance, digest, digest_text, schema)\r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQL Time(/s)",
   "type": "timeseries",
   "description": "perf_schema_events_statements_seconds_total (per sec).",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_seconds_total{digest=~\"$digest\", schema=~\"$schema\", alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_seconds_total{digest=~\"$digest\", schema=~\"$schema\", alias=\"$alias\"}[5m])\r\n) ",
     "legendFormat": "{{schema}}: {{digest}}"
    },
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_seconds_total{digest=~\"$digest\", schema=~\"$schema\", alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_seconds_total{digest=~\"$digest\", schema=~\"$schema\", alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{schema}}: {{digest}}: diff"
    }
   ]
  },
  {
   "title": "Executions",
   "type": "timeseries",
   "description": "The number of executions per second of statements.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_total{digest=~\"$digest\", schema=~\"$schema\", alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_total{digest=~\"$digest\", schema=~\"$schema\", alias=\"$alias\"}[5m])\r\n) ",
     "legendFormat": "{{schema}}: {{digest}}"
    },
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_total{digest=~\"$digest\", schema=~\"$schema\", alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_total{digest=~\"$digest\", schema=~\"$schema\", alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{schema}}: {{digest}}: diff"
    }
   ]
  },
  {
   "title": "rows_examined",
   "type": "timeseries",
   "description": "The number of rows read during statements' execution.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_rows_examined_total{digest=~\"$digest\", schema=~\"$schema\", alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_rows_examined_total{digest=~\"$digest\", schema=~\"$schema\", alias=\"$alias\"}[5m])\r\n) ",
     "legendFormat": "{{schema}}: {{digest}}"
    },
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_rows_examined_total{digest=~\"$digest\", schema=~\"$schema\", alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_rows_examined_total{digest=~\"$digest\", schema=~\"$schema\", alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{schema}}: {{digest}}: diff"
    }
   ]
  },
  {
   "title": "rows_sent",
   "type": "timeseries",
   "description": "The number of rows returned.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_rows_sent_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_rows_sent_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
     "legendFormat": "{{schema}}: {{digest}}"
    },
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_rows_sent_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_rows_sent_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{schema}}: {{digest}}: diff"
    }
   ]
  },
  {
   "title": "created_tmp_disk_tables",
   "type": "timeseries",
   "description": "The number of on-disk temporary tables created.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_tmp_tables_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_tmp_tables_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
     "legendFormat": "{{schema}}: {{digest}}"
    },
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_tmp_tables_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_tmp_tables_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{schema}}: {{digest}}: diff"
    }
   ]
  },
  {
   "title": "created_tmp_tables",
   "type": "timeseries",
   "description": "The number of temporary tables created.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_tmp_disk_tables_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_tmp_disk_tables_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
     "legendFormat": "{{schema}}: {{digest}}"
    },
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_tmp_disk_tables_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_tmp_disk_tables_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{schema}}: {{digest}}: diff"
    }
   ]
  },
  {
   "title": "rows_affected",
   "type": "timeseries",
   "description": "The number of rows affected by statements.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_rows_affected_total{digest=~\"$digest\", schema=~\"$schema\", alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_rows_affected_total{digest=~\"$digest\", schema=~\"$schema\", alias=\"$alias\"}[5m])\r\n) ",
     "legendFormat": "{{schema}}: {{digest}}"
    },
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_rows_affected_total{digest=~\"$digest\", schema=~\"$schema\", alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_rows_affected_total{digest=~\"$digest\", schema=~\"$schema\", alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{schema}}: {{digest}}: diff"
    }
   ]
  },
  {
   "title": "no_index_used",
   "type": "timeseries",
   "description": "The number of times no index was found.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_no_index_used_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_no_index_used_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
     "legendFormat": "{{schema}}: {{digest}}"
    },
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_no_index_used_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_no_index_used_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{schema}}: {{digest}}: diff"
    }
   ]
  },
  {
   "title": "sort_merge_passes",
   "type": "timeseries",
   "description": "The number of merge passes by the sort algorithm performed by statements.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_sort_merge_passes_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_sort_merge_passes_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
     "legendFormat": "{{schema}}: {{digest}}"
    },
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_sort_merge_passes_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_sort_merge_passes_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{schema}}: {{digest}}: diff"
    }
   ]
  },
  {
   "title": "sort_rows",
   "type": "timeseries",
   "description": "The number of rows sorted.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_sort_rows_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_sort_rows_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
     "legendFormat": "{{schema}}: {{digest}}"
    },
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_sort_rows_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_sort_rows_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{schema}}: {{digest}}: diff"
    }
   ]
  },
  {
   "title": "errors",
   "type": "timeseries",
   "description": "The number of errors. 0 if SQLSTATE signifies completion (starting with 00) or warning (01), otherwise 1.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_errors_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_errors_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
     "legendFormat": "{{schema}}: {{digest}}"
    },
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_errors_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_errors_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{schema}}: {{digest}}: diff"
    }
   ]
  },
  {
   "title": "warnings",
   "type": "timeseries",
   "description": "The number of warnings from the diagnostics area.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_warnings_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv])\r\n   or irate(mysql_perf_schema_events_statements_warnings_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m])\r\n) ",
     "legendFormat": "{{schema}}: {{digest}}"
    },
    {
     "expr": "topk (2,\r\n   rate(mysql_perf_schema_events_statements_warnings_total{digest=~\"$digest.*\",alias=\"$alias\"}[$intv] offset $diff_intv)\r\n   or irate(mysql_perf_schema_events_statements_warnings_total{digest=~\"$digest.*\",alias=\"$alias\"}[5m] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{schema}}: {{digest}}: diff"
    }
   ]
  }
 ]
}