{
 "title": "All DB Overview",
 "description": "All DB Overview",
 "tags": [
  "CI-TEC",
  "Exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "oracle",
    "label": "oracle",
    "query": {
     "query": "label_values(oracledb_up,alias)"
    }
   },
   { "name": "mysql", "label": "mysql", "query": { "query": "label_values(mysql_up,alias)" } },
   { "name": "postgres", "label": "postgres", "query": { "query": "label_values(pg_up,alias)" } },
   {
    "name": "mssql",
    "label": "mssql",
    "query": {
     "query": "label_values(mssql_batch_requests,alias)"
    }
   },
   { "name": "intv", "label": "interval", "query": "30s, 1m, 5m, 30m, 1h, 6h, 12h" },
   { "name": "use_diff", "label": "Comparison", "query": "On : 1, Off : 0" },
   { "name": "diff_intv", "label": "Comp. Period", "query": "1d" }
  ]
 },
 "panels": [
  { "title": "Oracle Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(oracledb_up{}) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(up + (oracledb_up - oracledb_up)) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_duration_seconds + (oracledb_up - oracledb_up)) by (alias, instance, job) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(oracledb_ora_startup_time_minutes + (oracledb_up - oracledb_up)) by (alias, instance, job) * 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_samples_scraped + (oracledb_up - oracledb_up)) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(oracledb_ora_metric_value{metric_name=\"Database Time Per Sec\"}[$__range]) / 100) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(oracledb_ora_metric_value{metric_name=\"Database Time Per Sec\"}[$__range] offset $diff_intv) / 100) by (alias, instance, job)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(oracledb_ora_metric_value{metric_name=\"Host CPU Utilization (%)\"}[$__range]) / 100) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(oracledb_ora_metric_value{metric_name=\"Host CPU Utilization (%)\"}[$__range] offset $diff_intv) / 100) by (alias, instance, job)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(last_over_time(oracledb_instance{}[24h])) by (alias, instance, job, version)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "MS-SQL Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(mssql_batch_requests/mssql_batch_requests) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(up + (mssql_batch_requests - mssql_batch_requests)) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_duration_seconds + (mssql_batch_requests - mssql_batch_requests)) by (alias, instance, job) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(mssql_uptime + (mssql_batch_requests - mssql_batch_requests)) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_samples_scraped + (mssql_batch_requests - mssql_batch_requests)) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(mssql_top_elapsed_sql{}[$__range])/1000000) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(mssql_top_elapsed_sql{}[$__range] offset $diff_intv)/1000000) by (alias, instance, job)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(mssql_top_exec_sql{}[$__range])) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(mssql_top_exec_sql{}[$__range] offset $diff_intv)) by (alias, instance, job)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(last_over_time(mssql_info{info=\"socket_count\"}[24h])) by (alias, instance, job, edition, productversion)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "MySQL Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(mysql_up) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(up + (mysql_up - mysql_up)) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_duration_seconds + (mysql_up - mysql_up)) by (alias, instance, job) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(mysql_global_status_uptime) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_samples_scraped + (mysql_up - mysql_up)) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(mysql_perf_schema_events_statements_sum_timer_wait{}[$__range])) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(mysql_perf_schema_events_statements_sum_timer_wait{}[$__range] offset $diff_intv)) by (alias, instance, job)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(mysql_global_status_handlers_total{handler=~\"read_rnd_next|read_next|read_prev\"}[$__range])) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(mysql_global_status_handlers_total{handler=~\"read_rnd_next|read_next|read_prev\"}[$__range] offset $diff_intv)) by (alias, instance, job)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(pg_up{}) by (alias, instance, job)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(up + (pg_up - pg_up)) by (alias, instance, job)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(scrape_duration_seconds + (pg_up - pg_up)) by (alias, instance, job) * 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(oracledb_ora_startup_time_minutes + (pg_up - pg_up)) by (alias, instance, job) * 60",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(scrape_samples_scraped + (pg_up - pg_up)) by (alias, instance, job)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(pg_stat_topsql_seconds_total{}[$__range])) by (alias, instance, job)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(pg_stat_topsql_seconds_total{}[$__range] offset $diff_intv)) by (alias, instance, job)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(pg_stat_topsql_calls_total{}[$__range])) by (alias, instance, job)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(pg_stat_topsql_calls_total{}[$__range] offset $diff_intv)) by (alias, instance, job)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "TSDB retention Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (prometheus_tsdb_retention_limit_seconds) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TSDB used Storage Size",
     "type": "timeseries",
     "description": "The number of bytes that are currently used for local storage by all blocks.",
     "gridPos": { "h": 7, "w": 7, "x": 2, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_storage_blocks_bytes",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Head_series",
     "type": "timeseries",
     "description": "Total number of series in the head block.\nThe \"head\" of the TSDB refers to the in-memory portion of the database that holds the most recent data. ",
     "gridPos": { "h": 7, "w": 7, "x": 9, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "prometheus_tsdb_head_series", "legendFormat": "{{job}} - {{instance}}" }
     ]
    },
    {
     "title": "Oracle Scrape Duration (s)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
     "targets": [
      {
       "expr": "scrape_duration_seconds{job!=\"prometheus\"} + (oracledb_up - oracledb_up)",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "TSDB retention Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (prometheus_tsdb_retention_limit_bytes) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MS-SQL Scrape Duration (s)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "scrape_duration_seconds{job!=\"prometheus\"} + (mssql_batch_requests - mssql_batch_requests)",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "MySQL Scrape Duration (s)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
     "targets": [
      {
       "expr": "scrape_duration_seconds{job!=\"prometheus\"} + (mysql_up - mysql_up)",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "PostgreSQL Scrape Duration (s)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
     "targets": [
      {
       "expr": "scrape_duration_seconds{job!=\"prometheus\"} + (pg_up - pg_up)",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  }
 ]
}