{
 "title": "SQL Server Multiple Instances",
 "description": "SQL Server Multiple Instances",
 "tags": [
  "CI-TEC",
  "MS-SQL",
  "Others"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(mssql_batch_requests,job)"
    }
   },
   {
    "name": "alias",
    "label": "Instance",
    "query": {
     "query": "label_values(mssql_batch_requests{job=~\"$group\"},alias)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU % - Stat",
   "type": "stat",
   "description": "Current Stat. CPU usage % of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value divided by Base Counter value)",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (alias, db) (\n    mssql_perf_gauge{alias=~\"$alias\",gauge=\"CPU usage %\", db=\"default\"})",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "description": "CPU usage % Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value divided by Base Counter value)",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "avg by (alias, db) (\n    mssql_perf_gauge{alias=~\"$alias\",gauge=\"CPU usage %\", db=\"default\"})",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Memory Usage % - Stat",
   "type": "stat",
   "description": "Current Stat. Memory Usage % Of SYS.DM_OS_SYS_MEMORY.",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_os_memory{alias=~\"$alias\",state=\"pct\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Disk Usage % - Stat",
   "type": "stat",
   "description": "Current Stat. Disk Usage % Of SYS.DM_OS_VOLUME_STATS.",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_drive_used_pct{alias=~\"$alias\"}",
     "legendFormat": "{{alias}} {{drive}}"
    }
   ]
  },
  {
   "title": "Disk Read & Write Kb/Sec",
   "type": "timeseries",
   "description": "Disk Read & Write (Kb) Bytes/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "mssql_perf_gauge{alias=~\"$alias\",gauge=\"Disk Read Bytes/sec\", db=\"default\"}/1024",
     "legendFormat": "{{alias}}-Read"
    },
    {
     "expr": "mssql_perf_gauge{alias=~\"$alias\",gauge=\"Disk Write Bytes/sec\", db=\"default\"}/1024",
     "legendFormat": "{{alias}}-Write"
    }
   ]
  },
  {
   "title": "Active Transactions",
   "type": "timeseries",
   "description": "Active Transactions for Total Databases Of SYS.DM_OS_VOLUME_STATS.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "mssql_perf_gauge{alias=~\"$alias\",gauge=\"Active Transactions\", db=\"_Total\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Connections Count",
   "type": "timeseries",
   "description": "Connection Count Per Databases Of SYS.SYSPROCESSES.",
   "gridPos": { "h": 6, "w": 9, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mssql_connections{alias=~\"$alias\"}",
     "legendFormat": "{{alias}} {{db}}"
    }
   ]
  },
  {
   "title": "Batch Request/Sec",
   "type": "timeseries",
   "description": "Batch Requests/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 6 },
   "targets": [
    {
     "expr": "rate(mssql_batch_requests{alias=~\"$alias\"}[$__rate_interval])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Page Life Expectancy Seconds",
   "type": "timeseries",
   "description": "Page life expectancy Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Absolute value)",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "targets": [
    {
     "expr": "mssql_page_life_expectancy_seconds{alias=~\"$alias\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Lock Requests/Sec",
   "type": "timeseries",
   "description": "Lock Requests/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Lock Requests/sec\", db=\"_Total\"}[$__rate_interval])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Lock Blocks",
   "type": "timeseries",
   "description": "Lock Blocks Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Absolute value)",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "targets": [
    {
     "expr": "mssql_perf_gauge{alias=~\"$alias\",gauge=\"Lock Blocks\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Table Lock Escalstion/Sec",
   "type": "timeseries",
   "description": "Table Lock Escalations/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Table Lock Escalations/sec\"}[$__rate_interval])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Wait Time (sec) by Type",
   "type": "timeseries",
   "description": "Wait Time (sec) Per one second by Type Of SYS.DM_OS_WAIT_STATS.",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(alias, wait_type) (rate(mssql_wait_time_seconds{alias=~\"$alias\"}[$__rate_interval]))",
     "legendFormat": "{{alias}}-{{wait_type}}"
    }
   ]
  },
  {
   "title": "Full Scans/sec",
   "type": "timeseries",
   "description": "Full Scans/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Full Scans/sec\"}[$__rate_interval])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Index Searches/sec",
   "type": "timeseries",
   "description": "Index Searches/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Index Searches/sec\"}[$__rate_interval])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Range Scans/sec",
   "type": "timeseries",
   "description": "Range Scans/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Range Scans/sec\"}[$__rate_interval])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Active Temp Tables",
   "type": "timeseries",
   "description": "Active Temp Tables Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Absolute value)",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "mssql_perf_gauge{alias=~\"$alias\",gauge=\"Active Temp Tables\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Top SQLs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "type": "table",
   "description": "Top SQL ordered by Elapsed Time",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(200,(\r\n   sum(max_over_time(mssql_top_elapsed_sql{alias=~\"$alias\"}[$__range]) / 1000000 -\r\n       min_over_time(mssql_top_elapsed_sql{alias=~\"$alias\"}[$__range]) / 1000000)\r\n    by (job, alias, db, instance, query_hash, partial_query) \r\n))",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200,(\r\n   sum(max_over_time(mssql_top_cpu_sql{alias=~\"$alias\"}[$__range]) / 1000000 -\r\n       min_over_time(mssql_top_cpu_sql{alias=~\"$alias\"}[$__range]) / 1000000)\r\n    by (job, alias, db, instance, query_hash, partial_query) \r\n))",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200,(\r\n   sum(max_over_time(mssql_top_exec_sql{alias=~\"$alias\"}[$__range]) -\r\n       min_over_time(mssql_top_exec_sql{alias=~\"$alias\"}[$__range]))\r\n    by (job, alias, db, instance, query_hash, partial_query) \r\n))",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(200,(\r\n   sum(max_over_time(mssql_top_logical_read_sql{alias=~\"$alias\"}[$__range]) -\r\n       min_over_time(mssql_top_logical_read_sql{alias=~\"$alias\"}[$__range]))\r\n    by (job, alias, db, instance, query_hash, partial_query) \r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Session Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Session Waits",
     "type": "table",
     "description": "Wait Session List, ordered by CPU Time(ms).",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "mssql_sess_wtime_sec{alias=~\"$alias\"}",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU % - Stat",
     "type": "stat",
     "description": "Current Stat. CPU usage % of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value divided by Base Counter value)",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (alias, db) (\n    mssql_perf_gauge{alias=~\"$alias\",gauge=\"CPU usage %\", db=\"default\"})",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "CPU Usage %",
     "type": "timeseries",
     "description": "CPU usage % Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value divided by Base Counter value)",
     "gridPos": { "h": 5, "w": 7, "x": 4, "y": 54 },
     "targets": [
      {
       "expr": "avg by (alias, db) (\n    mssql_perf_gauge{alias=~\"$alias\",gauge=\"CPU usage %\", db=\"default\"})",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Memory Usage % - Stat",
     "type": "stat",
     "description": "Current Stat. Memory Usage % Of SYS.DM_OS_SYS_MEMORY.",
     "gridPos": { "h": 5, "w": 6, "x": 11, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mssql_os_memory{alias=~\"$alias\",state=\"pct\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Memory Free Gb - Stat",
     "type": "stat",
     "description": "Current Stat. Memory Free Gb Of SYS.DM_OS_SYS_MEMORY.",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mssql_os_memory{alias=~\"$alias\",state=\"available\"}/1024/1024/1024",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Disk Usage % - Stat",
     "type": "stat",
     "description": "Current Stat. Disk Usage % Of SYS.DM_OS_VOLUME_STATS.",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mssql_drive_used_pct{alias=~\"$alias\"}",
       "legendFormat": "{{alias}} {{drive}}"
      }
     ]
    },
    {
     "title": "Disk Free Gb - Stat",
     "type": "stat",
     "description": "Current Stat. Disk Free Gb Of SYS.DM_OS_VOLUME_STATS.",
     "gridPos": { "h": 5, "w": 9, "x": 9, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mssql_drive_free_gb{alias=~\"$alias\"}",
       "legendFormat": "{{alias}}  {{drive}}"
      }
     ]
    },
    {
     "title": "Buffer Hit % - Stat",
     "type": "stat",
     "description": "Current Stat. Buffer cache hit ratio % Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value divided by Base Counter value)",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mssql_perf_gauge{alias=~\"$alias\",gauge=\"Buffer cache hit ratio\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Disk Read & Write Kb/Sec",
     "type": "timeseries",
     "description": "Disk Read & Write (Kb) Bytes/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
     "targets": [
      {
       "expr": "mssql_perf_gauge{alias=~\"$alias\",gauge=\"Disk Read Bytes/sec\", db=\"default\"}/1024",
       "legendFormat": "{{alias}}-Read"
      },
      {
       "expr": "mssql_perf_gauge{alias=~\"$alias\",gauge=\"Disk Write Bytes/sec\", db=\"default\"}/1024",
       "legendFormat": "{{alias}}-Write"
      }
     ]
    },
    {
     "title": "Avg Disk Read & Write I/O (ms)",
     "type": "timeseries",
     "description": "Avg Disk Read & Write IO (ms) Per one second Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value divided by Base Counter value)",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
     "targets": [
      {
       "expr": "rate(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Avg Disk Read IO (ms)\", db=\"default\"}[$__rate_interval])",
       "legendFormat": "{{alias}}-Read"
      },
      {
       "expr": "rate(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Avg Disk Write IO (ms)\", db=\"default\"}[$__rate_interval])",
       "legendFormat": "{{alias}}-Write"
      }
     ]
    },
    {
     "title": "DB & Log Size Gb",
     "type": "timeseries",
     "description": "DB & Log Size Gb Of SYS.DM_IO_VIRTUAL_FILE_STATS.",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "mssql_database_size_bytes{alias=~\"$alias\"}/1024/1024/1024",
       "legendFormat": "{{alias}} {{database}} {{file_type}}"
      }
     ]
    },
    {
     "title": "Clerk Size (Mb)",
     "type": "timeseries",
     "description": "Memory Clerk Size (Mb) Of SYS.DM_OS_MEMORY_CLERKS.",
     "gridPos": { "h": 6, "w": 14, "x": 10, "y": 70 },
     "targets": [
      {
       "expr": "mssql_clerk_size_kilobytes{alias=~\"$alias\"}/1024",
       "legendFormat": "{{alias}} {{clerk_type}}"
      }
     ]
    },
    {
     "title": "Page Fault Count",
     "type": "timeseries",
     "description": "Page Fault Count Per one second Of SYS.DM_OS_PROCESS_MEMORY. (Delta value)",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "rate(mssql_page_fault_count{alias=~\"$alias\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Buffer Hit %",
     "type": "timeseries",
     "description": "Buffer cache hit ratio % Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value divided by Base Counter value)",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "mssql_perf_gauge{alias=~\"$alias\",gauge=\"Buffer cache hit ratio\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "General Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Transactions",
     "type": "timeseries",
     "description": "Active Transactions Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Absolute value)",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "mssql_perf_gauge{alias=~\"$alias\",gauge=\"Active Transactions\", db=\"_Total\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Batch Request/Sec",
     "type": "timeseries",
     "description": "Batch Requests/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 55 },
     "targets": [
      {
       "expr": "rate(mssql_batch_requests{alias=~\"$alias\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Active Temp Tables",
     "type": "timeseries",
     "description": "Active Temp Tables Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Absolute value)",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "mssql_perf_gauge{alias=~\"$alias\",gauge=\"Active Temp Tables\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Temp Tables Creation Rate",
     "type": "timeseries",
     "description": "Temp Tables Creation Rate Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 55 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Temp Tables Creation Rate\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Connections Count",
     "type": "timeseries",
     "description": "Connection Count Per Databases Of SYS.SYSPROCESSES.",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "mssql_connections{alias=~\"$alias\"}",
       "legendFormat": "{{alias}} {{db}}"
      }
     ]
    },
    {
     "title": "Active Parallel Threads",
     "type": "timeseries",
     "description": "Active Parallel Threads Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Absolute value)",
     "gridPos": { "h": 6, "w": 5, "x": 9, "y": 61 },
     "targets": [
      {
       "expr": "mssql_perf_gauge{alias=~\"$alias\",gauge=\"Active parallel threads\", db=\"default\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Background Writer Pages/Sec",
     "type": "timeseries",
     "description": "Background writer pages/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 5, "x": 14, "y": 61 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Background writer pages/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Log (Mb) Bytes Flushed/Sec",
     "type": "timeseries",
     "description": "Log (Mb) Bytes Flushed/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 61 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Log Bytes Flushed/sec\", db=\"_Total\"}[$__rate_interval]) / 1024 / 1024",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Page Life Expectancy Seconds",
     "type": "timeseries",
     "description": "Page life expectancy Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Absolute value)",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "mssql_page_life_expectancy_seconds{alias=~\"$alias\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Processes Blocked",
     "type": "timeseries",
     "description": "Processes Blocked Count Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Absolute value)",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 67 },
     "targets": [
      {
       "expr": "mssql_perf_gauge{alias=~\"$alias\",gauge=\"Processes blocked\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Logins/Sec",
     "type": "timeseries",
     "description": "Logins/Sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 5, "x": 14, "y": 67 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Logins/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Logouts/Sec",
     "type": "timeseries",
     "description": "Logouts/Sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 67 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Logouts/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "User Connections",
     "type": "timeseries",
     "description": "User Connections Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Absolute value)",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "mssql_perf_gauge{alias=~\"$alias\",gauge=\"User Connections\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Free Space in tempdb (Mb)",
     "type": "timeseries",
     "description": "Free Space in tempdb (Mb) Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Absolute value)",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 73 },
     "targets": [
      {
       "expr": "mssql_perf_gauge{alias=~\"$alias\",gauge=\"Free Space in tempdb (KB)\"} / 1024",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Cursor Requests/Sec",
     "type": "timeseries",
     "description": "Cursor Requests/Sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 5, "x": 14, "y": 73 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Cursor Requests/sec\", db=\"_Total\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Connect Errors",
     "type": "timeseries",
     "description": "Kill Connection Errors Per one second Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 73 },
     "targets": [
      {
       "expr": "rate(mssql_kill_connection_errors{alias=~\"$alias\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "User Errors",
     "type": "timeseries",
     "description": "User Errors Per one second Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "rate(mssql_user_errors{alias=~\"$alias\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Network IO waits - Waits started/Sec",
     "type": "timeseries",
     "description": "Waits started per second (Network IO waits) Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Absolute value)",
     "gridPos": { "h": 6, "w": 6, "x": 8, "y": 79 },
     "targets": [
      {
       "expr": "rate(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Network IO waits\", db=\"Waits started per second\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Network IO waits - Avg wait time(ms)",
     "type": "timeseries",
     "description": "Avg wait time(ms) (Network IO waits) Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Absolute value)",
     "gridPos": { "h": 6, "w": 5, "x": 14, "y": 79 },
     "targets": [
      {
       "expr": "rate(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Network IO waits\", db=\"Average wait time (ms)\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Network IO waits - Waits in Progress",
     "type": "timeseries",
     "description": "Waits in Progress (Network IO waits) Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Absolute value)",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 79 },
     "targets": [
      {
       "expr": "rate(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Network IO waits\", db=\"Waits in progress\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Wait Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wait Time (sec) by Category",
     "type": "timeseries",
     "description": "Wait Time (sec) Per one second By Category Of SYS.DM_OS_WAIT_STATS.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum by(alias,wait_category) (rate(mssql_wait_time_seconds{alias=~\"$alias\"}[$__rate_interval]))",
       "legendFormat": "{{alias}}-{{wait_category}}"
      }
     ]
    },
    {
     "title": "Wait Time (sec) by Type",
     "type": "timeseries",
     "description": "Wait Time (sec) Per one second By Type Of SYS.DM_OS_WAIT_STATS.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum by(alias,wait_type) (rate(mssql_wait_time_seconds{alias=~\"$alias\"}[$__rate_interval]))",
       "legendFormat": "{{alias}}-{{wait_type}} "
      }
     ]
    },
    {
     "title": "Signal Wait Time (sec) by Wait Type",
     "type": "timeseries",
     "description": "(Thread) Signal Wait Time (sec) Per one second by Wait Type Of SYS.DM_OS_WAIT_STATS.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum by(alias,wait_type) (rate(mssql_signal_wait_time_seconds{alias=~\"$alias\"}[$__rate_interval]))",
       "legendFormat": "{{alias}}-{{wait_type}}"
      }
     ]
    },
    {
     "title": "Waiting Tasks Count by Wait Type",
     "type": "timeseries",
     "description": "Waiting Tasks Count Per one second by Wait Type Of SYS.DM_OS_WAIT_STATS.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum by(alias,wait_type) (rate(mssql_waiting_tasks_count{alias=~\"$alias\"}[$__rate_interval]))",
       "legendFormat": "{{alias}}-{{wait_type}}"
      }
     ]
    },
    {
     "title": "Signal Wait Time (sec) by Wait Category",
     "type": "timeseries",
     "description": "(Thread) Signal Wait Time (sec) Per one second by Wait Category Of SYS.DM_OS_WAIT_STATS.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum by(alias,wait_category) (rate(mssql_signal_wait_time_seconds{alias=~\"$alias\"}[$__rate_interval]))",
       "legendFormat": "{{alias}}-{{wait_category}}"
      }
     ]
    },
    {
     "title": "Waiting Tasks Count by Wait Category",
     "type": "timeseries",
     "description": "(Thread) Waiting Tasks Count Per one second by Wait Category Of SYS.DM_OS_TASKS_STATS.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "sum by(alias,wait_category) (rate(mssql_waiting_tasks_count{alias=~\"$alias\"}[$__rate_interval]))",
       "legendFormat": "{{alias}}-{{wait_category}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Locks & Latches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lock Request/Sec",
     "type": "timeseries",
     "description": "Lock Requests/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Lock Requests/sec\", db=\"_Total\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Lock Wait Time (ms)",
     "type": "timeseries",
     "description": "Lock Wait Time (ms) Per one second For Total Databases Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 57 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Lock Wait Time (ms)\", db=\"_Total\"}[$__rate_interval])",
       "legendFormat": "{{alias}} "
      }
     ]
    },
    {
     "title": "Average Latch Wait Time (ms)",
     "type": "timeseries",
     "description": "Average Latch Wait Time (ms) Per one second Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value divided by Base Counter value)",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 57 },
     "targets": [
      {
       "expr": "rate(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Average Latch Wait Time (ms)\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Lock Waits/Sec",
     "type": "timeseries",
     "description": "Lock Waits/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 57 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Lock Waits/sec\", db=\"_Total\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Avg Wait Time (ms)",
     "type": "timeseries",
     "description": "Avg Wait Time (ms) Per one second For Total Databases Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 57 },
     "targets": [
      {
       "expr": "rate(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Average Wait Time (ms)\", db=\"_Total\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Dead Locks/Sec",
     "type": "timeseries",
     "description": "Number of Deadlocks/sec For Total Databases Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "rate(mssql_deadlocks{alias=~\"$alias\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Table Lock Escalstion/Sec",
     "type": "timeseries",
     "description": "Table Lock Escalations/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 62 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Table Lock Escalations/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Lock Timeout/Sec",
     "type": "timeseries",
     "description": "Lock Timeouts/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 62 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Lock Timeouts/sec\", db=\"_Total\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Lock Blocks",
     "type": "timeseries",
     "description": "Lock Blocks Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Absolute value)",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 62 },
     "targets": [
      {
       "expr": "mssql_perf_gauge{alias=~\"$alias\",gauge=\"Lock Blocks\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Lock Memory Mb",
     "type": "timeseries",
     "description": "Lock Memory (Mb) Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Absolute value)",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 62 },
     "targets": [
      {
       "expr": "mssql_perf_gauge{alias=~\"$alias\",gauge=\"Lock Memory (KB)\"}/1024",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Latch Waits/sec",
     "type": "timeseries",
     "description": "Latch Waits/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Latch Waits/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Page IO latch - Avg Wait Time (ms)",
     "type": "timeseries",
     "description": "Avg Wait Time (ms) (Page IO latch) Per one second Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 67 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Page IO latch waits\", db=\"Average wait time (ms)\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Page IO latch waits - Waits started/sec",
     "type": "timeseries",
     "description": "Waits started/sec (Page IO latch waits) Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Page IO latch waits\", db=\"Waits started per second\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Page IO latch - Waits in Progress",
     "type": "timeseries",
     "description": "Waits in Progress (Page IO latch) Per one second Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 67 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Page IO latch waits\", db=\"Waits in progress\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resident Memory Usage Gb - Stat",
     "type": "stat",
     "description": "Current Stat. Resident Memory Usage Gb Of SYS.DM_OS_PROCESS_MEMORY.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mssql_resident_memory_bytes{alias=~\"$alias\"}/1024/1024/1024",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Memory Grants Outstanding",
     "type": "timeseries",
     "description": "Memory Grants Outstanding Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Absolute value)",
     "gridPos": { "h": 5, "w": 5, "x": 4, "y": 16 },
     "targets": [
      {
       "expr": "mssql_perf_gauge{alias=~\"$alias\",gauge=\"Memory Grants Outstanding\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Memory Grants Pending",
     "type": "timeseries",
     "description": "Memory Grants Pending Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Absolute value)",
     "gridPos": { "h": 5, "w": 5, "x": 9, "y": 16 },
     "targets": [
      {
       "expr": "mssql_perf_gauge{alias=~\"$alias\",gauge=\"Memory Grants Pending\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Readahead pages/sec",
     "type": "timeseries",
     "description": "Readahead pages/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 5, "w": 5, "x": 14, "y": 16 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Readahead pages/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Lazy writes/sec",
     "type": "timeseries",
     "description": "Lazy writes/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 16 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Lazy writes/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Page reads/sec",
     "type": "timeseries",
     "description": "Page reads/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Page reads/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Page writes/sec",
     "type": "timeseries",
     "description": "Page writes/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 21 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Page writes/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Background writer pages/sec",
     "type": "timeseries",
     "description": "Background writer pages/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 5, "w": 6, "x": 10, "y": 21 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Background writer pages/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Checkpoint pages/sec",
     "type": "timeseries",
     "description": "Checkpoint pages/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 21 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Checkpoint pages/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Free list stalls/sec",
     "type": "timeseries",
     "description": "Free list stalls/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 21 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Free list stalls/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Access Method",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Full Scans/sec",
     "type": "timeseries",
     "description": "Full Scans/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Full Scans/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Index Searches/sec",
     "type": "timeseries",
     "description": "Index Searches/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Index Searches/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Range Scans/sec",
     "type": "timeseries",
     "description": "Range Scans/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Range Scans/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Mixed page allocations/sec",
     "type": "timeseries",
     "description": "Mixed page allocations/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Mixed page allocations/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Page Splits/sec",
     "type": "timeseries",
     "description": "Page Splits/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Page Splits/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Extents Allocated/sec",
     "type": "timeseries",
     "description": "Extents Allocated/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 23 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Extents Allocated/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Workfiles Created/sec",
     "type": "timeseries",
     "description": "Workfiles Created/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Workfiles Created/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Worktables Created/sec",
     "type": "timeseries",
     "description": "Worktables Created/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 23 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Worktables Created/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Forwarded Records/sec",
     "type": "timeseries",
     "description": "Forwarded Records/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 23 },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Forwarded Records/sec\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  }
 ]
}