{
 "title": "SQL Server Details",
 "description": "SQL Server Details (2024-11-21)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "alias", "label": "alias" },
   {
    "name": "start_offset",
    "label": "statement_start_offset",
    "query": {
     "query": "query_result(avg_over_time(mssql_top_elapsed_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$diff_intv]))"
    }
   },
   { "name": "intv", "label": "interval", "query": "30s, 1m, 5m, 30m, 1h, 6h, 12h" },
   { "name": "use_diff", "label": "Comparison", "query": "On : 1, Off : 0" },
   { "name": "diff_intv", "label": "Comp. Period", "query": "1d" },
   { "name": "sql_id", "label": "sql_id" },
   { "name": "sql_text", "label": "sql_text" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "sql_id : $sql_id<br>\r\n${sql_text}<br>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 6 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n<br>\r\n<br>\r\n  Retrieval time\r\n</div>"
   }
  },
  {
   "type": "table",
   "description": "Top SQLs ordered by Elapsed Time",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(100,(\r\n   sum(last_over_time(mssql_top_elapsed_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range]) / 1000000 -\r\n       min_over_time(mssql_top_elapsed_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range]) / 1000000)\r\n    by (job, alias, db, instance, sql_handle, plan_handle, statement_start_offset, partial_query) \r\n))",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(100,(\r\n   sum(last_over_time(mssql_top_cpu_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range]) / 1000000 -\r\n       min_over_time(mssql_top_cpu_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range]) / 1000000)\r\n    by (job, alias, db, instance, sql_handle, plan_handle, statement_start_offset) \r\n))",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(100,(\r\n   sum(last_over_time(mssql_top_exec_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range]) -\r\n       min_over_time(mssql_top_exec_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range]))\r\n    by (job, alias, db, instance, sql_handle, plan_handle, statement_start_offset) \r\n))",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(100,(\r\n   sum(last_over_time(mssql_top_logical_read_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range]) -\r\n       min_over_time(mssql_top_logical_read_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range]))\r\n    by (job, alias, db, instance, sql_handle, plan_handle, statement_start_offset) \r\n))",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(100,(\r\n   sum(last_over_time(mssql_top_physical_read_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range]) -\r\n       min_over_time(mssql_top_physical_read_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range]))\r\n    by (job, alias, db, instance, sql_handle, plan_handle, statement_start_offset) \r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 11 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\nDiff : -${diff_intv}\r\n</div>\r\n"
   }
  },
  {
   "type": "table",
   "description": "Top SQLs ordered by Elapsed Time",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(100,(\r\n   sum(last_over_time(mssql_top_elapsed_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range] offset $diff_intv) / 1000000 -\r\n       min_over_time(mssql_top_elapsed_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range] offset $diff_intv) / 1000000)\r\n    by (job, alias, db, instance, sql_handle, plan_handle, statement_start_offset, partial_query) \r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(100,(\r\n   sum(last_over_time(mssql_top_cpu_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range] offset $diff_intv) / 1000000 -\r\n       min_over_time(mssql_top_cpu_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range] offset $diff_intv) / 1000000)\r\n    by (job, alias, db, instance, sql_handle, plan_handle, statement_start_offset) \r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(100,(\r\n   sum(last_over_time(mssql_top_exec_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range] offset $diff_intv) -\r\n       min_over_time(mssql_top_exec_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range] offset $diff_intv))\r\n    by (job, alias, db, instance, sql_handle, plan_handle, statement_start_offset) \r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(100,(\r\n   sum(last_over_time(mssql_top_logical_read_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range] offset $diff_intv) -\r\n       min_over_time(mssql_top_logical_read_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range] offset $diff_intv))\r\n    by (job, alias, db, instance, sql_handle, plan_handle, statement_start_offset) \r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(100,(\r\n   sum(last_over_time(mssql_top_physical_read_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range] offset $diff_intv) -\r\n       min_over_time(mssql_top_physical_read_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$__range] offset $diff_intv))\r\n    by (job, alias, db, instance, sql_handle, plan_handle, statement_start_offset) \r\n)) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Graph - Sum of All", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "SQL Time(s)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(mssql_top_elapsed_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$intv])/1000000) by (alias)",
     "legendFormat": "Basetime"
    },
    {
     "expr": "sum(rate(mssql_top_elapsed_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$intv] offset $diff_intv)/1000000) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "Comp: -$diff_intv"
    }
   ]
  },
  {
   "title": "CPU Time(s)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(mssql_top_cpu_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$intv])/1000000) by (alias)",
     "legendFormat": "Basetime"
    },
    {
     "expr": "sum(rate(mssql_top_cpu_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$intv] offset $diff_intv)/1000000) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "Comp: -$diff_intv"
    }
   ]
  },
  {
   "title": "Executions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mssql_top_exec_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$intv])) by (alias)",
     "legendFormat": "Basetime"
    },
    {
     "expr": "sum(rate(mssql_top_exec_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "Comp: -$diff_intv"
    }
   ]
  },
  {
   "title": "Logical reads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mssql_top_logical_read_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$intv])) by (alias)",
     "legendFormat": "Basetime"
    },
    {
     "expr": "sum(rate(mssql_top_logical_read_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "Comp: -$diff_intv"
    }
   ]
  },
  {
   "title": "Logical writes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mssql_top_logical_writes_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$intv])) by (alias)",
     "legendFormat": "Basetime"
    },
    {
     "expr": "sum(rate(mssql_top_logical_writes_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "Comp: -$diff_intv"
    }
   ]
  },
  {
   "title": "Physical reads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mssql_top_physical_read_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$intv])) by (alias)",
     "legendFormat": "Basetime"
    },
    {
     "expr": "sum(rate(mssql_top_physical_read_sql{alias=\"$alias\", sql_handle=\"$sql_id\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "Comp: -$diff_intv"
    }
   ]
  },
  {
   "title": "Graph - by Each start_offset & plan_handle",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL Time(s)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(mssql_top_elapsed_sql{alias=\"$alias\", sql_handle=\"$sql_id\", statement_start_offset=~\"$start_offset\"}[$intv])/1000000) \r\nby (alias, statement_start_offset, plan_handle)",
       "legendFormat": "{{statement_start_offset}}: {{plan_handle}}"
      },
      {
       "expr": "sum(rate(mssql_top_elapsed_sql{alias=\"$alias\", sql_handle=\"$sql_id\", statement_start_offset=~\"$start_offset\"}[$intv] offset $diff_intv)/1000000) \r\nby (alias, statement_start_offset, plan_handle)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{statement_start_offset}}: {{plan_handle}} - Comp"
      }
     ]
    },
    {
     "title": "CPU Time(s)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(mssql_top_cpu_sql{alias=\"$alias\", sql_handle=\"$sql_id\", statement_start_offset=~\"$start_offset\"}[$intv])/1000000) by (alias, statement_start_offset, plan_handle)",
       "legendFormat": "{{statement_start_offset}}: {{plan_handle}}"
      },
      {
       "expr": "sum(rate(mssql_top_cpu_sql{alias=\"$alias\", sql_handle=\"$sql_id\", statement_start_offset=~\"$start_offset\"}[$intv] offset $diff_intv)/1000000) by (alias, statement_start_offset, plan_handle)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{statement_start_offset}}: {{plan_handle}} - Comp"
      }
     ]
    },
    {
     "title": "Executions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(mssql_top_exec_sql{alias=\"$alias\", sql_handle=\"$sql_id\", statement_start_offset=~\"$start_offset\"}[$intv]))\r\nby (alias, statement_start_offset, plan_handle)",
       "legendFormat": "{{statement_start_offset}}: {{plan_handle}}"
      },
      {
       "expr": "sum(rate(mssql_top_exec_sql{alias=\"$alias\", sql_handle=\"$sql_id\", statement_start_offset=~\"$start_offset\"}[$intv] offset $diff_intv))\r\nby (alias, statement_start_offset, plan_handle)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{statement_start_offset}}: {{plan_handle}} - Comp"
      }
     ]
    },
    {
     "title": "Logical reads",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(mssql_top_logical_read_sql{alias=\"$alias\", sql_handle=\"$sql_id\", statement_start_offset=~\"$start_offset\"}[$intv])) \r\nby (alias, statement_start_offset, plan_handle)",
       "legendFormat": "{{statement_start_offset}}: {{plan_handle}}"
      },
      {
       "expr": "sum(rate(mssql_top_logical_read_sql{alias=\"$alias\", sql_handle=\"$sql_id\", statement_start_offset=~\"$start_offset\"}[$intv] offset $diff_intv)) \r\nby (alias, statement_start_offset, plan_handle)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{statement_start_offset}}: {{plan_handle}} - Comp"
      }
     ]
    },
    {
     "title": "Logical writes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(mssql_top_logical_writes_sql{alias=\"$alias\", sql_handle=\"$sql_id\", statement_start_offset=~\"$start_offset\"}[$intv]))\r\nby (alias, statement_start_offset, plan_handle)",
       "legendFormat": "{{statement_start_offset}}: {{plan_handle}}"
      },
      {
       "expr": "sum(rate(mssql_top_logical_writes_sql{alias=\"$alias\", sql_handle=\"$sql_id\", statement_start_offset=~\"$start_offset\"}[$intv] offset $diff_intv))\r\nby (alias, statement_start_offset, plan_handle)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{statement_start_offset}}: {{plan_handle}} - Comp"
      }
     ]
    },
    {
     "title": "Executions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(mssql_top_exec_sql{alias=\"$alias\", sql_handle=\"$sql_id\", statement_start_offset=~\"$start_offset\"}[$intv]))\r\nby (alias, statement_start_offset, plan_handle)",
       "legendFormat": "{{statement_start_offset}}: {{plan_handle}}"
      },
      {
       "expr": "sum(rate(mssql_top_exec_sql{alias=\"$alias\", sql_handle=\"$sql_id\", statement_start_offset=~\"$start_offset\"}[$intv] offset $diff_intv))\r\nby (alias, statement_start_offset, plan_handle)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{statement_start_offset}}: {{plan_handle}} - Comp"
      }
     ]
    }
   ]
  },
  { "title": "Wait Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "session_id",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(mssql_sess_wtime_sec{alias=\"$alias\", sql_handle=\"$sql_id\"}) by (session_id)",
     "legendFormat": "{{session_id}}"
    }
   ]
  },
  {
   "title": "tx_isolation_level",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(mssql_sess_wtime_sec{alias=\"$alias\", sql_handle=\"$sql_id\"}) by (transaction_isolation_level)",
     "legendFormat": "{{transaction_isolation_level}}"
    }
   ]
  },
  {
   "title": "wait_type",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(mssql_sess_wtime_sec{alias=\"$alias\", sql_handle=\"$sql_id\"}) by (wait_type)",
     "legendFormat": "{{wait_type}}"
    }
   ]
  },
  {
   "title": "program",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(mssql_sess_wtime_sec{alias=\"$alias\", sql_handle=\"$sql_id\"}) by (program)",
     "legendFormat": "{{program}}"
    }
   ]
  }
 ]
}