{
 "title": "SQL Server DB Size",
 "description": "SQL Server DB Size",
 "tags": [
  "CI-TEC",
  "MS-SQL",
  "Others"
 ],
 "time": { "from": "now-3d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(mssql_batch_requests,job)"
    }
   },
   {
    "name": "alias",
    "label": "alias",
    "query": {
     "query": "label_values(mssql_batch_requests{job=~\"$group\"},alias)"
    }
   },
   {
    "name": "database",
    "label": "database",
    "query": {
     "query": "query_result(last_over_time(mssql_file_size_bytes{alias=~\"$alias\", file_type=\"Data File\" }[120m]))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DB Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(mssql_file_size_bytes{alias=~\"$alias\" }[120m])) by (job, alias, instance)",
     "legendFormat": "Total Size"
    },
    {
     "expr": "sum(last_over_time(mssql_file_size_bytes{alias=~\"$alias\", file_type=\"Data File\" }[120m])) by (job, alias, instance)",
     "legendFormat": "Data Size"
    },
    {
     "expr": "sum(last_over_time(mssql_file_size_bytes{alias=~\"$alias\", file_type=\"Log File\" }[120m])) by (job, alias, instance)",
     "legendFormat": "Log Size"
    }
   ]
  },
  {
   "title": "$alias",
   "type": "timeseries",
   "description": "only permenant tablespace usage",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(last_over_time(mssql_file_size_bytes{alias=\"$alias\", file_type=\"Log File\"}[120m])) by (job, alias, instance)",
     "legendFormat": "Log Size"
    },
    {
     "expr": "sum(last_over_time(mssql_file_size_bytes{alias=\"$alias\", file_type=\"Data File\"}[120m])) by (job, alias, instance)",
     "legendFormat": "Data Size"
    },
    {
     "expr": "sum(last_over_time(mssql_file_size_bytes{alias=\"$alias\"}[120m])) by (job, alias, instance)",
     "legendFormat": "Total Size"
    }
   ]
  },
  {
   "title": "Number of DB & File",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(last_over_time(mssql_file_size_bytes{alias=~\"$alias\" }[120m])) by (job, alias, instance, database)) by (job, alias, instance)",
     "legendFormat": "# databases"
    },
    {
     "expr": "count(last_over_time(mssql_file_size_bytes{alias=~\"$alias\", file_type=\"Data File\" }[120m])) by (job, alias, instance)",
     "legendFormat": "# Data Files"
    },
    {
     "expr": "count(last_over_time(mssql_file_size_bytes{alias=~\"$alias\", file_type=\"Log File\" }[120m])) by (job, alias, instance)",
     "legendFormat": "# Log Files"
    }
   ]
  },
  {
   "title": "Mount Point Free Size",
   "type": "table",
   "description": "Top SQL ordered by Elapsed Time",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "sum(last_over_time(mssql_drive_size_gb{alias=~\"$alias\" }[120m])) without (__name__)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(last_over_time(mssql_drive_size_gb{alias=~\"$alias\" }[120m])) without (__name__) - \r\nsum(last_over_time(mssql_drive_free_gb{alias=~\"$alias\" }[120m])) without (__name__)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(last_over_time(mssql_drive_free_gb{alias=~\"$alias\" }[120m])) without (__name__)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(last_over_time(mssql_drive_used_pct{alias=~\"$alias\" }[120m])) without (__name__)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(last_over_time(mssql_drive_free_pct{alias=~\"$alias\" }[120m])) without (__name__)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DB Size per database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "table",
   "description": "Top SQL ordered by Elapsed Time",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(last_over_time(mssql_file_size_bytes{alias=~\"$alias\", file_type=\"Data File\" }[120m])) by (job, alias, instance, database)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(last_over_time(mssql_file_size_bytes{alias=~\"$alias\", file_type=\"Log File\" }[120m])) by (job, alias, instance, database)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(last_over_time(mssql_file_size_bytes{alias=~\"$alias\", file_type=\"Data File\" }[120m])) by (job, alias, instance, database)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(last_over_time(mssql_file_size_bytes{alias=~\"$alias\", file_type=\"Log File\" }[120m])) by (job, alias, instance, database)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(last_over_time(mssql_file_size_bytes{alias=~\"$alias\", file_type=\"Data File\", database=~\"$database\" }[120m])) by (job, alias, instance, database)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Selected database Size Grapth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "$database",
     "type": "timeseries",
     "description": "only permenant tablespace usage",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "repeat": "database",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(last_over_time(mssql_database_size_bytes{alias=\"$alias\", file_type=\"Log File\", database=~\"$database\"}[120m])) by (job, alias, instance, database)",
       "legendFormat": "Log Size"
      },
      {
       "expr": "sum(last_over_time(mssql_database_size_bytes{alias=\"$alias\", file_type=\"Data File\", database=~\"$database\"}[120m])) by (job, alias, instance, database)",
       "legendFormat": "Data Size"
      },
      {
       "expr": "sum(last_over_time(mssql_database_size_bytes{alias=\"$alias\", database=~\"$database\"}[120m])) by (job, alias, instance, database)",
       "legendFormat": "Total Size"
      }
     ]
    }
   ]
  },
  { "title": "File Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Data Files",
   "type": "table",
   "description": "Top SQL ordered by Elapsed Time",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(last_over_time(mssql_file_size_bytes{alias=~\"$alias\", file_type=\"Data File\", database=~\"$database\"  }[120m])) without (__name__)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(last_over_time(mssql_file_growth{alias=~\"$alias\", file_type=\"Data File\", database=~\"$database\"  }[120m])) without (__name__)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(last_over_time(mssql_file_max_pages{alias=~\"$alias\", file_type=\"Data File\", database=~\"$database\"  }[120m])) without (__name__) * 8192",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Files",
   "type": "table",
   "description": "Top SQL ordered by Elapsed Time",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(last_over_time(mssql_file_size_bytes{alias=~\"$alias\", file_type=\"Log File\", database=~\"$database\"  }[120m])) without (__name__)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(last_over_time(mssql_file_growth{alias=~\"$alias\", file_type=\"Log File\", database=~\"$database\"  }[120m])) without (__name__)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(last_over_time(mssql_file_max_pages{alias=~\"$alias\", file_type=\"Log File\", database=~\"$database\"  }[120m])) without (__name__) * 8192",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}