{
 "title": "SQL Server SQLs",
 "description": "SQL Server Statements (2024-08-26)",
 "tags": [
  "CI-TEC",
  "MS-SQL",
  "SQL"
 ],
 "time": { "from": "2025-03-17T21:44:59.807Z", "to": "2025-03-17T22:14:59.807Z" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(mssql_batch_requests,job)"
    }
   },
   {
    "name": "alias",
    "label": "alias",
    "query": {
     "query": "label_values(mssql_batch_requests{job=~\"$group\"},alias)"
    }
   },
   {
    "name": "intv",
    "label": "interval",
    "query": "10s, 30s, 1m, 5m, 30m, 1h, 6h, 12h"
   },
   { "name": "filter", "label": "Top SQLs Filter" },
   { "name": "sql_id", "label": "sql_id Filter (Min 5 chars.)" },
   { "name": "use_diff", "label": "Comparison", "query": "On : 1, Off : 0" },
   { "name": "diff_intv", "label": "Comp. Period", "query": "1d" }
  ]
 },
 "panels": [
  {
   "title": "Total - SQL Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(mssql_top_elapsed_sql{alias=~\"$alias\"}[$intv])/1000000) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(mssql_top_elapsed_sql{alias=~\"$alias\"}[$intv] offset $diff_intv)/1000000) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Total - SQL CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(mssql_top_cpu_sql{alias=~\"$alias\"}[$intv])/1000000) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(mssql_top_cpu_sql{alias=~\"$alias\"}[$intv] offset $diff_intv)/1000000) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Total - Executions",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mssql_top_exec_sql{alias=~\"$alias\"}[$intv])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(mssql_top_exec_sql{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Total - Logical reads",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mssql_top_logical_read_sql{alias=~\"$alias\"}[$intv])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(mssql_top_logical_read_sql{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Total - Physical reads",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mssql_top_physical_read_sql{alias=~\"$alias\"}[$intv])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(mssql_top_physical_read_sql{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Total - Logical writes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mssql_top_logical_writes_sql{alias=~\"$alias\"}[$intv])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(mssql_top_logical_writes_sql{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  { "title": "Top SQLs Comparison", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "table",
   "description": "Top SQL ordered by Elapsed Time",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_elapsed_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\" }[$__range])/1000000\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_cpu_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\"}[$__range])/1000000\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_exec_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\" }[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_logical_read_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\" }[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_physical_read_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\" }[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_elapsed_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\" }[$__range] offset $diff_intv)/1000000\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_cpu_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\" }[$__range] offset $diff_intv)/1000000\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_exec_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\" }[$__range] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_logical_read_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\" }[$__range] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_physical_read_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\" }[$__range] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Top SQLs per executions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "type": "table",
   "description": "Top SQL ordered by Elapsed Time",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_elapsed_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\" }[$__range])/1000000\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_cpu_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\"}[$__range])/1000000\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_exec_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\" }[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_logical_read_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\" }[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_physical_read_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\" }[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_elapsed_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\" }[$__range] offset $diff_intv)/1000000\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_cpu_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\" }[$__range] offset $diff_intv)/1000000\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_exec_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\" }[$__range] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_logical_read_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\" }[$__range] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_physical_read_sql{alias=~\"$alias\", partial_query=~\"(?s)(?i).*$filter.*\",sql_handle=~\"$sql_id.*\" }[$__range] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}