{
 "title": "SQL Server One Instance",
 "description": "SQL Server One Instance",
 "tags": [
  "CI-TEC",
  "MS-SQL",
  "One"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(mssql_batch_requests,job)"
    }
   },
   {
    "name": "alias",
    "label": "alias",
    "query": {
     "query": "label_values(mssql_batch_requests{job=~\"$group\"},alias)"
    }
   },
   { "name": "intv", "label": "interval", "query": "30s, 1m, 5m, 30m, 1h, 6h, 12h" },
   { "name": "use_diff", "label": "Comparison", "query": "On : 1, Off : 0" },
   { "name": "diff_intv", "label": "Comp. Period", "query": "1d" }
  ]
 },
 "panels": [
  {
   "title": "DB Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(last_over_time(mssql_info{alias=~\"$alias\", info=\"cores_per_socket\"}[24h])) by (job, alias, instance, edition, productlevel, productversion, virtual_machine_type)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(mssql_info{alias=~\"$alias\", info=\"cpu_count\"}[24h])) by (job, alias, instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(mssql_info{alias=~\"$alias\", info=\"hyperthread_ratio\"}[24h])) by (job, alias, instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(mssql_info{alias=~\"$alias\", info=\"numa_node_count\"}[24h])) by (job, alias, instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(mssql_info{alias=~\"$alias\", info=\"socket_count\"}[24h])) by (job, alias, instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(mssql_uptime{alias=~\"$alias\"}) by (job, alias, instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(last_over_time(mssql_os_memory{alias=~\"$alias\", state=\"total\"}[24h])) by (job, alias, instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(mssql_resident_memory_bytes{alias=~\"$alias\"}[24h])) by (job, alias, instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(mssql_parameters{alias=~\"$alias\", state=\"value\", name=\"max server memory (MB)\"}[24h])) by (job, alias, instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(mssql_parameters{alias=~\"$alias\", state=\"value\", name=\"min server memory (MB)\"}[24h])) by (job, alias, instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(mssql_parameters{alias=~\"$alias\", state=\"value\", name=\"min memory per query (KB)\"}[24h])) by (job, alias, instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(mssql_parameters{alias=~\"$alias\", state=\"value\", name=\"max worker threads\"}[24h])) by (job, alias, instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(mssql_parameters{alias=~\"$alias\", state=\"value\", name=\"max degree of parallelism\"}[24h])) by (job, alias, instance)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "DB CPU (%)",
   "type": "timeseries",
   "description": "The CPU bandwidth usage by all requests in all workload groups belonging to this pool.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "sum(avg(avg_over_time(mssql_perf_gauge{alias=~\"$alias\", gauge=\"CPU usage %\"}[$intv])) by (alias, db)) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(avg(avg_over_time(mssql_perf_gauge{alias=~\"$alias\", gauge=\"CPU usage %\"}[$intv] offset $diff_intv)) by (alias, db)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "OS Memory Usage (%)",
   "type": "timeseries",
   "description": "= (total_physical_mem. - available_physical_mem.) / total_physical_mem.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "avg_over_time(mssql_os_memory{alias=~\"$alias\",state=\"pct\"}[$intv])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "avg_over_time(mssql_os_memory{alias=~\"$alias\",state=\"pct\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "SQL Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(mssql_top_cpu_sql{alias=~\"$alias\"}[$intv])/1000000) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(mssql_top_cpu_sql{alias=~\"$alias\"}[$intv] offset $diff_intv)/1000000) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "SQL Executions",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mssql_top_exec_sql{alias=~\"$alias\"}[$intv])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(mssql_top_exec_sql{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "SQL Logical reads",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mssql_top_logical_read_sql{alias=~\"$alias\"}[$intv])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(mssql_top_logical_read_sql{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "SQL Physical reads",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mssql_top_physical_read_sql{alias=~\"$alias\"}[$intv])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(mssql_top_physical_read_sql{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Free list stalls/sec",
   "type": "timeseries",
   "description": "Indicates the number of requests per second that had to wait for a free page.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Free list stalls/sec\"}[$intv])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Free list stalls/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Page Life Expectancy (s)",
   "type": "timeseries",
   "description": "- Indicates the minimum number of seconds a page stays in the buffer pool on this node without references.\n- If this value is small, system performance may deteriorate, so the cause must be analyzed and action taken. Larger values ​​indicate better performance and stability.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(mssql_page_life_expectancy_seconds{alias=~\"$alias\"}[$intv])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(avg_over_time(mssql_page_life_expectancy_seconds{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Wait Time (s)",
   "type": "timeseries",
   "description": "Wait Time in Seconds",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mssql_wait_time_seconds{alias=~\"$alias\", wait_category!=\"CPU\"}[$intv])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(mssql_wait_time_seconds{alias=~\"$alias\", wait_category!=\"CPU\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Batch Requests/sec",
   "type": "timeseries",
   "description": "Number of Transact-SQL command batches received per second. This statistic is affected by all constraints (such as I/O, number of users, cache size, complexity of requests, and so on). High batch requests mean good throughput.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mssql_batch_requests{alias=~\"$alias\"}[$intv])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(mssql_batch_requests{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Page lookups/sec",
   "type": "timeseries",
   "description": "Indicates the number of requests per second to find a page in the buffer pool",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Page lookups/sec\"}[$intv])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Page lookups/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Page reads/sec",
   "type": "timeseries",
   "description": "Indicates the number of physical database page reads that are issued per second. This statistic displays the total number of physical page reads across all databases. ",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Page reads/sec\"}[$intv])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Page reads/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "User Connections",
   "type": "timeseries",
   "description": "Counts the number of users currently connected to SQL Server.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"User Connections\"}[$intv])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"User Connections\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Active Transactions",
   "type": "timeseries",
   "description": "The number of currently active transactions of all types.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Active Transactions\", db=\"_Total\"}[$intv])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Active Transactions\", db=\"_Total\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Table Lock Escalations/sec",
   "type": "timeseries",
   "description": "Number of times locks on a table were escalated to the TABLE or HoBT granularity.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Table Lock Escalations/sec\"}[$intv])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Table Lock Escalations/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Full Scan/sec",
   "type": "timeseries",
   "description": "Number of unrestricted full scans per second. These can be either base-table or full-index scan",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Full Scans/sec\"}[$intv])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Full Scans/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Range Scan/sec",
   "type": "timeseries",
   "description": "Number of qualified range scans through indexes per second.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Range Scans/sec\"}[$intv])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Range Scans/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Index Searches/sec",
   "type": "timeseries",
   "description": "Number of index searches per second. These are used to start a range scan, reposition a range scan, revalidate a scan point, fetch a single index record, and search down the index to locate where to insert a new row.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Index Searches/sec\"}[$intv])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Index Searches/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "description": "information about processes that are running on an instance of SQL Server.\n(sys.sysprocesses)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(mssql_connections{alias=~\"$alias\",}[$intv])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(avg_over_time(mssql_connections{alias=~\"$alias\",}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Processes blocked",
   "type": "timeseries",
   "description": "Number of currently blocked processes.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Processes blocked\"}[$intv])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Processes blocked\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  {
   "title": "Processes blocked",
   "type": "timeseries",
   "description": "Number of currently blocked processes.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Processes blocked\"}[$intv])) by (alias)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Processes blocked\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "{{alias}}:diff"
    }
   ]
  },
  { "title": "Top SQLs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "table",
   "description": "Top SQL ordered by Elapsed Time",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_elapsed_sql{alias=~\"$alias\" }[$__range])/1000000\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_cpu_sql{alias=~\"$alias\" }[$__range])/1000000\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_exec_sql{alias=~\"$alias\" }[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_logical_read_sql{alias=~\"$alias\" }[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_physical_read_sql{alias=~\"$alias\" }[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_elapsed_sql{alias=~\"$alias\" }[$__range] offset $diff_intv)/1000000\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_cpu_sql{alias=~\"$alias\" }[$__range] offset $diff_intv)/1000000\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_exec_sql{alias=~\"$alias\" }[$__range] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_logical_read_sql{alias=~\"$alias\" }[$__range] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1000,\r\n     increase(mssql_top_physical_read_sql{alias=~\"$alias\" }[$__range] offset $diff_intv)\r\n) >= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB CPU (%)",
     "type": "timeseries",
     "description": "The CPU bandwidth usage by all requests in all workload groups belonging to this pool.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "sum(avg(avg_over_time(mssql_perf_gauge{alias=~\"$alias\", gauge=\"CPU usage %\"}[$intv])) by (alias, db)) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(avg(avg_over_time(mssql_perf_gauge{alias=~\"$alias\", gauge=\"CPU usage %\"}[$intv] offset $diff_intv)) by (alias, db)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "type": "stat",
     "description": "CPU & Memory Size",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_os_memory{alias=~\"$alias\", state=\"total\"}[$intv])\r\n",
       "legendFormat": "OS Memory"
      },
      {
       "expr": "avg_over_time(mssql_resident_memory_bytes{alias=~\"$alias\"}[$intv])",
       "legendFormat": "DB Used Mem"
      }
     ]
    },
    {
     "title": "OS Memory Usage (%)",
     "type": "timeseries",
     "description": "= (total_physical_mem. - available_physical_mem.) / total_physical_mem.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_os_memory{alias=~\"$alias\",state=\"pct\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(mssql_os_memory{alias=~\"$alias\",state=\"pct\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "OS Memory Free (GB)",
     "type": "timeseries",
     "description": "Size of physical memory available, in GB.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_os_memory{alias=~\"$alias\", state=\"available\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(mssql_os_memory{alias=~\"$alias\", state=\"available\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "mssql memory % of OS",
     "type": "timeseries",
     "description": "Displays the percentage of total OS memory utilized by SQL Server. This metric helps monitor memory allocation efficiency and assess if SQL Server's memory usage aligns with the system's overall capacity.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(avg_over_time(mssql_resident_memory_bytes{alias=~\"$alias\"}[$intv])) by (alias) /\r\navg(avg_over_time(mssql_os_memory{alias=~\"$alias\", state=\"total\"}[$intv])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg(avg_over_time(mssql_resident_memory_bytes{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias) /\r\navg(avg_over_time(mssql_os_memory{alias=~\"$alias\", state=\"total\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "mssql memory util (%)",
     "type": "timeseries",
     "description": "Specifies the percentage of committed memory that is in the working set",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_memory_utilization_percentage{alias=~\"$alias\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(mssql_memory_utilization_percentage{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "read_io_stall (ms)",
     "type": "timeseries",
     "description": "Total time, in milliseconds, that the users waited for reads issued on the file.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_io_stall_seconds{alias=~\"$alias\", operation=\"read\", db!~\"master|model|msdb\"}[$intv]) * 1000",
       "legendFormat": "{{db}}"
      },
      {
       "expr": "rate(mssql_io_stall_seconds{alias=~\"$alias\", operation=\"read\", db!~\"master|model|msdb\"}[$intv] offset $diff_intv) * 1000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{db}}:diff"
      }
     ]
    },
    {
     "title": "write_io_stall (ms)",
     "type": "timeseries",
     "description": "Total time, in milliseconds, that users waited for writes to be completed on the file.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_io_stall_seconds{alias=~\"$alias\", operation=\"write\", db!~\"master|model|msdb\"}[$intv]) * 1000",
       "legendFormat": "{{db}}"
      },
      {
       "expr": "rate(mssql_io_stall_seconds{alias=~\"$alias\", operation=\"write\", db!~\"master|model|msdb\"}[$intv] offset $diff_intv) * 1000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{db}}:diff"
      }
     ]
    },
    {
     "title": "mssql page fault",
     "type": "timeseries",
     "description": "The number of page faults that were incurred by the SQL Server process",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_page_fault_count{alias=~\"$alias\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_page_fault_count{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "mssql resident memory",
     "type": "timeseries",
     "description": "SQL Server resident memory size (AKA working set).",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_resident_memory_bytes{alias=~\"$alias\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(mssql_resident_memory_bytes{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "mssql virtual memory",
     "type": "timeseries",
     "description": "SQL Server committed virtual memory size",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_virtual_memory_bytes{alias=~\"$alias\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(mssql_virtual_memory_bytes{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Disk Usage (%)",
     "type": "timeseries",
     "description": "Tablespace Usage %",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "mssql_drive_used_pct{alias=~\"$alias\"}",
       "legendFormat": "{{drive}}"
      }
     ]
    },
    {
     "title": "Disk Free (GB)",
     "type": "timeseries",
     "description": "Available free space on the volume.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "mssql_drive_free_gb{alias=~\"$alias\"}",
       "legendFormat": "{{drive}}"
      }
     ]
    },
    {
     "title": "DB file Used GB",
     "type": "timeseries",
     "description": "DB file Used GB",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\r\n  mssql_database_size_bytes{alias=~\"$alias\"},\r\n  \"short_type\",\r\n  \"$1\",\r\n  \"file_type\",\r\n  \"^(.{1,4}).*|^(.*)$\"\r\n)",
       "legendFormat": "{{database}} ({{short_type}})"
      }
     ]
    }
   ]
  },
  {
   "title": "General Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Batch Requests/sec",
     "type": "timeseries",
     "description": "Number of Transact-SQL command batches received per second. This statistic is affected by all constraints (such as I/O, number of users, cache size, complexity of requests, and so on). High batch requests mean good throughput.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_batch_requests{alias=~\"$alias\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_batch_requests{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Connections (processes)",
     "type": "timeseries",
     "description": "information about processes that are running on an instance of SQL Server.\n(sys.sysprocesses)",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(avg_over_time(mssql_connections{alias=~\"$alias\",}[$intv])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(avg_over_time(mssql_connections{alias=~\"$alias\",}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Active Temp Tables",
     "type": "timeseries",
     "description": "Number of temporary tables/table variables in use.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Active Temp Tables\"}[$intv])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Active Temp Tables\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Temp Tables Creation Rate",
     "type": "timeseries",
     "description": "Number of temporary tables/table variables created per second.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Temp Tables Creation Rate\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Temp Tables Creation Rate\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Active parallel threads",
     "type": "timeseries",
     "description": "Active parallel threads",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Active parallel threads\", db=\"default\"}[$intv])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Active parallel threads\", db=\"default\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Processes blocked",
     "type": "timeseries",
     "description": "Number of currently blocked processes.",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Processes blocked\"}[$intv])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Processes blocked\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Background writer pages/sec",
     "type": "timeseries",
     "description": "Number of pages flushed to enforce the recovery interval settings.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Background writer pages/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Background writer pages/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Log Bytes Flushed/sec",
     "type": "timeseries",
     "description": "Total number of log bytes flushed.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Log Bytes Flushed/sec\", db=\"_Total\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Log Bytes Flushed/sec\", db=\"_Total\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Logins/sec",
     "type": "timeseries",
     "description": "Total number of logins started per second. This does not include pooled connections.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Logins/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Logins/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "User Connections",
     "type": "timeseries",
     "description": "Counts the number of users currently connected to SQL Server.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"User Connections\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"User Connections\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Cursor Requests/sec",
     "type": "timeseries",
     "description": "Number of SQL cursor requests received by server.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Cursor Requests/sec\", db=\"_Total\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Cursor Requests/sec\", db=\"_Total\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Kill Connection Errors /sec",
     "type": "timeseries",
     "description": "Number of severe errors that caused SQL Server to kill the connection.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_kill_connection_errors{alias=~\"$alias\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_kill_connection_errors{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "User Errors /sec",
     "type": "timeseries",
     "description": "Number of user errors.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_user_errors{alias=~\"$alias\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_user_errors{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "NW waits - Waits started / sec",
     "type": "timeseries",
     "description": "Number of Network IO waits started per second of the selected type of wait.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Network IO waits\", db=\"Waits started per second\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Network IO waits\", db=\"Waits started per second\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "NW waits - Avg wait time (ms)",
     "type": "timeseries",
     "description": "Average time for the Network IO waits.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Network IO waits\", db=\"Average wait time (ms)\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Network IO waits\", db=\"Average wait time (ms)\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "NW waits - Waits in progress",
     "type": "timeseries",
     "description": "Number of processes currently waiting.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Network IO waits\", db=\"Waits in progress\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Network IO waits\", db=\"Waits in progress\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  },
  {
   "title": "Active Session Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Active Session List",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "mssql_sess_wtime_sec{alias=~\"$alias\", command!=\"AWAITING COMMAND\"}",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Access Method",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Full Scan/sec",
     "type": "timeseries",
     "description": "Number of unrestricted full scans per second. These can be either base-table or full-index scan",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Full Scans/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Full Scans/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Range Scan/sec",
     "type": "timeseries",
     "description": "Number of qualified range scans through indexes per second.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Range Scans/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Range Scans/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Index Searches/sec",
     "type": "timeseries",
     "description": "Number of index searches per second. These are used to start a range scan, reposition a range scan, revalidate a scan point, fetch a single index record, and search down the index to locate where to insert a new row.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Index Searches/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Index Searches/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Forwarded Records/sec",
     "type": "timeseries",
     "description": "Number of records per second fetched through forwarded record pointers.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Forwarded Records/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Forwarded Records/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Page Splits/sec",
     "type": "timeseries",
     "description": "Number of page splits per second that occur as the result of overflowing index pages.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Page Splits/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Page Splits/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Table Lock Escalations/sec",
     "type": "timeseries",
     "description": "Number of times locks on a table were escalated to the TABLE or HoBT granularity.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Table Lock Escalations/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Table Lock Escalations/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Workfiles Created/sec",
     "type": "timeseries",
     "description": "Number of work files created per second. For example, work files could be used to store temporary results for hash joins and hash aggregates.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Workfiles Created/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Workfiles Created/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Worktables Created/sec",
     "type": "timeseries",
     "description": "Number of work tables created per second. For example, work tables could be used to store temporary results for query spool, lob variables, XML variables, and cursors.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Worktables Created/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Worktables Created/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Mixed page allocations/sec",
     "type": "timeseries",
     "description": "Number of pages allocated per second from mixed extents. These could be used for storing the IAM pages and the first eight pages that are allocated to an allocation unit.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Mixed page allocations/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Mixed page allocations/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Extents Allocated/sec",
     "type": "timeseries",
     "description": "Number of extents allocated per second in all databases in this instance of SQL Server.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Extents Allocated/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Extents Allocated/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free list stalls/sec",
     "type": "timeseries",
     "description": "Indicates the number of requests per second that had to wait for a free page.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Free list stalls/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Free list stalls/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Page lookups/sec",
     "type": "timeseries",
     "description": "Indicates the number of requests per second to find a page in the buffer pool",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Page lookups/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Page lookups/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Page reads/sec",
     "type": "timeseries",
     "description": "Indicates the number of physical database page reads that are issued per second. This statistic displays the total number of physical page reads across all databases. ",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Page reads/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Page reads/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Page writes/sec",
     "type": "timeseries",
     "description": "Indicates the number of physical database page writes that are issued per second.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Page writes/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Page writes/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Lazy writes/sec",
     "type": "timeseries",
     "description": "Indicates the number of buffers written per second by the buffer manager's lazy writer. The lazy writer is a system process that flushes out batches of dirty, aged buffers (buffers that contain changes that must be written back to disk before the buffer can be reused for a different page) and makes them available to user processes. The lazy writer eliminates the need to perform frequent checkpoints in order to create available buffers.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Lazy writes/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Lazy writes/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Extents Allocated/sec",
     "type": "timeseries",
     "description": "Total number of non-free cache pages in the buffer pool extension file.",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Extents Allocated/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Extents Allocated/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Readahead pages/sec",
     "type": "timeseries",
     "description": "Indicates the number of pages read per second in anticipation of use.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Readahead pages/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Readahead pages/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Checkpoint pages/sec",
     "type": "timeseries",
     "description": "Indicates the number of pages flushed to disk per second by a checkpoint or other operation that require all dirty pages to be flushed.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Checkpoint pages/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Checkpoint pages/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL Server Clerk Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Memory Clerks",
     "type": "timeseries",
     "description": "all memory clerks that are currently active in the instance of SQL Server.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(avg_over_time(mssql_clerk_size_kilobytes{alias=~\"$alias\"}[$intv])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(avg_over_time(mssql_clerk_size_kilobytes{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Memory - SQLBUFFERPOOL",
     "type": "timeseries",
     "description": "This memory clerk keeps track of commonly the largest memory consumer inside SQL Server - data and index pages. Buffer Pool or data cache keeps data and index pages loaded in memory to provide fast access to data. ",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_clerk_size_kilobytes{alias=~\"$alias\", clerk_type=\"MEMORYCLERK_SQLBUFFERPOOL\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(mssql_clerk_size_kilobytes{alias=~\"$alias\", clerk_type=\"MEMORYCLERK_SQLBUFFERPOOL\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Memory - CACHESTORE_SQLCP",
     "type": "timeseries",
     "description": "This cache store is used for caching ad hoc queries, prepared statements, and server-side cursors in plan cache. Ad hoc queries are commonly language-event T-SQL statements submitted to the server without explicit parameterization.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_clerk_size_kilobytes{alias=~\"$alias\", clerk_type=\"CACHESTORE_SQLCP\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(mssql_clerk_size_kilobytes{alias=~\"$alias\", clerk_type=\"CACHESTORE_SQLCP\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Memory - ALL MEMORYCLERK_",
     "type": "timeseries",
     "description": "https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-memory-clerks-transact-sql?view=sql-server-ver16",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(avg_over_time(mssql_clerk_size_kilobytes{alias=~\"$alias\", clerk_type=~\"MEMORYCLERK_.*\"}[$intv])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(avg_over_time(mssql_clerk_size_kilobytes{alias=~\"$alias\", clerk_type=~\"MEMORYCLERK_.*\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Memory - ALL CACHESTORE_",
     "type": "timeseries",
     "description": "https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-memory-clerks-transact-sql?view=sql-server-ver16",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(avg_over_time(mssql_clerk_size_kilobytes{alias=~\"$alias\", clerk_type=~\"CACHESTORE_.*\"}[$intv])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(avg_over_time(mssql_clerk_size_kilobytes{alias=~\"$alias\", clerk_type=~\"CACHESTORE_.*\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Memory - ALL USERSTORE_",
     "type": "timeseries",
     "description": "https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-memory-clerks-transact-sql?view=sql-server-ver16",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(avg_over_time(mssql_clerk_size_kilobytes{alias=~\"$alias\", clerk_type=~\"USERSTORE_.*\"}[$intv])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(avg_over_time(mssql_clerk_size_kilobytes{alias=~\"$alias\", clerk_type=~\"USERSTORE_.*\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  },
  {
   "title": "Hit Ratio",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffer Cache Hit (%)",
     "type": "timeseries",
     "description": "Indicates the percentage of pages found in the buffer cache without having to read from disk. The ratio is the total number of cache hits divided by the total number of cache lookups over the last few thousand page accesses.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\", gauge=\"Buffer cache hit ratio\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\", gauge=\"Buffer cache hit ratio\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Plan Cache Hit (%) - Total",
     "type": "timeseries",
     "description": "SQL Server uses memory to store objects such as stored procedures, ad hoc and prepared Transact-SQL statements, and triggers.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\", gauge=\"Cache Hit Ratio\", object=\"MSSQL$SQLSVC:Plan Cache\", db=\"_Total\" }[$intv])",
       "legendFormat": "{{object}} - {{db}} "
      },
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\", gauge=\"Cache Hit Ratio\", object=\"MSSQL$SQLSVC:Plan Cache\", db=\"_Total\" }[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Plan Cache Hit (%) - SQL Plans",
     "type": "timeseries",
     "description": "- SQL Plans : Query plans produced from an ad hoc Transact-SQL query, including auto-parameterized queries, or from Transact-SQL statements prepared using sp_prepare or sp_cursorprepare.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\", gauge=\"Cache Hit Ratio\", object=\"MSSQL$SQLSVC:Plan Cache\", db=\"SQL Plans\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\", gauge=\"Cache Hit Ratio\", object=\"MSSQL$SQLSVC:Plan Cache\", db=\"SQL Plans\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Plan Cache Hit (%) - Object Plans",
     "type": "timeseries",
     "description": "- Object Plans : Query plans generated by creating a stored procedure, function, or trigger.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\", gauge=\"Cache Hit Ratio\", object=\"MSSQL$SQLSVC:Plan Cache\", db=\"Object Plans\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\", gauge=\"Cache Hit Ratio\", object=\"MSSQL$SQLSVC:Plan Cache\", db=\"Object Plans\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Catalog Cache Hit (%) - Total",
     "type": "timeseries",
     "description": "Catalog metadata cache hits and lookups.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\", gauge=\"Cache Hit Ratio\", object=\"MSSQL$SQLSVC:Catalog Metadata\", db=\"_Total\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\", gauge=\"Cache Hit Ratio\", object=\"MSSQL$SQLSVC:Catalog Metadata\", db=\"_Total\"}[$intv]offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Catalog Cache Hit (%) - DBs",
     "type": "timeseries",
     "description": "Catalog metadata cache hits and lookups.",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\", gauge=\"Cache Hit Ratio\", object=\"MSSQL$SQLSVC:Catalog Metadata\", db!~\"master|model|msdb|mssqlsystemresource|tempdb|_Total\"}[$intv])",
       "legendFormat": "{{db}}"
      },
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\", gauge=\"Cache Hit Ratio\", object=\"MSSQL$SQLSVC:Catalog Metadata\", db!~\"master|model|msdb|mssqlsystemresource|tempdb|_Total\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{db}}:diff"
      }
     ]
    }
   ]
  },
  {
   "title": "Wait Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wait Time (ms)",
     "type": "table",
     "gridPos": { "h": 10, "w": 16, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(100, last_over_time(mssql_wait_time_seconds{alias=~\"$alias\", wait_category!=\"CPU\"}[$__range])\r\n        - min_over_time(mssql_wait_time_seconds{alias=~\"$alias\", wait_category!=\"CPU\"}[$__range])) * 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(100, last_over_time(mssql_waiting_tasks_count{alias=~\"$alias\", wait_category!=\"CPU\"}[$__range])\r\n        - min_over_time(mssql_waiting_tasks_count{alias=~\"$alias\", wait_category!=\"CPU\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(100, last_over_time(mssql_wait_time_seconds{alias=~\"$alias\", wait_category!=\"CPU\"}[$__range] offset $diff_intv)\r\n        - min_over_time(mssql_wait_time_seconds{alias=~\"$alias\", wait_category!=\"CPU\"}[$__range] offset $diff_intv)) * 1000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(100, last_over_time(mssql_waiting_tasks_count{alias=~\"$alias\", wait_category!=\"CPU\"}[$__range] offset $diff_intv)\r\n        - min_over_time(mssql_waiting_tasks_count{alias=~\"$alias\", wait_category!=\"CPU\"}[$__range] offset $diff_intv))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wait Type Time (ms)",
     "type": "timeseries",
     "description": "- https://fiftynine.io/sql/wait-type-reference/",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sum(\r\nlabel_replace(\r\n  rate(mssql_wait_time_seconds{alias=~\"$alias\", wait_category!=\"CPU\"}[$intv]),\r\n  \"short_wait_type\",\r\n  \"$1\",\r\n  \"wait_type\",\r\n  \"^(.{1,18}).*|^(.*)$\"\r\n)\r\n) by (alias, wait_category, wait_type, short_wait_type)) * 1000 > 0.1",
       "legendFormat": "{{short_wait_type}}"
      }
     ]
    },
    {
     "title": "Wait Type Time ( Diff : $diff_intv )",
     "type": "timeseries",
     "description": "- https://fiftynine.io/sql/wait-type-reference/",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sum(\r\nlabel_replace(\r\n  rate(mssql_wait_time_seconds{alias=~\"$alias\", wait_category!=\"CPU\"}[$intv] offset $diff_intv),\r\n  \"short_wait_type\",\r\n  \"$1\",\r\n  \"wait_type\",\r\n  \"^(.{1,18}).*|^(.*)$\"\r\n)\r\n) by (alias, wait_category, wait_type, short_wait_type)) * 1000 > 0.1",
       "legendFormat": "{{short_wait_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Locks & Latches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lock & Latch Wait Time (ms)",
     "type": "table",
     "gridPos": { "h": 5, "w": 16, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(100, last_over_time(mssql_wait_time_seconds{alias=~\"$alias\", wait_category=~\".*Latch.*|.*Lock.*\"}[$__range])\r\n        - min_over_time(mssql_wait_time_seconds{alias=~\"$alias\", wait_category=~\".*Latch.*|.*Lock.*\"}[$__range])) * 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(100, last_over_time(mssql_waiting_tasks_count{alias=~\"$alias\", wait_category=~\".*Latch.*|.*Lock.*\"}[$__range])\r\n        - min_over_time(mssql_waiting_tasks_count{alias=~\"$alias\", wait_category=~\".*Latch.*|.*Lock.*\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(100, last_over_time(mssql_wait_time_seconds{alias=~\"$alias\", wait_category=~\".*Latch.*|.*Lock.*\"}[$__range] offset $diff_intv)\r\n        - min_over_time(mssql_wait_time_seconds{alias=~\"$alias\", wait_category=~\".*Latch.*|.*Lock.*\"}[$__range] offset $diff_intv)) * 1000\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "__auto"
      },
      {
       "expr": "topk(100, last_over_time(mssql_waiting_tasks_count{alias=~\"$alias\", wait_category=~\".*Latch.*|.*Lock.*\"}[$__range] offset $diff_intv)\r\n        - min_over_time(mssql_waiting_tasks_count{alias=~\"$alias\", wait_category=~\".*Latch.*|.*Lock.*\"}[$__range] offset $diff_intv))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Lock & Latch Wait Type Time (ms)",
     "type": "timeseries",
     "description": "- https://fiftynine.io/sql/wait-type-reference/",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sum(\r\nlabel_replace(\r\n  rate(mssql_wait_time_seconds{alias=~\"$alias\", wait_category=~\".*Latch.*|.*Lock.*\"}[$intv]),\r\n  \"short_wait_type\",\r\n  \"$1\",\r\n  \"wait_type\",\r\n  \"^(.{1,18}).*|^(.*)$\"\r\n)\r\n) by (alias, wait_category, wait_type, short_wait_type)) * 1000",
       "legendFormat": "{{short_wait_type}}"
      }
     ]
    },
    {
     "title": "Dead Locks/Sec",
     "type": "timeseries",
     "description": "Number of Deadlocks/sec For Total Databases Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_deadlocks{alias=~\"$alias\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_deadlocks{alias=~\"$alias\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Lock Timeout/Sec",
     "type": "timeseries",
     "description": "Number of lock requests per second that timed out, including requests for NOWAIT locks.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Lock Timeouts/sec\", db=\"_Total\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Lock Timeouts/sec\", db=\"_Total\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Lock Wait Time (ms)",
     "type": "timeseries",
     "description": "Number of lock requests per second that timed out, including requests for NOWAIT locks.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Lock Wait Time (ms)\", db=\"_Total\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Lock Wait Time (ms)\", db=\"_Total\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Latch Wait Time (ms)",
     "type": "timeseries",
     "description": "Number of lock requests per second that timed out, including requests for NOWAIT locks.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Average Latch Wait Time (ms)\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Average Latch Wait Time (ms)\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  }
 ]
}