{
 "title": "SQL Server Sessions",
 "description": "SQL Server Sessions",
 "tags": [
  "CI-TEC",
  "MS-SQL",
  "Others"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(mssql_batch_requests,job)"
    }
   },
   {
    "name": "alias",
    "label": "alias",
    "query": {
     "query": "label_values(mssql_batch_requests{job=~\"$group\"},alias)"
    }
   },
   { "name": "session_id", "label": "session_id" },
   { "name": "sql_id", "label": "sql_id" },
   { "name": "db", "label": "db" },
   { "name": "command", "label": "command" }
  ]
 },
 "panels": [
  { "title": "Active Session Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Session Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(mssql_sess_wtime_sec{alias=~\"$alias\"})",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "command",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(mssql_sess_wtime_sec{alias=~\"$alias\"}) by (command)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "wait_type",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(mssql_sess_wtime_sec{alias=~\"$alias\"}) by (wait_type)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "session_id",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(mssql_sess_wtime_sec{alias=~\"$alias\", command!=\"AWAITING COMMAND\"}) by (session_id)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "db",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(mssql_sess_wtime_sec{alias=~\"$alias\"}) by (db)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "SQL_ID",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(mssql_sess_wtime_sec{alias=~\"$alias\"}) by (sql_handle)",
     "legendFormat": "{{sql_handle}}"
    }
   ]
  },
  {
   "title": "status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(mssql_sess_wtime_sec{alias=~\"$alias\"}) by (status)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "sql_id",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(mssql_sess_wtime_sec{alias=~\"$alias\"}) by (sql_handle)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "program",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(mssql_sess_wtime_sec{alias=~\"$alias\"}) by (program)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "username",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(mssql_sess_wtime_sec{alias=~\"$alias\"}) by (username)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Active Session Summary by session_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "type": "table",
   "description": "Active Session List",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "mssql_sess_wtime_sec{alias=~\"$alias\", command!=\"AWAITING COMMAND\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Active Session List", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "type": "table",
   "description": "Active Session List",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "mssql_sess_wtime_sec{alias=~\"$alias\", session_id=~\".*$session_id.*\", sql_handle=~\"(?s)(?i).*$sql_id.*\", db=~\"(?s)(?i).*$db.*\", command=~\"(?s)(?i).*$command.*\", command!=\"AWAITING COMMAND\" }",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}