{
 "title": "SQL Server Overview",
 "description": "SQL Server Overview",
 "tags": [
  "CI-TEC",
  "MS-SQL",
  "Main"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(mssql_batch_requests,job)"
    }
   },
   {
    "name": "alias",
    "label": "alias",
    "query": {
     "query": "label_values(mssql_batch_requests{job=~\"$group\"},alias)"
    }
   },
   { "name": "intv", "label": "interval", "query": "30s, 1m, 5m, 30m, 1h, 6h, 12h" },
   { "name": "use_diff", "label": "Comparison", "query": "On : 1, Off : 0" },
   { "name": "diff_intv", "label": "Comp. Period", "query": "1d" }
  ]
 },
 "panels": [
  { "title": "DB & Exporter State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(mssql_batch_requests/mssql_batch_requests) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(up + (mssql_batch_requests - mssql_batch_requests)) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_duration_seconds + (mssql_batch_requests - mssql_batch_requests)) by (alias, instance, job) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(mssql_uptime + (mssql_batch_requests - mssql_batch_requests)) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_samples_scraped + (mssql_batch_requests - mssql_batch_requests)) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(mssql_top_elapsed_sql{}[$__range])/1000000) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(mssql_top_elapsed_sql{}[$__range] offset $diff_intv)/1000000) by (alias, instance, job)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(mssql_top_exec_sql{}[$__range])) by (alias, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(mssql_top_exec_sql{}[$__range] offset $diff_intv)) by (alias, instance, job)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(last_over_time(mssql_info{info=\"socket_count\"}[24h])) by (alias, instance, job, edition, productversion)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$alias",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "alias",
   "collapsed": true,
   "panels": [
    {
     "title": "$alias",
     "type": "stat",
     "description": "- The total wait time of the summarized events that are timed.\n- = Active session",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count({__name__=~\".+\",alias=\"$alias\"}) by (alias, instance, job)",
       "legendFormat": "DB"
      },
      {
       "expr": "up{alias=\"$alias\"}",
       "legendFormat": "Exporter"
      }
     ]
    },
    {
     "title": "DB CPU (%)",
     "type": "timeseries",
     "description": "The CPU bandwidth usage by all requests in all workload groups belonging to this pool.",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "sum(avg(avg_over_time(mssql_perf_gauge{alias=~\"$alias\", gauge=\"CPU usage %\"}[$intv])) by (alias, db)) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(avg(avg_over_time(mssql_perf_gauge{alias=~\"$alias\", gauge=\"CPU usage %\"}[$intv] offset $diff_intv)) by (alias, db)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "OS Memory Usage (%)",
     "type": "timeseries",
     "description": "= (total_physical_mem. - available_physical_mem.) / total_physical_mem.",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_os_memory{alias=~\"$alias\",state=\"pct\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(mssql_os_memory{alias=~\"$alias\",state=\"pct\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "SQL Time",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(mssql_top_cpu_sql{alias=~\"$alias\"}[$intv])/1000000) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(rate(mssql_top_cpu_sql{alias=~\"$alias\"}[$intv] offset $diff_intv)/1000000) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "SQL Executions",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(mssql_top_exec_sql{alias=~\"$alias\"}[$intv])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(rate(mssql_top_exec_sql{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "SQL Logical reads",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(mssql_top_logical_read_sql{alias=~\"$alias\"}[$intv])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(rate(mssql_top_logical_read_sql{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "SQL Physical reads",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 2, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(mssql_top_physical_read_sql{alias=~\"$alias\"}[$intv])) by (alias)",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "sum(rate(mssql_top_physical_read_sql{alias=~\"$alias\"}[$intv] offset $diff_intv)) by (alias)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Table Lock Escalstion",
     "type": "timeseries",
     "description": "Table Lock Escalations/sec Of SYS.DM_OS_PERFORMANCE_COUNTERS. (Delta value)",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Table Lock Escalations/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Table Lock Escalations/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Full Scan/sec",
     "type": "timeseries",
     "description": "Number of unrestricted full scans per second. These can be either base-table or full-index scan",
     "gridPos": { "h": 4, "w": 2, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Full Scans/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Full Scans/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Range Scan/sec",
     "type": "timeseries",
     "description": "Number of qualified range scans through indexes per second.",
     "gridPos": { "h": 4, "w": 2, "x": 18, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Range Scans/sec\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_counter{alias=~\"$alias\",counter=\"Range Scans/sec\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "Avg read IO (ms)",
     "type": "timeseries",
     "description": "Avg Disk Read IO (ms)",
     "gridPos": { "h": 4, "w": 2, "x": 20, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Avg Disk Read IO (ms)\", db=\"default\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "rate(mssql_perf_gauge{alias=~\"$alias\",gauge=\"Avg Disk Read IO (ms)\", db=\"default\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    },
    {
     "title": "User Connections",
     "type": "timeseries",
     "description": "Counts the number of users currently connected to SQL Server.",
     "gridPos": { "h": 4, "w": 2, "x": 22, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"User Connections\"}[$intv])",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "avg_over_time(mssql_perf_gauge{alias=~\"$alias\",gauge=\"User Connections\"}[$intv] offset $diff_intv)\r\n>= ((1-$use_diff)*100000000000000000000000000000000000000000)",
       "legendFormat": "{{alias}}:diff"
      }
     ]
    }
   ]
  }
 ]
}